// Hand-written for the 44th Detachment (The Kuiper Engagements / SciFi modpack).
// Faction: UCNMC - UCN Marine Corp. 17 kits, plain setUnitLoadout format.
//
// Gear notes:
//   Look is TKE, weapons are OPTRE. Everyone wears the UCMR combat shirt
//   (TKE_CombatShirtWArmourUCMR_U_B), TKE_UCMCArmour* plates, UCMR/UCMC
//   helmets and OPTRE_NVG_MVI_UL_HUL; DMs/Spotter swap to boonies and
//   TKE_ReconNVG, Automatic Riflemen (incl. AT) and Mailman wear
//   TKE_UCNPilotHelmRV.
//   Display names follow USMC billets; the role keys (UCNMC_LanceLead,
//   UCNMC_Heavy, ...) are the old internal names and must not change, the
//   ORBAT slots and crates look kits up by key.
//   Primaries by role:
//     Plt Cmdr/Plt Sgt/Radio Op, Squad/Fireteam Ldr - OPTRE_MA32B (7.62, 32rnd)
//     Corpsmen, Mailman                             - OPTRE_MA5K  (7.62, 32rnd)
//     Designated Marksman, Spotter                  - OPTRE_M392_DMR (15rnd)
//     Automatic Rifleman                            - OPTRE_M739_SAW (192rnd box)
//     Automatic Rifleman (AT)                       - M739 SAW + OPTRE_M41_SSR
//     Scout Sniper                                  - OPTRE_SRS99C (14.5mm)
//     Combat Engineer                               - OPTRE_M45ATAC (8 gauge)
//   Sidearm is TKE_UCNPistol, except the Scout Sniper and Combat Engineer who
//   carry the OPTRE_M7 (60rnd 5x23mm) instead.
//   Medical is ACE + KAT (kat_* items); Corpsmen carry the full KAT set.
//   Plt Cmdr/Plt Sgt/Plt Corpsman/Radio Op, Squad Leaders and Corpsmen carry
//   TKE_RadioPackUCN; everyone else (including Fireteam Leaders and the
//   Combat Engineer) carries a plain pack.
//   The second array on each kit is the allowed-swap list for the kit menu.

["UCNMC_BulldogCommander", "Platoon Commander", "UCNMC",
  [["OPTRE_MA32B","OPTRE_MA5Suppressor","OPTRE_M6C_Laser","OPTRE_M6D_Scope_Black",["OPTRE_32Rnd_762x51_Mag",32],[],""],[],["TKE_UCNPistol","","","",["TKE_UCNPistol_mag",15],[],""],["TKE_CombatShirtWArmourUCMR_U_B",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["kat_TXA",2],["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_painkillers",1,10]]],["TKE_UCMCArmour4_2Camo",[["OPTRE_32Rnd_762x51_Mag",8,32],["TKE_UCNPistol_mag",2,15],["TKE_FRAG_mag",2,1],["TKE_SMOKE_mag",2,1],["ACE_Chemlight_IR",2,1],["SmokeShellRed",1,1],["Chemlight_green",1,1],["Chemlight_red",1,1]]],["TKE_RadioPackUCN",[["kat_IV_16",2],["ACE_splint",2],["ACE_MapTools",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_CableTie",4],["ACE_EntrenchingTool",1],["ACE_Kestrel4500",1],["acex_intelitems_notepad",1,1],["tsp_sling",1]]],"TKE_UCMRHelmCamoTeethV2","TKE_UCNFaceWear1Camo1",["ACE_Vector","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","KAT_STS","OPTRE_NVG_MVI_UL_HUL"]],
  ["TKE_UCMRHelmCamo","TKE_UCMRHelmCamoTeeth","TKE_UCMRHelmCamoV2","TKE_UCMRHelmCamoTeethV2","TKE_UCMRHelmOpenCamo","TKE_UCMRHelmOpenCamoTeeth","OPTRE_MA32B","TKE_UCNRifle_Optic","OPTRE_M41_SSR","OPTRE_MA37BGL","OPTRE_MA5K","TKE_UCNDMR","TKE_UCNDMR_Optic","TKE_UCNMMG_Optic","TKE_UCNBPRifleV2_Optic","OPTRE_M6D_Scope_Black","TKE_ThermScope","OPTRE_M393_Scope","OPTRE_M12_Optic_Red","TKE_10xSightV2","OPTRE_32Rnd_762x51_Mag","OPTRE_M41_Twin_AI","TKE_20rnd_969x51_magUCN","TKE_20rnd_969x51_magUCNAP","TKE_25rnd_762x51_mag","TKE_25rnd_762x51_magAP","TKE_30rnd_575x45_magTR","TKE_30rnd_575x45_magAP","TKE_150rnd_62x35_magUCN","TKE_150rnd_62x35_magUCNAP","TKE_100rnd_ucnmmg_mag","TKE_UCNPistol_mag","3Rnd_HE_Grenade_shell","TKE_CombatShirtWArmourUCMR_U_B","TKE_CombatUniCamo_U_B","TKE_CombatUniRolledV1Camo_U_B","TKE_CombatUniRolledV2Camo_U_B","TKE_VoidSuitCamo_U_B","TKE_UCMCArmour4_1Camo","TKE_UCMCArmour4_2Camo","TKE_UCMCArmour6_3Camo","OPTRE_M392_DMR","OPTRE_15Rnd_762x51_Mag"]] call _reg;

["UCNMC_BulldogTwoIC", "Platoon Sergeant / Fires", "UCNMC",
  [["OPTRE_MA32B","OPTRE_MA5Suppressor","OPTRE_M6C_Laser","OPTRE_M6D_Scope_Black",["OPTRE_32Rnd_762x51_Mag",32],[],""],[],["TKE_UCNPistol","","","",["TKE_UCNPistol_mag",15],[],""],["TKE_CombatShirtWArmourUCMR_U_B",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["kat_TXA",2],["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_painkillers",1,10]]],["TKE_UCMCArmour4_2Camo",[["OPTRE_32Rnd_762x51_Mag",8,32],["TKE_UCNPistol_mag",2,15],["TKE_FRAG_mag",2,1],["TKE_SMOKE_mag",2,1],["ACE_Chemlight_IR",2,1],["SmokeShellRed",1,1],["Chemlight_green",1,1],["Chemlight_red",1,1]]],["TKE_RadioPackUCN",[["kat_IV_16",2],["ACE_splint",2],["ACE_MapTools",1],["ACE_RangeCard",1],["ACE_Kestrel4500",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_EntrenchingTool",1],["acex_intelitems_notepad",1,1],["ACE_CableTie",2],["tsp_sling",1]]],"TKE_UCMRHelmCamo","TKE_UCNFaceWear1Camo1",["ACE_Vector","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","KAT_STS","OPTRE_NVG_MVI_UL_HUL"]],
  ["TKE_UCMRHelmOpen","TKE_UCMRHelmCamo","TKE_UCMRHelmCamoTeeth","TKE_UCMRHelmCamoV2","TKE_UCMRHelmCamoTeethV2","TKE_UCMRHelmOpenCamo","TKE_UCMRHelmOpenCamoTeeth","OPTRE_MA32B","TKE_UCNRifle_Optic","OPTRE_M41_SSR","OPTRE_MA37BGL","OPTRE_MA5K","TKE_UCNDMR","TKE_UCNDMR_Optic","TKE_UCNMMG_Optic","TKE_UCNBPRifleV2_Optic","ACE_Yardage450","OPTRE_M6D_Scope_Black","TKE_ThermScope","OPTRE_M393_Scope","OPTRE_M12_Optic_Red","TKE_10xSightV2","OPTRE_32Rnd_762x51_Mag","OPTRE_M41_Twin_AI","TKE_20rnd_969x51_magUCN","TKE_20rnd_969x51_magUCNAP","TKE_25rnd_762x51_mag","TKE_25rnd_762x51_magAP","TKE_30rnd_575x45_magTR","TKE_30rnd_575x45_magAP","TKE_150rnd_62x35_magUCN","TKE_150rnd_62x35_magUCNAP","TKE_100rnd_ucnmmg_mag","TKE_UCNPistol_mag","3Rnd_HE_Grenade_shell","TKE_CombatShirtWArmourUCMR_U_B","TKE_CombatUniCamo_U_B","TKE_CombatUniRolledV1Camo_U_B","TKE_CombatUniRolledV2Camo_U_B","TKE_VoidSuitCamo_U_B","TKE_UCMCArmour4_1Camo","TKE_UCMCArmour4_2Camo","TKE_UCMCArmour6_3Camo","OPTRE_M392_DMR","OPTRE_15Rnd_762x51_Mag"]] call _reg;

["UCNMC_BulldogCorpsman", "Platoon Corpsman", "UCNMC",
  [["OPTRE_MA5K","OPTRE_MA5Suppressor","OPTRE_M6C_Laser","OPTRE_M6D_Scope_Black",["OPTRE_32Rnd_762x51_Mag",32],[],""],[],["TKE_UCNPistol","","","",["TKE_UCNPistol_mag",15],[],""],["TKE_CombatShirtWArmourUCMR_U_B",[["ACE_elasticBandage",20],["ACE_packingBandage",20],["kat_chestSeal",10],["ACE_tourniquet",8],["ACE_morphine",6],["ACE_epinephrine",10],["kat_TXA",10],["ACE_EarPlugs",1],["ACE_EHP",1],["kat_larynx",3]]],["TKE_UCMCArmour4_1Camo",[["OPTRE_32Rnd_762x51_Mag",8,32],["kat_IV_16",8],["ACE_plasmaIV_500",4],["kat_aatKit",4],["kat_IO_FAST",3],["ACE_splint",4],["TKE_SMOKE_mag",2,1],["ACE_Chemlight_IR",2,1],["SmokeShellRed",1,1],["Chemlight_green",1,1],["Chemlight_red",1,1]]],["TKE_RadioPackUCN",[["kat_accuvac",1],["kat_X_AED",1],["kat_BVM",1],["kat_stethoscope",1],["ACE_surgicalKit",1],["kat_fentanyl",3],["kat_ketamine",3],["kat_amiodarone",3],["ACE_adenosine",4],["kat_naloxone",4],["kat_EACA",5],["kat_Pulseoximeter",2],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_EntrenchingTool",1],["ACE_Kestrel4500",1],["ACE_MapTools",1],["acex_intelitems_notepad",1,1],["ACE_CableTie",2],["tsp_sling",1]]],"TKE_UCMCHelmM","TKE_UCNFaceWear1Camo1",[],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","KAT_STS","OPTRE_NVG_MVI_UL_HUL"]],
  ["TKE_UCMRHelmCamo","TKE_UCMRHelmCamoTeeth","TKE_UCMRHelmCamoV2","TKE_UCMRHelmCamoTeethV2","TKE_UCMRHelmOpenCamo","TKE_UCMRHelmOpenCamoTeeth","TKE_UCMCHelmM","OPTRE_M6D_Scope_Black","TKE_ThermScope","OPTRE_M393_Scope","OPTRE_M12_Optic_Red","TKE_CombatShirtWArmourUCMR_U_B","TKE_CombatUniCamo_U_B","TKE_CombatUniRolledV1Camo_U_B","TKE_CombatUniRolledV2Camo_U_B","TKE_VoidSuitCamo_U_B","TKE_UCMCArmour4_1Camo","TKE_UCMCArmour4_2Camo","TKE_UCMCArmour6_3Camo"]] call _reg;

["UCNMC_BulldogSignals", "Radio Operator", "UCNMC",
  [["OPTRE_MA32B","OPTRE_MA5Suppressor","OPTRE_M6C_Laser","OPTRE_M6D_Scope_Black",["OPTRE_32Rnd_762x51_Mag",32],[],""],[],["TKE_UCNPistol","","","",["TKE_UCNPistol_mag",15],[],""],["TKE_CombatShirtWArmourUCMR_U_B",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["kat_TXA",2],["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_painkillers",1,10]]],["TKE_UCMCArmour4_1Camo",[["OPTRE_32Rnd_762x51_Mag",8,32],["TKE_UCNPistol_mag",2,15],["TKE_FRAG_mag",1,1],["TKE_SMOKE_mag",2,1],["ACE_Chemlight_IR",4,1],["SmokeShellRed",1,1],["Chemlight_green",1,1],["Chemlight_red",1,1]]],["TKE_RadioPackUCN",[["kat_IV_16",2],["ACE_splint",2],["ACE_MapTools",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_CableTie",6],["acex_intelitems_notepad",1,1],["ACE_EntrenchingTool",1],["ACE_Kestrel4500",1],["tsp_sling",1]]],"TKE_UCMCHelmClosedV2","TKE_UCNFaceWear1Camo1",["ACE_Vector","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","KAT_STS","OPTRE_NVG_MVI_UL_HUL"]],
  ["TKE_UCMRHelmCamo","TKE_UCMRHelmCamoTeeth","TKE_UCMRHelmCamoV2","TKE_UCMRHelmCamoTeethV2","TKE_UCMRHelmOpenCamo","TKE_UCMRHelmOpenCamoTeeth","TKE_UCMCHelmClosedV2","OPTRE_M6D_Scope_Black","TKE_ThermScope","OPTRE_M393_Scope","OPTRE_M12_Optic_Red","TKE_CombatShirtWArmourUCMR_U_B","TKE_CombatUniCamo_U_B","TKE_CombatUniRolledV1Camo_U_B","TKE_CombatUniRolledV2Camo_U_B","TKE_VoidSuitCamo_U_B","TKE_UCMCArmour4_1Camo","TKE_UCMCArmour4_2Camo","TKE_UCMCArmour6_3Camo"]] call _reg;

["UCNMC_LanceLead", "Squad Leader", "UCNMC",
  [["OPTRE_MA32B","OPTRE_MA5Suppressor","OPTRE_M6C_Laser","OPTRE_M6D_Scope_Black",["OPTRE_32Rnd_762x51_Mag",32],[],""],[],["TKE_UCNPistol","","","",["TKE_UCNPistol_mag",15],[],""],["TKE_CombatShirtWArmourUCMR_U_B",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["kat_TXA",2],["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_painkillers",1,10]]],["TKE_UCMCArmour6_3Camo",[["OPTRE_32Rnd_762x51_Mag",8,32],["TKE_UCNPistol_mag",2,15],["TKE_FRAG_mag",2,1],["TKE_SMOKE_mag",2,1],["ACE_Chemlight_IR",2,1],["SmokeShellRed",1,1],["Chemlight_green",1,1],["Chemlight_red",1,1]]],["TKE_RadioPackUCN",[["kat_IV_16",2],["ACE_splint",2],["ACE_MapTools",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_CableTie",4],["ACE_EntrenchingTool",1],["ACE_Kestrel4500",1],["acex_intelitems_notepad",1,1],["tsp_sling",1]]],"TKE_UCMRHelmCamo","TKE_UCNFaceWear1Camo1",["ACE_Vector","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","KAT_STS","OPTRE_NVG_MVI_UL_HUL"]],
  ["TKE_UCMRHelmOpen","TKE_UCMRHelmCamo","TKE_UCMRHelmCamoTeeth","TKE_UCMRHelmCamoV2","TKE_UCMRHelmCamoTeethV2","TKE_UCMRHelmOpenCamo","TKE_UCMRHelmOpenCamoTeeth","OPTRE_MA32B","TKE_UCNBPRifleV2_Optic","OPTRE_M41_SSR","OPTRE_MA37BGL","OPTRE_MA5K","TKE_UCNDMR","TKE_UCNDMR_Optic","TKE_UCNMMG_Optic","TKE_UCNRifle_Optic","OPTRE_M6D_Scope_Black","TKE_ThermScope","OPTRE_M393_Scope","OPTRE_M12_Optic_Red","TKE_10xSightV2","OPTRE_32Rnd_762x51_Mag","OPTRE_M41_Twin_AI","TKE_20rnd_969x51_magUCN","TKE_20rnd_969x51_magUCNAP","TKE_25rnd_762x51_mag","TKE_25rnd_762x51_magAP","TKE_30rnd_575x45_magTR","TKE_30rnd_575x45_magAP","TKE_150rnd_62x35_magUCN","TKE_150rnd_62x35_magUCNAP","TKE_100rnd_ucnmmg_mag","TKE_UCNPistol_mag","3Rnd_HE_Grenade_shell","TKE_CombatShirtWArmourUCMR_U_B","TKE_CombatUniCamo_U_B","TKE_CombatUniRolledV1Camo_U_B","TKE_CombatUniRolledV2Camo_U_B","TKE_VoidSuitCamo_U_B","TKE_UCMCArmour4_1Camo","TKE_UCMCArmour4_2Camo","TKE_UCMCArmour6_3Camo","OPTRE_M392_DMR","OPTRE_15Rnd_762x51_Mag"]] call _reg;

["UCNMC_FireteamLead", "Fireteam Leader", "UCNMC",
  [["OPTRE_MA32B","OPTRE_MA5Suppressor","OPTRE_M6C_Laser","OPTRE_M6D_Scope_Black",["OPTRE_32Rnd_762x51_Mag",32],[],""],[],["TKE_UCNPistol","","","",["TKE_UCNPistol_mag",15],[],""],["TKE_CombatShirtWArmourUCMR_U_B",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["kat_TXA",2],["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_painkillers",1,10]]],["TKE_UCMCArmour6_3Camo",[["OPTRE_32Rnd_762x51_Mag",8,32],["TKE_UCNPistol_mag",2,15],["TKE_FRAG_mag",2,1],["TKE_SMOKE_mag",2,1],["ACE_Chemlight_IR",2,1],["SmokeShellRed",1,1],["Chemlight_green",1,1],["Chemlight_red",1,1]]],["TKE_LightPackUCN",[["kat_IV_16",2],["ACE_splint",2],["ACE_MapTools",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_CableTie",4],["TKE_FRAG_mag",2,1],["ACE_EntrenchingTool",1],["ACE_Kestrel4500",1],["acex_intelitems_notepad",1,1],["tsp_sling",1]]],"TKE_UCMRHelmCamo","TKE_UCNFaceWear1Camo1",["ACE_Vector","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","KAT_STS","OPTRE_NVG_MVI_UL_HUL"]],
  ["TKE_UCMRHelmOpen","TKE_UCMRHelmCamo","TKE_UCMRHelmCamoTeeth","TKE_UCMRHelmCamoV2","TKE_UCMRHelmCamoTeethV2","TKE_UCMRHelmOpenCamo","TKE_UCMRHelmOpenCamoTeeth","TKE_RadioPackUCN","TKE_LightPackUCN","OPTRE_MA32B","TKE_UCNBPRifleV2_Optic","OPTRE_M41_SSR","OPTRE_MA37BGL","OPTRE_MA5K","TKE_UCNDMR","TKE_UCNDMR_Optic","TKE_UCNMMG_Optic","TKE_UCNRifle_Optic","OPTRE_M6D_Scope_Black","TKE_ThermScope","OPTRE_M393_Scope","OPTRE_M12_Optic_Red","TKE_10xSightV2","OPTRE_32Rnd_762x51_Mag","OPTRE_M41_Twin_AI","TKE_20rnd_969x51_magUCN","TKE_20rnd_969x51_magUCNAP","TKE_25rnd_762x51_mag","TKE_25rnd_762x51_magAP","TKE_30rnd_575x45_magTR","TKE_30rnd_575x45_magAP","TKE_150rnd_62x35_magUCN","TKE_150rnd_62x35_magUCNAP","TKE_100rnd_ucnmmg_mag","TKE_UCNPistol_mag","3Rnd_HE_Grenade_shell","TKE_CombatShirtWArmourUCMR_U_B","TKE_CombatUniCamo_U_B","TKE_CombatUniRolledV1Camo_U_B","TKE_CombatUniRolledV2Camo_U_B","TKE_VoidSuitCamo_U_B","TKE_UCMCArmour4_1Camo","TKE_UCMCArmour4_2Camo","TKE_UCMCArmour6_3Camo","OPTRE_M392_DMR","OPTRE_15Rnd_762x51_Mag"]] call _reg;

["UCNMC_Marksman", "Designated Marksman", "UCNMC",
  [["OPTRE_M392_DMR","OPTRE_MA5Suppressor","OPTRE_M6C_Laser","OPTRE_M393_Scope",["OPTRE_15Rnd_762x51_Mag",15],[],"bipod_02_F_blk"],[],["TKE_UCNPistol","","","",["TKE_UCNPistol_mag",12],[],""],["TKE_CombatShirtWArmourUCMR_U_B",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["kat_TXA",2],["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_painkillers",1,10]]],["TKE_UCMCArmour4_1Camo",[["TKE_FRAG_mag",1,1],["TKE_SMOKE_mag",2,1],["ACE_Chemlight_IR",2,1],["SmokeShellRed",1,1],["Chemlight_green",1,1],["Chemlight_red",1,1]]],["TKE_RuckSack",[["kat_IV_16",2],["ACE_splint",2],["ACE_RangeCard",1],["ACE_ATragMX",1],["ACE_Kestrel4500",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["OPTRE_15Rnd_762x51_Mag",6,15],["ACE_EntrenchingTool",1],["ACE_MapTools",1],["acex_intelitems_notepad",1,1],["ACE_CableTie",2],["tsp_sling",1]]],"TKE_BoonieHatScrimHSUCMR","TKE_UCNFaceWear1Camo1",["TKE_BinoUCN","","","",["Laserbatteries",1],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","KAT_STS","TKE_ReconNVG"]],
  ["TKE_UCMRHelmCamo","TKE_UCMRHelmCamoTeeth","TKE_UCMRHelmCamoV2","TKE_UCMRHelmCamoTeethV2","TKE_UCMRHelmOpenCamo","TKE_UCMRHelmOpenCamoTeeth","TKE_BoonieHatScrimUCMR","TKE_BoonieHatScrimHSUCMR","TKE_ReconNVG","OPTRE_NVG_MVI_UL_HUL","TKE_CombatShirtWArmourUCMR_U_B","TKE_CombatUniCamo_U_B","TKE_CombatUniRolledV1Camo_U_B","TKE_CombatUniRolledV2Camo_U_B","TKE_VoidSuitCamo_U_B","TKE_UCMCArmour4_1Camo","TKE_UCMCArmour4_2Camo","TKE_UCMCArmour6_3Camo","OPTRE_M392_DMR","OPTRE_15Rnd_762x51_Mag","OPTRE_Commando","Commando_20Rnd_65_Mag","OPTRE_M6D_Scope_Black","TKE_ThermScope","OPTRE_M393_Scope","OPTRE_M12_Optic_Red","TKE_10xSightV2"]] call _reg;

["UCNMC_Heavy", "Automatic Rifleman", "UCNMC",
  [["OPTRE_M739_SAW_Black_F","","OPTRE_M6C_Laser","OPTRE_M739_SAW_Smartlink",["OPTRE_M739_SAW_192rnd_Box",192],[],"bipod_01_F_blk"],[],["TKE_UCNPistol","","","",["TKE_UCNPistol_mag",12],[],""],["TKE_CombatShirtWArmourUCMR_U_B",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["kat_TXA",2],["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_painkillers",1,10]]],["TKE_UCMCArmour4_1Camo",[["OPTRE_M739_SAW_192rnd_Box",2,192],["SmokeShellRed",1,1],["Chemlight_green",1,1],["Chemlight_red",1,1]]],["TKE_RuckSackUCMR",[["kat_IV_16",2],["ACE_splint",2],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["OPTRE_M739_SAW_192rnd_Box",4,192],["TKE_UCNPistol_mag",2,12],["ACE_EntrenchingTool",1],["ACE_Kestrel4500",1],["ACE_MapTools",1],["acex_intelitems_notepad",1,1],["ACE_CableTie",2],["tsp_sling",1]]],"TKE_UCNPilotHelmRV","TKE_UCMCNvgFC",["TKE_BinoUCN","","","",["Laserbatteries",1],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","KAT_STS","OPTRE_NVG_MVI_UL_HUL"]],
  ["TKE_UCMRHelmCamo","TKE_UCMRHelmCamoTeeth","TKE_UCMRHelmCamoV2","TKE_UCMRHelmCamoTeethV2","TKE_UCMRHelmOpenCamo","TKE_UCMRHelmOpenCamoTeeth","TKE_UCNPilotHelmRV","OPTRE_M739_SAW_Black_F","TKE_UCNMMG_Optic","OPTRE_M6C_Laser","OPTRE_M739_SAW_Smartlink","TKE_ThermScope","OPTRE_M393_Scope","OPTRE_M12_Optic_Red","OPTRE_M739_SAW_192rnd_Box","TKE_100rnd_ucnmmg_mag","TKE_CombatShirtWArmourUCMR_U_B","TKE_CombatUniCamo_U_B","TKE_CombatUniRolledV1Camo_U_B","TKE_CombatUniRolledV2Camo_U_B","TKE_VoidSuitCamo_U_B","TKE_UCMCArmour4_1Camo","TKE_UCMCArmour4_2Camo","TKE_UCMCArmour6_3Camo"]] call _reg;

["UCNMC_HeavyAT", "Automatic Rifleman (AT)", "UCNMC",
  [["OPTRE_M739_SAW_Black_F","","OPTRE_M6C_Laser","OPTRE_M739_SAW_Smartlink",["OPTRE_M739_SAW_192rnd_Box",192],[],"bipod_01_F_blk"],["OPTRE_M41_SSR","","","",["OPTRE_M41_Twin_AI",2],[],""],["TKE_UCNPistol","","","",["TKE_UCNPistol_mag",12],[],""],["TKE_CombatShirtWArmourUCMR_U_B",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["kat_TXA",2],["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_painkillers",1,10]]],["TKE_UCMCArmour4_1Camo",[["OPTRE_M739_SAW_192rnd_Box",2,192],["SmokeShellRed",1,1],["Chemlight_green",1,1],["Chemlight_red",1,1]]],["TKE_BackPack1UCN",[["kat_IV_16",2],["ACE_splint",2],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["OPTRE_M739_SAW_192rnd_Box",4,192],["OPTRE_M41_Twin_AI",1,2],["TKE_UCNPistol_mag",2,12],["ACE_EntrenchingTool",1],["ACE_Kestrel4500",1],["ACE_MapTools",1],["acex_intelitems_notepad",1,1],["ACE_CableTie",2],["tsp_sling",1]]],"TKE_UCNPilotHelmRV","TKE_UCNFaceWear1GLCamo1",["TKE_BinoUCN","","","",["Laserbatteries",1],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","KAT_STS","OPTRE_NVG_MVI_UL_HUL"]],
  ["TKE_UCMRHelmCamo","TKE_UCMRHelmCamoTeeth","TKE_UCMRHelmCamoV2","TKE_UCMRHelmCamoTeethV2","TKE_UCMRHelmOpenCamo","TKE_UCMRHelmOpenCamoTeeth","TKE_UCNPilotHelmRV","OPTRE_M739_SAW_Black_F","TKE_UCNMMG_Optic","OPTRE_M41_SSR","OPTRE_M6C_Laser","OPTRE_M739_SAW_Smartlink","TKE_ThermScope","OPTRE_M393_Scope","OPTRE_M12_Optic_Red","OPTRE_M739_SAW_192rnd_Box","TKE_100rnd_ucnmmg_mag","TKE_CombatShirtWArmourUCMR_U_B","TKE_CombatUniCamo_U_B","TKE_CombatUniRolledV1Camo_U_B","TKE_CombatUniRolledV2Camo_U_B","TKE_VoidSuitCamo_U_B","TKE_UCMCArmour4_1Camo","TKE_UCMCArmour4_2Camo","TKE_UCMCArmour6_3Camo"]] call _reg;

["UCNMC_Corpsman", "Corpsman", "UCNMC",
  [["OPTRE_MA5K","OPTRE_MA5Suppressor","OPTRE_M6C_Laser","OPTRE_M6D_Scope_Black",["OPTRE_32Rnd_762x51_Mag",32],[],""],[],["TKE_UCNPistol","","","",["TKE_UCNPistol_mag",15],[],""],["TKE_CombatShirtWArmourUCMR_U_B",[["ACE_elasticBandage",20],["ACE_packingBandage",20],["kat_chestSeal",10],["ACE_tourniquet",8],["ACE_morphine",6],["ACE_epinephrine",10],["kat_TXA",10],["ACE_EarPlugs",1],["ACE_EHP",1],["kat_larynx",3]]],["TKE_UCMCArmour4_1Camo",[["OPTRE_32Rnd_762x51_Mag",8,32],["kat_IV_16",6],["ACE_plasmaIV_500",4],["kat_aatKit",4],["ACE_splint",4],["TKE_SMOKE_mag",2,1],["ACE_Chemlight_IR",2,1],["SmokeShellRed",1,1],["Chemlight_green",1,1],["Chemlight_red",1,1]]],["TKE_RadioPackUCN",[["kat_accuvac",1],["kat_X_AED",1],["kat_BVM",1],["kat_stethoscope",1],["ACE_surgicalKit",1],["kat_IO_FAST",3],["kat_fentanyl",3],["kat_ketamine",3],["kat_amiodarone",3],["ACE_adenosine",4],["kat_naloxone",4],["kat_EACA",5],["kat_Pulseoximeter",2],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_EntrenchingTool",1],["ACE_Kestrel4500",1],["ACE_MapTools",1],["acex_intelitems_notepad",1,1],["ACE_CableTie",2],["tsp_sling",1]]],"TKE_UCMCHelmM","TKE_UCNFaceWear1Camo1",[],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","KAT_STS","OPTRE_NVG_MVI_UL_HUL"]],
  ["TKE_UCMRHelmCamo","TKE_UCMRHelmCamoTeeth","TKE_UCMRHelmCamoV2","TKE_UCMRHelmCamoTeethV2","TKE_UCMRHelmOpenCamo","TKE_UCMRHelmOpenCamoTeeth","TKE_UCMCHelmM","OPTRE_M6D_Scope_Black","TKE_ThermScope","OPTRE_M393_Scope","OPTRE_M12_Optic_Red","TKE_CombatShirtWArmourUCMR_U_B","TKE_CombatUniCamo_U_B","TKE_CombatUniRolledV1Camo_U_B","TKE_CombatUniRolledV2Camo_U_B","TKE_VoidSuitCamo_U_B","TKE_UCMCArmour4_1Camo","TKE_UCMCArmour4_2Camo","TKE_UCMCArmour6_3Camo"]] call _reg;

["UCNMC_Sniper", "Scout Sniper", "UCNMC",
  [["OPTRE_SRS99C","OPTRE_SRS99D_Suppressor","OPTRE_BMR_Laser","TKE_10xSightV2",["OPTRE_4Rnd_145x114_HVAP_Mag",4],[],""],[],["OPTRE_M7_Folded","OPTRE_M7_silencer","OPTRE_M6C_Laser","TKE_ReflexSight",["OPTRE_60Rnd_5x23mm_Mag",60],[],""],["TKE_CombatShirtWArmourUCMR_U_B",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["kat_TXA",2],["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_painkillers",1,10]]],["TKE_UCMCArmour4_1Camo",[["OPTRE_4Rnd_145x114_HVAP_Mag",8,4],["OPTRE_60Rnd_5x23mm_Mag",2,60],["TKE_SMOKE_mag",2,1],["ACE_Chemlight_IR",2,1],["SmokeShellRed",1,1],["Chemlight_green",1,1],["Chemlight_red",1,1]]],["TKE_BackPack2UCN",[["kat_IV_16",2],["ACE_splint",2],["ACE_ATragMX",1],["ACE_Kestrel4500",1],["ACE_RangeCard",1],["ACE_MapTools",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["OPTRE_4Rnd_145x114_HVAP_Mag",6,4],["OPTRE_4Rnd_145x114_APFSDS_Mag",4,4],["ACE_EntrenchingTool",1],["acex_intelitems_notepad",1,1],["ACE_CableTie",2],["tsp_sling",1]]],"TKE_BoonieHatScrimHSUCMR","TKE_UCNFaceWear1Camo1",["ACE_Vector","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","KAT_STS","OPTRE_NVG_MVI_UL_HUL"]],
  ["TKE_UCMRHelmCamo","TKE_UCMRHelmCamoTeeth","TKE_UCMRHelmCamoV2","TKE_UCMRHelmCamoTeethV2","TKE_UCMRHelmOpenCamo","TKE_UCMRHelmOpenCamoTeeth","TKE_BoonieHatScrimUCMR","TKE_BoonieHatScrimHSUCMR","TKE_ReconNVG","OPTRE_NVG_MVI_UL_HUL","OPTRE_SRS99C","TKE_10xSightV2","TKE_ThermScope","OPTRE_M393_Scope","OPTRE_M12_Optic_Red","OPTRE_4Rnd_145x114_APFSDS_Mag","TKE_CombatShirtWArmourUCMR_U_B","TKE_CombatUniCamo_U_B","TKE_CombatUniRolledV1Camo_U_B","TKE_CombatUniRolledV2Camo_U_B","TKE_VoidSuitCamo_U_B","TKE_UCMCArmour4_1Camo","TKE_UCMCArmour4_2Camo","TKE_UCMCArmour6_3Camo"]] call _reg;

["UCNMC_Spotter", "Scout Sniper (Spotter)", "UCNMC",
  [["OPTRE_M392_DMR","OPTRE_MA5Suppressor","OPTRE_M6C_Laser","OPTRE_M393_Scope",["OPTRE_15Rnd_762x51_Mag",15],[],"bipod_02_F_blk"],[],["TKE_UCNPistol","","","",["TKE_UCNPistol_mag",12],[],""],["TKE_CombatShirtWArmourUCMR_U_B",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["kat_TXA",2],["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_painkillers",1,10]]],["TKE_UCMCArmour4_1Camo",[["TKE_FRAG_mag",1,1],["TKE_SMOKE_mag",2,1],["ACE_Chemlight_IR",2,1],["SmokeShellRed",1,1],["Chemlight_green",1,1],["Chemlight_red",1,1]]],["TKE_RuckSack",[["kat_IV_16",2],["ACE_splint",2],["ACE_RangeCard",1],["ACE_ATragMX",1],["ACE_Kestrel4500",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["OPTRE_15Rnd_762x51_Mag",6,15],["ACE_EntrenchingTool",1],["ACE_MapTools",1],["acex_intelitems_notepad",1,1],["ACE_CableTie",2],["tsp_sling",1]]],"TKE_BoonieHatScrimHSUCMR","TKE_UCNFaceWear1Camo1",["TKE_BinoUCN","","","",["Laserbatteries",1],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","KAT_STS","TKE_ReconNVG"]],
  ["TKE_UCMRHelmCamo","TKE_UCMRHelmCamoTeeth","TKE_UCMRHelmCamoV2","TKE_UCMRHelmCamoTeethV2","TKE_UCMRHelmOpenCamo","TKE_UCMRHelmOpenCamoTeeth","TKE_BoonieHatScrimUCMR","TKE_BoonieHatScrimHSUCMR","TKE_ReconNVG","OPTRE_NVG_MVI_UL_HUL","TKE_CombatShirtWArmourUCMR_U_B","TKE_CombatUniCamo_U_B","TKE_CombatUniRolledV1Camo_U_B","TKE_CombatUniRolledV2Camo_U_B","TKE_VoidSuitCamo_U_B","TKE_UCMCArmour4_1Camo","TKE_UCMCArmour4_2Camo","TKE_UCMCArmour6_3Camo","OPTRE_M392_DMR","OPTRE_15Rnd_762x51_Mag","OPTRE_Commando","Commando_20Rnd_65_Mag","OPTRE_M6D_Scope_Black","TKE_ThermScope","OPTRE_M393_Scope","OPTRE_M12_Optic_Red","TKE_10xSightV2"]] call _reg;

["UCNMC_MailmanChiefPilot", "Aircraft Commander", "UCNMC",
  [["OPTRE_MA5K","OPTRE_MA5Suppressor","OPTRE_M6C_Vis_Red_Laser","OPTRE_M6D_Scope_Black",["OPTRE_32Rnd_762x51_Mag",32],[],""],[],["TKE_UCNPistol","","","",["TKE_UCNPistol_mag",12],[],""],["TKE_CombatShirtWArmourUCMR_U_B",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["kat_TXA",2],["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_painkillers",1,10]]],["TKE_PilotVest",[]],["TKE_LightPackUCN",[["kat_IV_16",2],["ACE_splint",2],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["OPTRE_32Rnd_762x51_Mag",6,32],["TKE_UCNPistol_mag",2,12],["ACE_EntrenchingTool",1],["ACE_Kestrel4500",1],["ACE_MapTools",1],["acex_intelitems_notepad",1,1],["ACE_CableTie",2],["tsp_sling",1],["SmokeShellRed",1,1],["Chemlight_green",1,1],["Chemlight_red",1,1]]],"TKE_UCNPilotHelmRV","TKE_UCMCNvgFC",["TKE_BinoUCN","","","",["Laserbatteries",1],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","KAT_STS","OPTRE_NVG_MVI_UL_HUL"]],
  ["OPTRE_M6D_Scope_Black","TKE_ThermScope","OPTRE_M393_Scope","OPTRE_M12_Optic_Red","TKE_CombatShirtWArmourUCMR_U_B","TKE_CombatUniCamo_U_B","TKE_CombatUniRolledV1Camo_U_B","TKE_CombatUniRolledV2Camo_U_B","TKE_VoidSuitCamo_U_B"]] call _reg;

["UCNMC_MailmanPilot", "Co-Pilot", "UCNMC",
  [["OPTRE_MA5K","OPTRE_MA5Suppressor","OPTRE_M6C_Vis_Red_Laser","OPTRE_M6D_Scope_Black",["OPTRE_32Rnd_762x51_Mag",32],[],""],[],["TKE_UCNPistol","","","",["TKE_UCNPistol_mag",12],[],""],["TKE_CombatShirtWArmourUCMR_U_B",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["kat_TXA",2],["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_painkillers",1,10]]],["TKE_PilotVest",[]],["TKE_LightPackUCN",[["kat_IV_16",2],["ACE_splint",2],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["OPTRE_32Rnd_762x51_Mag",6,32],["TKE_UCNPistol_mag",2,12],["ACE_EntrenchingTool",1],["ACE_Kestrel4500",1],["ACE_MapTools",1],["acex_intelitems_notepad",1,1],["ACE_CableTie",2],["tsp_sling",1],["SmokeShellRed",1,1],["Chemlight_green",1,1],["Chemlight_red",1,1]]],"TKE_UCNPilotHelmRV","TKE_UCMCNvgFC",["TKE_BinoUCN","","","",["Laserbatteries",1],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","KAT_STS","OPTRE_NVG_MVI_UL_HUL"]],
  ["OPTRE_M6D_Scope_Black","TKE_ThermScope","OPTRE_M393_Scope","OPTRE_M12_Optic_Red","TKE_CombatShirtWArmourUCMR_U_B","TKE_CombatUniCamo_U_B","TKE_CombatUniRolledV1Camo_U_B","TKE_CombatUniRolledV2Camo_U_B","TKE_VoidSuitCamo_U_B"]] call _reg;

["UCNMC_MailmanGunner", "Crew Chief", "UCNMC",
  [["OPTRE_MA5K","OPTRE_MA5Suppressor","OPTRE_M6C_Vis_Red_Laser","OPTRE_M6D_Scope_Black",["OPTRE_32Rnd_762x51_Mag",32],[],""],[],["TKE_UCNPistol","","","",["TKE_UCNPistol_mag",12],[],""],["TKE_CombatShirtWArmourUCMR_U_B",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["kat_TXA",2],["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_painkillers",1,10]]],["TKE_PilotVest",[]],["TKE_LightPackUCN",[["kat_IV_16",2],["ACE_splint",2],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["OPTRE_32Rnd_762x51_Mag",6,32],["TKE_UCNPistol_mag",2,12],["ACE_EntrenchingTool",1],["ACE_Kestrel4500",1],["ACE_MapTools",1],["acex_intelitems_notepad",1,1],["ACE_CableTie",2],["tsp_sling",1],["SmokeShellRed",1,1],["Chemlight_green",1,1],["Chemlight_red",1,1]]],"TKE_UCNPilotHelmRV","TKE_UCMCNvgFC",["TKE_BinoUCN","","","",["Laserbatteries",1],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","KAT_STS","OPTRE_NVG_MVI_UL_HUL"]],
  ["OPTRE_M6D_Scope_Black","TKE_ThermScope","OPTRE_M393_Scope","OPTRE_M12_Optic_Red","TKE_CombatShirtWArmourUCMR_U_B","TKE_CombatUniCamo_U_B","TKE_CombatUniRolledV1Camo_U_B","TKE_CombatUniRolledV2Camo_U_B","TKE_VoidSuitCamo_U_B"]] call _reg;

["UCNMC_MailmanVehicleCdr", "Vehicle Commander", "UCNMC",
  [["OPTRE_MA5K","OPTRE_MA5Suppressor","OPTRE_M6C_Vis_Red_Laser","OPTRE_M6D_Scope_Black",["OPTRE_32Rnd_762x51_Mag",32],[],""],[],["TKE_UCNPistol","","","",["TKE_UCNPistol_mag",12],[],""],["TKE_CombatShirtWArmourUCMR_U_B",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["kat_TXA",2],["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_painkillers",1,10]]],["TKE_PilotVest",[]],["TKE_LightPackUCN",[["kat_IV_16",2],["ACE_splint",2],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["OPTRE_32Rnd_762x51_Mag",6,32],["TKE_UCNPistol_mag",2,12],["ACE_EntrenchingTool",1],["ACE_Kestrel4500",1],["ACE_MapTools",1],["acex_intelitems_notepad",1,1],["ACE_CableTie",2],["tsp_sling",1],["SmokeShellRed",1,1],["Chemlight_green",1,1],["Chemlight_red",1,1]]],"TKE_UCNPilotHelmRV","TKE_UCMCNvgFC",["TKE_BinoUCN","","","",["Laserbatteries",1],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","KAT_STS","OPTRE_NVG_MVI_UL_HUL"]],
  ["OPTRE_M6D_Scope_Black","TKE_ThermScope","OPTRE_M393_Scope","OPTRE_M12_Optic_Red","TKE_CombatShirtWArmourUCMR_U_B","TKE_CombatUniCamo_U_B","TKE_CombatUniRolledV1Camo_U_B","TKE_CombatUniRolledV2Camo_U_B","TKE_VoidSuitCamo_U_B"]] call _reg;

["UCNMC_Sapper", "Combat Engineer", "UCNMC",
  [["OPTRE_M45ATAC","","","",["OPTRE_12Rnd_8Gauge_Pellets",12],[],""],[],["OPTRE_M7_Folded","OPTRE_M7_silencer","OPTRE_M6C_Laser","TKE_ReflexSight",["OPTRE_60Rnd_5x23mm_Mag",60],[],""],["TKE_CombatShirtWArmourUCMR_U_B",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["kat_TXA",2],["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_painkillers",1,10]]],["TKE_UCMCArmour4_2Camo",[["OPTRE_12Rnd_8Gauge_Pellets",4,12],["OPTRE_12Rnd_8Gauge_Slugs",3,12],["OPTRE_60Rnd_5x23mm_Mag",4,60],["ACE_DefusalKit",1],["SmokeShellRed",1,1],["Chemlight_green",1,1],["Chemlight_red",1,1]]],["TKE_ReconPackUCMR",[["kat_IV_16",2],["ACE_splint",2],["Toolkit",1],["ACE_EntrenchingTool",1],["M168_Remote_Mag",1,1],["C7_Remote_Mag",4,1],["ACE_Clacker",2],["OPTRE_12Rnd_8Gauge_HEDP",4,12],["OPTRE_60Rnd_5x23mm_Mag",4,60],["ACE_Kestrel4500",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["acex_intelitems_notepad",1,1],["ACE_CableTie",2],["tsp_sling",1]]],"TKE_UCMRHelmCamo","TKE_UCNFaceWear1Camo1",["ACE_Vector","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","KAT_STS","OPTRE_NVG_MVI_UL_HUL"]],
  ["TKE_UCMRHelmCamo","TKE_UCMRHelmCamoTeeth","TKE_UCMRHelmCamoV2","TKE_UCMRHelmCamoTeethV2","TKE_UCMRHelmOpenCamo","TKE_UCMRHelmOpenCamoTeeth","TKE_CombatShirtWArmourUCMR_U_B","TKE_CombatUniCamo_U_B","TKE_CombatUniRolledV1Camo_U_B","TKE_CombatUniRolledV2Camo_U_B","TKE_VoidSuitCamo_U_B","TKE_UCMCArmour4_1Camo","TKE_UCMCArmour4_2Camo","TKE_UCMCArmour6_3Camo"]] call _reg;
