private _timeout = time + 60;
waitUntil { !isNil "Wbk_AddKit" || time > _timeout };
if (isNil "Wbk_AddKit") exitWith {};
clearWeaponCargoGlobal _this;
clearMagazineCargoGlobal _this;
clearItemCargoGlobal _this;
clearBackpackCargoGlobal _this;

[
_this,
"Troop Sergeant",
[["ZXX_MCC_KS3_FDE_SLK_NAS3","MCC_MCQ1_Shroud_556_TAN","MCC_AR_NGAL_M600V_Tail_BLK_IRL","MCC_EXPS3_FDE",["MCC_PMAG_556_556_30_MK262_NAS3",30],[],"MCC_BCM_VFG_FDE"],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300T","MPP_ACRO_BLK",["MPP_17rnd_9MM_147JHP_G17",17],[],""],["Bell_G3_G_KP_P",[["kat_IV_16",6],["ACE_adenosine",2],["kat_amiodarone",1],["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_chestSeal",8],["kat_EACA",2],["ACE_epinephrine",6],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",8],["kat_TXA",2],["kat_Carbonate",1,10],["kat_Painkiller",2,4],["ACE_painkillers",2,10]]],["Bell_JPC",[["tsp_sling",1],["ACE_CableTie",5],["ItemAndroidMisc",1],["ACE_M26_Clacker",1],["MCC_PMAG_556_556_30_MK262_NAS3",5,30],["MCC_D60_556_60_MK262_NAS3",1,60],["rhs_mag_mk84",3,1],["rhs_mag_m67",2,1],["UK3CB_BAF_SmokeShell",2,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",4,1],["ACE_Chemlight_HiGreen",2,1],["MPP_17rnd_9MM_147JHP_G17",2,17],["UK3CB_BAF_SmokeShellPurple",2,1],["UK3CB_BAF_SmokeShellGreen",2,1]]],["ZXX_Slingshot_JPC_TFAR",[["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["42cdo_vs17_item",1],["GX_UAVBattery",1],["ItemcTabMisc",1],["ACE_ChalkRed",1],["tsp_lockpick",1],["ACE_plasmaIV_500",5],["ACE_surgicalKit",1],["acex_intelitems_notepad",1,1],["tsp_breach_block_mag",1,1],["GX_DEPLOYABLE_MAGAZINE_BLACKHORNET_UAV",1,100],["rhsusf_m112_mag",1,1]]],"Jones_SF_C_BDOWN_BP_P_VL","Zulu_MFrame_A_M_CB_BLK_SHD",["ACE_Vector","","","",[],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","KAT_Cavmin","GPNVG_GLD_HIGH_SF"]],     
["Bell_G3_G_KP_P","Z_G3_MC_KP_PCU_RG_G_H","Grimes_Rugby_KP_NP","Z_J_BLK_FL_CRGHD_T_G","UKSFOW","UK3CB_BAF_G_Balaclava_Win","Zulu_Boogie_M2_MC","Zulu_Gatorz_M2_MC_BLK_PPL","Zulu_MFrame_A_M2_MC_BLK_PPL","MCC_BCM_VFG_FDE","MCC_MLOK_AFG_FDE","ZXX_MCC_KS1_FDE_SLK_NAS3","ZXX_MCC_KS3_FDE_SLK_NAS3","MCC_EXPS3_FDE","MCC_EXPS3_FDE_Down","MCC_MicroT2","MCC_MicroT2_Down","MCC_Vortex_Elanor_Acro_TAN","MCC_MCQ1_556_TAN","MCC_MCQ1_Shroud_556_TAN"],    
"true",    
{}    
] spawn Wbk_AddKit;  
 
[    
_this,    
"Team Lead",    
[["ZXX_MCC_KS3_FDE_SLK_NAS3","MCC_MCQ1_Shroud_556_TAN","MCC_AR_NGAL_M600V_Tail_BLK_IRL","MCC_EXPS3_FDE",["MCC_PMAG_556_556_30_MK262_NAS3",30],[],"MCC_BCM_VFG_FDE"],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300T","MPP_ACRO_BLK",["MPP_17rnd_9MM_147JHP_G17",17],[],""],["Bell_G3_G_KP_P",[["kat_IV_16",6],["ACE_adenosine",2],["kat_amiodarone",1],["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_chestSeal",8],["kat_EACA",2],["ACE_epinephrine",6],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",8],["kat_TXA",2],["kat_Carbonate",1,10],["kat_Painkiller",2,4],["ACE_painkillers",2,10]]],["Jones_JPC_PMAG_BLK",[["tsp_sling",1],["ACE_CableTie",5],["ItemAndroidMisc",1],["ACE_M26_Clacker",1],["MCC_PMAG_556_556_30_MK262_NAS3",5,30],["MCC_D60_556_60_MK262_NAS3",1,60],["rhs_mag_mk84",6,1],["rhs_mag_m67",2,1],["UK3CB_BAF_SmokeShell",2,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",4,1],["ACE_Chemlight_HiGreen",2,1],["MPP_17rnd_9MM_147JHP_G17",2,17],["UK3CB_BAF_SmokeShellPurple",2,1],["UK3CB_BAF_SmokeShellGreen",2,1]]],["satcom_01_ZXX",[["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["42cdo_vs17_item",1],["GX_UAVBattery",1],["tsp_lockpick",1],["ACE_ChalkWhite",1],["ACE_plasmaIV_500",5],["ACE_surgicalKit",1],["acex_intelitems_notepad",1,1],["GX_DEPLOYABLE_MAGAZINE_BLACKHORNET_UAV",1,100],["tsp_breach_block_mag",1,1],["DemoCharge_Remote_Mag",1,1]]],"Jones_SF_C_BDOWN_BP_P_VL","Zulu_MFrame_A_M_CB_BLK_SHD",["ACE_VectorDay","","","",[],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","KAT_Cavmin","Kestrel_Veersamy_UW"]],     
["Bell_G3_G_KP_P","Z_G3_MC_KP_PCU_RG_G_H","Grimes_Rugby_KP_NP","Z_J_BLK_FL_CRGHD_T_G","UKSFOW","UK3CB_BAF_G_Balaclava_Win","Zulu_Boogie_M2_MC","Zulu_Gatorz_M2_MC_BLK_PPL","Zulu_MFrame_A_M2_MC_BLK_PPL","MCC_BCM_VFG_FDE","MCC_MLOK_AFG_FDE","ZXX_MCC_KS1_FDE_SLK_NAS3","ZXX_MCC_KS3_FDE_SLK_NAS3","MCC_EXPS3_FDE","MCC_EXPS3_FDE_Down","MCC_MicroT2","MCC_MicroT2_Down","MCC_Vortex_Elanor_Acro_TAN","MCC_MCQ1_556_TAN","MCC_MCQ1_Shroud_556_TAN"],    
"true",    
{}    
] spawn Wbk_AddKit;  
 
[    
_this,    
"Team Lead 2",    
[["ZXX_MCC_KS3_FDE_SLK_NAS3","MCC_MCQ1_Shroud_556_TAN","MCC_AR_NGAL_M600V_Tail_BLK_IRL","MCC_EXPS3_FDE",["MCC_PMAG_556_556_30_MK262_NAS3",30],[],"MCC_BCM_VFG_FDE"],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300T","MPP_ACRO_BLK",["MPP_17rnd_9MM_147JHP_G17",17],[],""],["Bell_G3_G_KP_P",[["kat_IV_16",6],["ACE_adenosine",2],["kat_amiodarone",1],["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_chestSeal",8],["kat_EACA",2],["ACE_epinephrine",6],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",8],["kat_TXA",2],["kat_Carbonate",1,10],["kat_Painkiller",2,4],["ACE_painkillers",2,10]]],["Drake_AVS",[["tsp_sling",1],["ACE_CableTie",5],["ItemAndroidMisc",1],["ACE_M26_Clacker",1],["MCC_PMAG_556_556_30_MK262_NAS3",5,30],["MCC_D60_556_60_MK262_NAS3",1,60],["rhs_mag_mk84",5,1],["rhs_mag_m67",2,1],["UK3CB_BAF_SmokeShell",2,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",4,1],["ACE_Chemlight_HiGreen",2,1],["MPP_17rnd_9MM_147JHP_G17",2,17],["UK3CB_BAF_SmokeShellPurple",2,1],["UK3CB_BAF_SmokeShellGreen",2,1]]],["ZXX_JPC_Panel2",[["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["42cdo_vs17_item",1],["GX_UAVBattery",1],["tsp_lockpick",1],["ItemcTabMisc",1],["ACE_ChalkYellow",1],["ACE_plasmaIV_500",4],["ACE_surgicalKit",1],["acex_intelitems_notepad",1,1],["GX_DEPLOYABLE_MAGAZINE_BLACKHORNET_UAV",1,100],["DemoCharge_Remote_Mag",1,1],["Laserbatteries",1,1]]],"Jones_SF_C_BDOWN_BP_P_VL","Zulu_MFrame_A_M_CB_BLK_SHD",["UK3CB_BAF_Soflam_Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","KAT_Cavmin","Kestrel_Veersamy_UW"]],     
["Bell_G3_G_KP_P","Z_G3_MC_KP_PCU_RG_G_H","Grimes_Rugby_KP_NP","Z_J_BLK_FL_CRGHD_T_G","UKSFOW","UK3CB_BAF_G_Balaclava_Win","Zulu_Boogie_M2_MC","Zulu_Gatorz_M2_MC_BLK_PPL","Zulu_MFrame_A_M2_MC_BLK_PPL","MCC_BCM_VFG_FDE","MCC_MLOK_AFG_FDE","ZXX_MCC_KS3_FDE_SLK_NAS3","MCC_EXPS3_FDE","MCC_EXPS3_FDE_Down","MCC_MicroT2","MCC_MicroT2_Down","MCC_Vortex_Elanor_Acro_TAN","MCC_MCQ1_556_TAN","MCC_MCQ1_Shroud_556_TAN"],    
"true",    
{}    
] spawn Wbk_AddKit;  
 
[    
_this,    
"Lead Scout",    
[["ZXX_MCC_KS3_FDE_SLK_NAS3","MCC_MCQ1_Shroud_556_TAN","MCC_AR_NGAL_M600V_Tail_BLK_IRL","MCC_EXPS3_FDE",["MCC_PMAG_556_556_30_MK262_NAS3",30],[],"MCC_BCM_VFG_FDE"],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300T","MPP_ACRO_BLK",["MPP_17rnd_9MM_147JHP_G17",17],[],""],["Bell_G3_G_KP_P",[["kat_IV_16",6],["ACE_adenosine",2],["kat_amiodarone",1],["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_chestSeal",8],["kat_EACA",2],["ACE_epinephrine",6],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",8],["kat_TXA",2],["ACE_plasmaIV_500",4],["ACE_surgicalKit",1],["kat_Carbonate",1,10],["kat_Painkiller",2,4],["ACE_painkillers",2,10]]],["Mullings_JPC_NP",[["tsp_sling",1],["ACE_CableTie",5],["ItemAndroidMisc",1],["ACE_Clacker",1],["tsp_lockpick",1],["MCC_PMAG_556_556_30_MK262_NAS3",6,30],["MCC_D60_556_60_MK262_NAS3",1,60],["rhs_mag_mk84",4,1],["rhs_mag_m67",2,1],["UK3CB_BAF_SmokeShell",2,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",4,1],["ACE_Chemlight_HiGreen",2,1],["MPP_17rnd_9MM_147JHP_G17",2,17],["UK3CB_BAF_SmokeShellPurple",1,1],["UK3CB_BAF_SmokeShellGreen",1,1]]],["ZXX_JPC_Panel6",[["42cdo_vs17_item",1],["GX_UAVBattery",2],["ACE_EHP",1],["ACE_EarPlugs",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["acex_intelitems_notepad",1,1],["tsp_breach_block_mag",1,1],["GX_DEPLOYABLE_MAGAZINE_BLACKHORNET_UAV",2,100]]],"Adams_SF_CT_P_VLI","Zulu_MFrame_A_M_CB_BLK_SHD",["ACE_MX2A","","","",[],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","KAT_Cavmin","Kestrel_Veersamy_UW"]],     
["Bell_G3_G_KP_P","Z_G3_MC_KP_PCU_RG_G_H","Grimes_Rugby_KP_NP","Z_J_BLK_FL_CRGHD_T_G","UKSFOW","UK3CB_BAF_G_Balaclava_Win","Zulu_Boogie_M2_MC","Zulu_Gatorz_M2_MC_BLK_PPL","Zulu_MFrame_A_M2_MC_BLK_PPL","MCC_BCM_VFG_FDE","MCC_MLOK_AFG_FDE","ZXX_MCC_KS1_FDE_SLK_NAS3","ZXX_MCC_KS3_FDE_SLK_NAS3","MCC_EXPS3_FDE","MCC_EXPS3_FDE_Down","MCC_MicroT2","MCC_MicroT2_Down","MCC_Vortex_Elanor_Acro_TAN","MCC_MCQ1_556_TAN","MCC_MCQ1_Shroud_556_TAN"],    
"true",    
{}    
] spawn Wbk_AddKit;  
 
[    
_this,    
"Point Man",    
[["ZXX_MCC_KS3_FDE_SLK_NAS3","MCC_MCQ1_Shroud_556_TAN","MCC_AR_NGAL_M600V_Tail_BLK_IRL","MCC_EXPS3_FDE",["MCC_PMAG_556_556_30_MK262_NAS3",30],[],"MCC_BCM_VFG_FDE"],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300T","MPP_ACRO_BLK",["MPP_17rnd_9MM_147JHP_G17",17],[],""],["Bell_G3_G_KP_P",[["kat_IV_16",6],["ACE_adenosine",2],["kat_amiodarone",1],["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_chestSeal",8],["kat_EACA",2],["ACE_epinephrine",6],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",8],["kat_TXA",2],["kat_Carbonate",1,10],["kat_Painkiller",2,4],["ACE_painkillers",2,10]]],["Veersamy_AVS",[["tsp_sling",1],["ACE_CableTie",5],["ItemAndroidMisc",1],["ACE_M26_Clacker",1],["tsp_breach_shock",1],["tsp_lockpick",1],["ACE_DefusalKit",1],["MCC_PMAG_556_556_30_MK262_NAS3",6,30],["MCC_D60_556_60_MK262_NAS3",1,60],["rhs_mag_mk84",6,1],["rhs_mag_m67",2,1],["UK3CB_BAF_SmokeShell",2,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",4,1],["ACE_Chemlight_HiGreen",2,1],["MPP_17rnd_9MM_147JHP_G17",2,17],["UK3CB_BAF_SmokeShellPurple",1,1],["UK3CB_BAF_SmokeShellGreen",1,1]]],["ZXX_AVS_Panel7_MC2_B_NH",[["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["42cdo_vs17_item",1],["ACE_wirecutter",1],["GX_UAVBattery",1],["ACE_plasmaIV_500",4],["ACE_surgicalKit",1],["acex_intelitems_notepad",1,1],["tsp_breach_block_mag",3,1],["tsp_breach_stick_mag",2,1],["tsp_breach_linear_auto_mag",4,1],["GX_DEPLOYABLE_MAGAZINE_BLACKHORNET_UAV",1,100]]],"Adams_SF_CT_P_VLI","Zulu_MFrame_A_M_CB_BLK_SHD",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","KAT_Cavmin","GPNVG_GLD_HIGH_SF"]],     
["Bell_G3_G_KP_P","Z_G3_MC_KP_PCU_RG_G_H","Grimes_Rugby_KP_NP","Z_J_BLK_FL_CRGHD_T_G","UKSFOW","UK3CB_BAF_G_Balaclava_Win","Zulu_Boogie_M2_MC","Zulu_Gatorz_M2_MC_BLK_PPL","Zulu_MFrame_A_M2_MC_BLK_PPL","MCC_BCM_VFG_FDE","MCC_MLOK_AFG_FDE","ZXX_MCC_KS3_FDE_SLK_NAS3","MCC_EXPS3_FDE","MCC_EXPS3_FDE_Down","MCC_MicroT2","MCC_MicroT2_Down","MCC_Vortex_Elanor_Acro_TAN","MCC_MCQ1_556_TAN","MCC_MCQ1_Shroud_556_TAN"],    
"true",    
{}    
] spawn Wbk_AddKit;  
 
[    
_this,    
"Medic",    
[["ZXX_MCC_KS3_FDE_SLK_VFG_NAS3","MCC_MCQ1_Shroud_556_TAN","MCC_AR_NGAL_M600V_Tail_BLK_IRL","MCC_EXPS3_FDE",["MCC_PMAG_556_556_30_MK262_NAS3",30],[],"MCC_BCM_VFG_FDE"],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300T","MPP_ACRO_BLK",["MPP_17rnd_9MM_147JHP_G17",17],[],""],["Adams_G3_G_KP_P",[["kat_IV_16",8],["ACE_adenosine",10],["kat_amiodarone",3],["ACE_elasticBandage",15],["ACE_packingBandage",15],["kat_chestSeal",10],["kat_EACA",5],["ACE_epinephrine",10],["kat_IO_FAST",3],["kat_fentanyl",2],["kat_ketamine",2],["kat_larynx",6],["ACE_morphine",6],["kat_naloxone",6],["kat_Pulseoximeter",2],["ACE_tourniquet",8],["kat_TXA",10],["kat_Carbonate",1,10],["ACE_painkillers",2,10]]],["Galahad_AVS_L_D",[["tsp_sling",1],["ACE_CableTie",5],["ItemAndroidMisc",1],["ACE_Clacker",1],["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["MCC_PMAG_556_556_30_MK262_NAS3",4,30],["MCC_D60_556_60_MK262_NAS3",1,60],["rhs_mag_mk84",3,1],["rhs_mag_m67",2,1],["UK3CB_BAF_SmokeShell",2,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",4,1],["ACE_Chemlight_HiGreen",2,1],["MPP_17rnd_9MM_147JHP_G17",2,17],["UK3CB_BAF_SmokeShellPurple",1,1],["UK3CB_BAF_SmokeShellGreen",1,1],["tsp_breach_block_mag",1,1],["UK3CB_BAF_SmokeShellBlue",2,1],["acex_intelitems_notepad",1,1]]],["ZXX_AVS_Panel4NB",[["kat_aatKit",8],["kat_accuvac",1],["kat_X_AED",1],["kat_BVM",1],["ACE_plasmaIV",3],["ACE_plasmaIV_500",4],["kat_stethoscope",1],["ACE_surgicalKit",1],["42cdo_vs17_item",2]]],"Adams_SF_CT_P_VLI","Zulu_MFrame_A_M_CB_BLK_SHD",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","KAT_Cavmin","GPNVG_GLD_HIGH_SF"]],     
["Adams_G3_G_KP_P","Z_G3_MC_KP_PCU_RG_G_H","Grimes_Rugby_KP_NP","Z_J_BLK_FL_CRGHD_T_G","UKSFOW","UK3CB_BAF_G_Balaclava_Win","Zulu_Boogie_M2_MC","Zulu_Gatorz_M2_MC_BLK_PPL","Zulu_MFrame_A_M2_MC_BLK_PPL","MCC_BCM_VFG_FDE","MCC_MLOK_AFG_FDE","ZXX_MCC_KS3_FDE_SLK_NAS3","MCC_EXPS3_FDE","MCC_EXPS3_FDE_Down","MCC_MicroT2","MCC_MicroT2_Down","MCC_Vortex_Elanor_Acro_TAN","MCC_MCQ1_556_TAN","MCC_MCQ1_Shroud_556_TAN"],    
"true",    
{}    
] spawn Wbk_AddKit;  
 
[    
_this,    
"Signaller",    
[["ZXX_MCC_KS3_FDE_SLK_NAS3","MCC_MCQ1_Shroud_556_TAN","MCC_AR_NGAL_M600V_Tail_BLK_IRL","MCC_EXPS3_FDE",["MCC_PMAG_556_556_30_MK262_NAS3",30],[],"MCC_BCM_VFG_FDE"],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300T","MPP_ACRO_BLK",["MPP_17rnd_9MM_147JHP_G17",17],[],""],["Bell_G3_G_KP_P",[["kat_IV_16",6],["ACE_adenosine",2],["kat_amiodarone",1],["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_chestSeal",8],["kat_EACA",2],["ACE_epinephrine",6],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",8],["kat_TXA",2],["ACE_plasmaIV_500",4],["ACE_surgicalKit",1],["kat_Carbonate",1,10],["kat_Painkiller",2,4],["ACE_painkillers",2,10]]],["Jones_JPC_SLICK_PMAG_BLK",[["tsp_sling",1],["ACE_CableTie",5],["ItemAndroidMisc",1],["ACE_Clacker",1],["tsp_lockpick",1],["MCC_PMAG_556_556_30_MK262_NAS3",4,30],["MCC_D60_556_60_MK262_NAS3",1,60],["rhs_mag_mk84",3,1],["rhs_mag_m67",2,1],["UK3CB_BAF_SmokeShell",2,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",4,1],["ACE_Chemlight_HiGreen",2,1],["MPP_17rnd_9MM_147JHP_G17",2,17],["UK3CB_BAF_SmokeShellPurple",1,1],["UK3CB_BAF_SmokeShellGreen",1,1],["ACE_HandFlare_Green",2,1],["ACE_HandFlare_White",1,1],["tsp_breach_block_mag",1,1]]],["ZXX_Slingshot_AVS_TFAR",[["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["42cdo_vs17_item",1],["ItemcTabMisc",1],["GX_UAVBattery",2],["acex_intelitems_notepad",1,1],["Laserbatteries",2,1],["GX_DEPLOYABLE_MAGAZINE_RQ11B_UAV",1,100]]],"Adams_SF_CT_P_VLI","Zulu_MFrame_A_M_CB_BLK_SHD",["UK3CB_BAF_Soflam_Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","KAT_Cavmin","Kestrel_Veersamy_UW"]],     
["Bell_G3_G_KP_P","Z_G3_MC_KP_PCU_RG_G_H","Grimes_Rugby_KP_NP","Z_J_BLK_FL_CRGHD_T_G","UKSFOW","UK3CB_BAF_G_Balaclava_Win","Zulu_Boogie_M2_MC","Zulu_Gatorz_M2_MC_BLK_PPL","Zulu_MFrame_A_M2_MC_BLK_PPL","MCC_BCM_VFG_FDE","MCC_MLOK_AFG_FDE","ZXX_MCC_KS1_FDE_SLK_NAS3","ZXX_MCC_KS3_FDE_SLK_NAS3","MCC_EXPS3_FDE","MCC_EXPS3_FDE_Down","MCC_MicroT2","MCC_MicroT2_Down","MCC_Vortex_Elanor_Acro_TAN","MCC_MCQ1_556_TAN","MCC_MCQ1_Shroud_556_TAN"],    
"true",    
{}    
] spawn Wbk_AddKit;  
 
[    
_this,    
"Marksman",    
[["MCC_LMT_MARSL_SPECWAR_6ARC_DE_SLK","MCC_HuxWrx_Flow_762TI","MCC_AR_NGAL_M600V_Tail_BLK_IRL","MCC_Mark5_10_BLK",["MCC_ICM_6ARC_20RD_ATIP",20],[],"MSS_Atlas_BT10"],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300T","MPP_ACRO_BLK",["MPP_17rnd_9MM_147JHP_G17",17],[],""],["Bell_G3_G_KP_P",[["kat_IV_16",6],["ACE_adenosine",2],["kat_amiodarone",1],["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_chestSeal",8],["kat_EACA",2],["ACE_epinephrine",6],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",8],["kat_TXA",2],["kat_Carbonate",1,10],["kat_Painkiller",2,4],["ACE_painkillers",2,10]]],["Friday_JPC",[["tsp_sling",1],["ACE_CableTie",5],["ItemAndroidMisc",1],["ACE_Clacker",1],["tsp_lockpick",1],["rhs_mag_mk84",3,1],["rhs_mag_m67",2,1],["UK3CB_BAF_SmokeShell",4,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",4,1],["ACE_Chemlight_HiGreen",2,1],["MPP_17rnd_9MM_147JHP_G17",2,17],["UK3CB_BAF_SmokeShellPurple",1,1],["UK3CB_BAF_SmokeShellGreen",1,1],["MCC_ICM_6ARC_20RD_ATIP",4,20],["MCC_ICM_6ARC_20RD_ADVAP",2,20]]],["ZXX_JPC_Panel6",[["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["42cdo_vs17_item",1],["ACE_ATragMX",1],["ACE_RangeCard",1],["ACE_plasmaIV_500",4],["ACE_surgicalKit",1],["acex_intelitems_notepad",1,1],["tsp_breach_block_mag",1,1]]],"Adams_SF_CT_P_VLI","Zulu_MFrame_A_M_CB_BLK_SHD",["ACE_Vector","","","",[],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","KAT_Cavmin","Kestrel_Veersamy_UW"]],     
["Bell_G3_G_KP_P","Z_G3_MC_KP_PCU_RG_G_H","Grimes_Rugby_KP_NP","Z_J_BLK_FL_CRGHD_T_G","UKSFOW","UK3CB_BAF_G_Balaclava_Win","Zulu_Boogie_M2_MC","Zulu_Gatorz_M2_MC_BLK_PPL","Zulu_MFrame_A_M2_MC_BLK_PPL"],    
"true",    
{}    
] spawn Wbk_AddKit;  
 
[    
_this,    
"Specialist",    
[["rhs_weap_m249_pip_S","MCC_HuxWrx_Flow_556K","MCC_PEQ15_BLK_IRL","MCC_EXPS3_BLK_Down",["rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",200],[],"rhsusf_acc_saw_lw_bipod"],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300T","MPP_ACRO_BLK",["MPP_17rnd_9MM_147JHP_G17",17],[],""],["Bell_G3_G_KP_P",[["kat_IV_16",6],["ACE_adenosine",2],["kat_amiodarone",1],["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_chestSeal",8],["kat_EACA",2],["ACE_epinephrine",6],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",8],["kat_TXA",2],["kat_Carbonate",1,10],["kat_Painkiller",2,4],["ACE_painkillers",2,10]]],["Veersamy_AVS",[["tsp_sling",1],["ACE_CableTie",5],["ItemAndroidMisc",1],["ACE_Clacker",1],["tsp_lockpick",1],["rhs_mag_mk84",3,1],["rhs_mag_m67",2,1],["UK3CB_BAF_SmokeShell",2,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",4,1],["ACE_Chemlight_HiGreen",2,1],["MPP_17rnd_9MM_147JHP_G17",2,17],["UK3CB_BAF_SmokeShellPurple",1,1],["UK3CB_BAF_SmokeShellGreen",1,1],["rhsusf_100Rnd_556x45_M855_mixed_soft_pouch_coyote",1,100],["rhsusf_100Rnd_556x45_M995_soft_pouch_coyote",1,100],["rhsusf_200Rnd_556x45_soft_pouch_coyote",1,200]]],["ZXX_AVS_Panel2",[["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["42cdo_vs17_item",1],["ACE_Tripod",1],["ACE_plasmaIV_500",4],["ACE_surgicalKit",1],["acex_intelitems_notepad",1,1]]],"Adams_SF_CT_P_VLI","Zulu_MFrame_A_M_CB_BLK_SHD",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","KAT_Cavmin","Kestrel_Veersamy_UW"]],     
["Bell_G3_G_KP_P","Z_G3_MC_KP_PCU_RG_G_H","Grimes_Rugby_KP_NP","Z_J_BLK_FL_CRGHD_T_G","UKSFOW","UK3CB_BAF_G_Balaclava_Win","Zulu_Boogie_M2_MC","Zulu_Gatorz_M2_MC_BLK_PPL","Zulu_MFrame_A_M2_MC_BLK_PPL"],    
"true",    
{}    
] spawn Wbk_AddKit; 
 
[    
_this,    
"Support Gunner",    
[["P_UKSF_L7A2","","","UK3CB_BAF_TA648_308",["rhsusf_100Rnd_762x51_m80a1epr",100],[],""],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300T","MPP_ACRO_BLK",["MPP_17rnd_9MM_147JHP_G17",17],[],""],["U_B_FullGhillie_sard",[["kat_IV_16",6],["ACE_adenosine",2],["kat_amiodarone",1],["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_chestSeal",8],["kat_EACA",2],["ACE_epinephrine",6],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_tourniquet",8],["kat_TXA",2],["kat_Carbonate",1,10],["kat_Painkiller",2,4],["ACE_painkillers",2,10]]],["PFM_NA_L",[["ACE_IR_Strobe_Item",1],["ItemAndroidMisc",1],["MPP_bti_blk",1],["MPP_17rnd_9MM_147JHP_G17",2,17],["UK3CB_BAF_SmokeShell",1,1],["UK3CB_BAF_SmokeShellGreen",1,1],["ACE_Chemlight_HiGreen",1,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_IR",2,1],["rhs_mag_mk84",1,1],["rhs_mag_m67",1,1],["rhsusf_100Rnd_762x51_m80a1epr",5,100]]],["asip_b_01_mc",[["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["42cdo_vs17_item",1],["ACE_Tripod",1],["ACE_plasmaIV_500",4],["ACE_surgicalKit",1],["UK3CB_BAF_MaxiKite",1],["acex_intelitems_notepad",1,1],["ACE_SpareBarrel",1,1]]],"Bump_MC_SWIR_NCW_AMPD_NVL","Zulu_Boogie_M_RG",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","KAT_Cavmin","Kestrel_GLD_SF_UW_C"]],     
["U_B_FullGhillie_ard","U_B_FullGhillie_lsh","U_B_FullGhillie_sard","U_B_T_FullGhillie_tna_F""U_AlpGhillie","DPM_FullGhillie","U_SnowGhillie","U_TaigaGhillie","U_GarbageGhillie3","UK3CB_BAF_G_Balaclava_Win","Zulu_Boogie_M_RG","Z_G3_RG_KP_PCU_RG_G_H_NB","zxx_molot_lapa_mc_v1_face","zxx_molot_lapa_mct_v1_face","zxx_molot_lapa_mcal_v1_face","zxx_molot_lapa_sapsan_v1_face"],    
"true",    
{}    
] spawn Wbk_AddKit;  
 
[    
_this,    
"Sniper",    
[["MSS_AXSR_338NM_SAGE","MSS_MFMD_SDX_BLK","","MSS_SB_PMII_525_BLK_GM_NO_LRF_NO",["MSS_10rnd_338NM_300ATIP_AXSR",10],[],"MSS_Atlas_BT72"],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300T","MPP_ACRO_BLK",["MPP_17rnd_9MM_147JHP_G17",17],[],""],["U_B_FullGhillie_sard",[["kat_IV_16",6],["ACE_adenosine",2],["kat_amiodarone",1],["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_chestSeal",8],["kat_EACA",2],["ACE_epinephrine",6],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_tourniquet",8],["kat_TXA",2],["kat_Carbonate",1,10],["kat_Painkiller",2,4],["ACE_painkillers",2,10]]],["PFM_NA_L",[["ACE_IR_Strobe_Item",1],["ACE_Kestrel4500",1],["ACE_RangeCard",1],["ItemAndroidMisc",1],["ACE_ATragMX",1],["MPP_bti_blk",1],["ACE_CableTie",5],["MPP_17rnd_9MM_147JHP_G17",2,17],["UK3CB_BAF_SmokeShell",1,1],["UK3CB_BAF_SmokeShellGreen",1,1],["ACE_Chemlight_HiGreen",1,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_IR",2,1],["rhs_mag_mk84",1,1],["rhs_mag_m67",1,1],["MSS_10rnd_338NM_300ATIP_AXSR",3,10],["MSS_10rnd_338NM_M1162_AXSR",2,10]]],["asip_b_01_mc",[["42cdo_vs17_item",1],["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_MapTools",1],["ACE_PlottingBoard",1],["ACE_Tripod",1],["ACE_splint",3],["ACE_surgicalKit",1],["ACE_plasmaIV_500",4],["acex_intelitems_notepad",1,1]]],"Bump_MC_SWIR_NCW_AMPD_NVL","Zulu_Boogie_M_RG",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","KAT_Cavmin","Kestrel_GLD_SF_UW_C"]],     
["U_B_FullGhillie_ard","U_B_FullGhillie_lsh","U_B_FullGhillie_sard","U_B_T_FullGhillie_tna_F","MSS_SB_PMII_525_BLK_GM_NO_LRF_NO","MSS_SB_PMII_525_BLK_GM_NO_LRF_NV","MSS_MFMD_BLK","MSS_MFMD_SD_BLK","MSS_MFMD_SDX_BLK","U_AlpGhillie","DPM_FullGhillie","U_SnowGhillie","U_TaigaGhillie","U_GarbageGhillie3","MSS_AML338_BLK","MSS_AML338_BLK_C","UK3CB_BAF_G_Balaclava_Win","Zulu_Boogie_M_RG","Z_G3_RG_KP_PCU_RG_G_H_NB","zxx_molot_lapa_mc_v1_face","zxx_molot_lapa_mct_v1_face","zxx_molot_lapa_mcal_v1_face","zxx_molot_lapa_sapsan_v1_face"],    
"true",    
{}    
] spawn Wbk_AddKit;  
 
[    
_this,    
"Spotter",    
[["MSS_SR25_65CM_14_B5_FDE","MSS_KAC_PRSQDC_FDE","","MSS_Mark5_18_BLK_GM_NO_LRF_NO",["MSS_20rnd_AR10_MP_65CM_M1200_FDE",20],[],"MSS_Atlas_BT65"],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300T","MPP_ACRO_BLK",["MPP_17rnd_9MM_147JHP_G17",17],[],""],["U_B_FullGhillie_sard",[["kat_IV_16",6],["ACE_adenosine",2],["kat_amiodarone",1],["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_chestSeal",8],["kat_EACA",2],["ACE_epinephrine",6],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_tourniquet",8],["kat_TXA",2],["kat_Carbonate",1,10],["kat_Painkiller",2,4],["ACE_painkillers",2,10]]],["PFM_NA_L",[["ACE_IR_Strobe_Item",1],["ItemAndroidMisc",1],["MPP_bti_blk",1],["ACE_CableTie",5],["MPP_17rnd_9MM_147JHP_G17",2,17],["UK3CB_BAF_SmokeShell",1,1],["UK3CB_BAF_SmokeShellGreen",1,1],["ACE_Chemlight_HiGreen",1,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_IR",2,1],["rhs_mag_mk84",1,1],["rhs_mag_m67",1,1],["MSS_20rnd_AR10_MP_65CM_M1200_FDE",3,20],["MSS_20rnd_AR10_MP_65CM_147ELDM_FDE",3,20]]],["asip_b_01_mc",[["42cdo_vs17_item",1],["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_MapTools",1],["ACE_PlottingBoard",1],["ACE_SpottingScope",1],["ACE_plasmaIV_500",4],["ACE_splint",3],["ACE_surgicalKit",1],["ACE_RangeCard",1],["ACE_Kestrel4500",1],["ACE_ATragMX",1],["acex_intelitems_notepad",1,1]]],"Bump_MC_SWIR_NCW_AMPD_NVL","Zulu_Boogie_M_RG",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","KAT_Cavmin","Kestrel_GLD_SF_UW_C"]],     
["U_B_FullGhillie_ard","U_B_FullGhillie_lsh","U_B_FullGhillie_sard","U_B_T_FullGhillie_tna_F","MSS_Mark5_18_BLK_GM_NO_LRF_NO","MSS_Mark5_18_BLK_GM_NO_LRF_NV","MSS_Mark5_18_BLK_GM_NO_LRF_TI","U_AlpGhillie","DPM_FullGhillie","U_SnowGhillie","U_TaigaGhillie","U_GarbageGhillie3","Zulu_Boogie_M_RG","Z_G3_RG_KP_PCU_RG_G_H_NB","zxx_molot_lapa_mc_v1_face","zxx_molot_lapa_mct_v1_face","zxx_molot_lapa_mcal_v1_face","zxx_molot_lapa_sapsan_v1_face"],    
"true",    
{}    
] spawn Wbk_AddKit;  
 
[    
_this,    
"Drone Carrier",    
[["ZXX_MCC_KS3_FDE_SLK_NAS3","MCC_MCQ1_Shroud_556_TAN","MCC_AR_NGAL_M600V_Tail_BLK_IRL","MCC_Vortex_Elanor_Acro_TAN",["MCC_PMAG_556_556_30_MK262_NAS3",30],[],"MCC_BCM_VFG_FDE"],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300T","MPP_ACRO_BLK",["MPP_17rnd_9MM_147JHP_G17",17],[],""],["Z_G3_RG_KP_PCU_RG_G_H",[["kat_IV_16",6],["ACE_adenosine",2],["kat_amiodarone",1],["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_chestSeal",8],["kat_EACA",2],["ACE_epinephrine",6],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",8],["kat_TXA",2],["ACE_plasmaIV_500",4],["ACE_surgicalKit",1],["kat_Carbonate",1,10],["kat_Painkiller",2,4],["ACE_painkillers",2,10]]],["TRF_SPIRITUS_A",[["tsp_sling",1],["ACE_CableTie",5],["ItemAndroidMisc",1],["NightCap_Gld_UW",1],["MCC_PMAG_556_556_30_MK262_NAS3",5,30],["rhs_mag_mk84",2,1],["rhs_mag_m67",1,1],["UK3CB_BAF_SmokeShell",2,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",4,1],["ACE_Chemlight_HiGreen",2,1],["MPP_17rnd_9MM_147JHP_G17",2,17],["UK3CB_BAF_SmokeShellGreen",1,1]]],["TRF_ZIPON_LR",[["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["42cdo_vs17_item",1],["GX_UAVBattery",2],["acex_intelitems_notepad",1,1],["GX_DEPLOYABLE_MAGAZINE_BLACKHORNET_UAV",2,100],["GX_DEPLOYABLE_MAGAZINE_RQ11B_UAV",1,100]]],"UKAF_BOONIE","Zulu_Boogie_M_RG",["ACE_Vector","","","",[],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","KAT_Cavmin",""]],     
["ZXX_MCC_KS1_FDE_SLK_NAS3","ZXX_MCC_KS3_FDE_SLK_NAS3","MCC_MCQ1_556_TAN","MCC_MCQ1_Shroud_556_TAN","MCC_MLOK_AFG_FDE","MCC_BCM_VFG_FDE","UKSFOW","Z_G3_RG_KP_PCU_RG_G_H","MCC_EXPS3_UnityX_FDE_Down","MCC_MicroT2_Down","MCC_Vortex_Elanor_Acro_TAN","Zulu_Boogie_M2_CB","UK3CB_BAF_G_Balaclava_Win","Zulu_Boogie_M_RG","Zulu_Gatorz_M_RG_BLK_PPL","Zulu_MFrame_A_M_RG_BLK_PPL","zxx_molot_lapa_mc_v1_face","zxx_molot_lapa_mct_v1_face","zxx_molot_lapa_mcal_v1_face","zxx_molot_lapa_sapsan_v1_face"],    
"true",    
{}    
] spawn Wbk_AddKit;   
 
[    
_this,    
"JSFAW Pilot",    
[["ZXX_MCC_KS3_FDE_SLK_NAS3","MCC_MCQ1_556_TAN","MCC_NGAL_AR_Top_IRL","MCC_EXPS3_FDE",["MCC_PMAG_556_556_30_MK262_NAS3",30],[],""],[],["MPP_G19_BLK_9","","MPP_X300T","",["MPP_15rnd_9MM_147FMJ_G19",15],[],""],["Z_G3_MC_KP_PCU_BLK_G_H",[["kat_IV_16",4],["ACE_adenosine",2],["kat_amiodarone",1],["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_chestSeal",6],["kat_EACA",2],["ACE_epinephrine",5],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_tourniquet",6],["kat_TXA",2],["ACE_plasmaIV_500",1],["kat_Carbonate",1,10],["kat_Painkiller",1,4],["ACE_painkillers",2,10]]],["Friday_JPC_NB",[["ACE_IR_Strobe_Item",1],["ItemAndroidMisc",1],["ACE_CableTie",1],["ACE_Clacker",1],["42cdo_vs17_item",1],["MPP_15rnd_9MM_147FMJ_G19",2,15],["MCC_PMAG_556_556_30_MK262_NAS3",3,30],["UK3CB_BAF_SmokeShell",1,1],["DemoCharge_Remote_Mag",1,1]]],["satcom_01",[["ACE_EHP",1],["ACE_EarPlugs",1],["ACE_splint",3],["ACE_surgicalKit",1],["ACE_plasmaIV_500",3]]],"Bump_MC_HS6_NCW_AMPD_NVL","Zulu_Boogie_MM_MC",[],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","KAT_STS","GPNVG_GLD_LOW_SF"]],     
["UKSFOW","UK3CB_BAF_G_Balaclava_Win","Zulu_Boogie_MM_MC","Zulu_MFrame_BLK_CLR","Z_G3_MC_KP_PCU_BLK_G_H","Zulu_NoFrame_A_M_MC_BLK_PPL"],    
"true",    
{}    
] spawn Wbk_AddKit; 