[    
this,    
"Section Lead",    
[["ZXX_L119A2_CQB_BLK_MCC","P_UKSF_Acc_FA556SA_Silencer_BLK","MCC_AR_PEQ15_M300C_Tail_BLK_IRL","MCC_EXPS3_FDE",["MCC_PMAG_556_556_30_MK262",30],[],""],[],["P_UKSF_Glock17_G4","","P_UKSF_Acc_SFX300U_Blk","MPP_RMR_BLK",["P_UKSF_Mag_17rnd_9MM_FMJ_G17",17],[],""],["Adams_G3_G_KP_NP",[["kat_IV_16",6],["ACE_adenosine",2],["kat_amiodarone",1],["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_chestSeal",8],["kat_EACA",2],["ACE_epinephrine",6],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",8],["kat_TXA",2],["kat_Carbonate",1,10],["kat_Painkiller",2,4],["ACE_painkillers",2,10]]],["Rickardsson_AVS",[["tsp_sling",1],["ACE_CableTie",4],["ItemAndroidMisc",1],["UK3CB_BAF_SmokeShell",2,1],["UK3CB_BAF_SmokeShellPurple",1,1],["UK3CB_BAF_SmokeShellGreen",1,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_HiRed",4,1],["rhs_mag_mk84",2,1],["P_UKSF_Mag_17rnd_9MM_FMJ_G17",2,17],["rhs_mag_m67",2,1],["UK3CB_BAF_SmokeShellOrange",2,1],["MCC_PMAG_556_556_30_MK262",6,30]]],["ZXX_117G_AVS_TFAR",[["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_IR_Strobe_Item",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ItemcTabMisc",1],["ACE_ChalkRed",1],["GX_UAVBattery",1],["ACE_plasmaIV_500",4],["ACE_surgicalKit",1],["acex_intelitems_notepad",1,1],["GX_DEPLOYABLE_MAGAZINE_BLACKHORNET_UAV",1,100]]],"Adams_SF_CT_P_VLO","Zulu_MFrame_BLK_CLR",["ACE_Vector","","","",[],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","KAT_STS","Kestrel_BLK_SF_UW_C"]],     
["Adams_G3_G_KP_NP","UKSFOW","UK3CB_BAF_G_Balaclava_Win","Zulu_MFrame_BLK_CLR","Zulu_MFrame_M_CB_BLK_CLR","Grimes_Rugby_NG_KP_NP","ZXX_L119A2_CQB_BLK_MCC","ZXX_L119A2_CQB_CAMO_MCC","P_UKSF_Acc_FA556SA_Silencer_BLK","P_UKSF_Acc_FA556SA_Silencer_FDE","MCC_EXPS3_FDE","MCC_EXPS3_FDE_Down","MCC_MicroT2","MCC_MicroT2_Down","rhsusf_acc_ACOG_RMR","rhsusf_acc_ACOG_d","rhsusf_acc_su230_mrds"],    
"true",    
{}    
] spawn Wbk_AddKit;  
 
[    
this,    
"Point Man",    
[["ZXX_L119A2_CQB_BLK_MCC","P_UKSF_Acc_FA556SA_Silencer_BLK","MCC_AR_PEQ15_M300C_Tail_BLK_IRL","MCC_EXPS3_FDE",["MCC_PMAG_556_556_30_MK262",30],[],""],[],["P_UKSF_Glock17_G4","","P_UKSF_Acc_SFX300U_Blk","MPP_RMR_BLK",["P_UKSF_Mag_17rnd_9MM_FMJ_G17",17],[],""],["Adams_G3_G_KP_NP",[["kat_IV_16",6],["ACE_adenosine",2],["kat_amiodarone",1],["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_chestSeal",8],["kat_EACA",2],["ACE_epinephrine",6],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",8],["kat_TXA",2],["kat_Carbonate",1,10],["kat_Painkiller",2,4],["ACE_painkillers",2,10]]],["Mullings_JPC",[["tsp_sling",1],["ACE_CableTie",4],["ItemAndroidMisc",1],["UK3CB_BAF_SmokeShell",2,1],["UK3CB_BAF_SmokeShellPurple",1,1],["UK3CB_BAF_SmokeShellGreen",1,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_HiRed",4,1],["P_UKSF_Mag_17rnd_9MM_FMJ_G17",2,17],["MCC_PMAG_556_556_30_MK262",6,30],["rhs_mag_m67",2,1],["rhs_mag_mk84",2,1]]],["ZXX_JPC_Panel7_CB_NB_NH",[["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["MineDetector",1],["ChemicalDetector_01_tan_F",1],["GX_UAVBattery",1],["ACE_plasmaIV_500",4],["ACE_surgicalKit",1],["acex_intelitems_notepad",1,1],["GX_DEPLOYABLE_MAGAZINE_BLACKHORNET_UAV",1,100]]],"Adams_SF_CT_P_VLO","Zulu_MFrame_BLK_CLR",["ACE_Yardage450","","","",[],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","KAT_STS","Kestrel_BLK_SF_UW_C"]],     
["Adams_G3_G_KP_NP","UKSFOW","UK3CB_BAF_G_Balaclava_Win","Zulu_MFrame_BLK_CLR","Zulu_MFrame_M_CB_BLK_CLR","Grimes_Rugby_NG_KP_NP","ZXX_L119A2_CQB_BLK_MCC","ZXX_L119A2_CQB_CAMO_MCC","P_UKSF_Acc_FA556SA_Silencer_BLK","P_UKSF_Acc_FA556SA_Silencer_FDE","MCC_EXPS3_FDE","MCC_EXPS3_FDE_Down","MCC_MicroT2","MCC_MicroT2_Down","rhsusf_acc_ACOG_RMR","rhsusf_acc_ACOG_d","rhsusf_acc_su230_mrds"],    
"true",    
{}    
] spawn Wbk_AddKit;  
 
[    
this,    
"Lead Breacher",    
[["ZXX_L119A2_CQB_BLK_MCC","P_UKSF_Acc_FA556SA_Silencer_BLK","MCC_AR_PEQ15_M300C_Tail_BLK_IRL","MCC_EXPS3_FDE",["MCC_PMAG_556_556_30_MK262",30],[],""],["tsp_meleeWeapon_halligan","","","",[],[],""],["P_UKSF_Glock17_G4","","P_UKSF_Acc_SFX300U_Blk","MPP_RMR_BLK",["P_UKSF_Mag_17rnd_9MM_FMJ_G17",17],[],""],["Adams_G3_G_KP_NP",[["kat_IV_16",6],["ACE_adenosine",2],["kat_amiodarone",1],["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_chestSeal",8],["kat_EACA",2],["ACE_epinephrine",6],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",8],["kat_TXA",2],["ACE_plasmaIV_500",4],["ACE_surgicalKit",1],["kat_Carbonate",1,10],["kat_Painkiller",2,4],["ACE_painkillers",2,10]]],["Galahad_AVS_A_P",[["tsp_sling",1],["ACE_CableTie",4],["ItemAndroidMisc",1],["ACE_ChalkGreen",1],["ACE_ChalkRed",1],["ACE_DefusalKit",1],["ACE_M26_Clacker",1],["tsp_lockpick",1],["tsp_breach_shock",1],["UK3CB_BAF_SmokeShell",2,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",6,1],["P_UKSF_Mag_17rnd_9MM_FMJ_G17",2,17],["MCC_PMAG_556_556_30_MK262",7,30],["rhs_mag_m67",2,1],["rhs_mag_an_m14_th3",2,1],["tsp_breach_block_mag",3,1],["acex_intelitems_notepad",1,1],["ACE_CTS9",2,1],["rhs_mag_mk84",6,1]]],["Jones_AVS_1000",[["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_wirecutter",1],["ACE_EarPlugs",1],["ACE_EHP",1],["tsp_breach_popper_auto_mag",6,1],["tsp_breach_stick_mag",2,1],["rhsusf_m112_mag",2,1],["ClaymoreDirectionalMine_Remote_Mag",1,1],["tsp_breach_silhouette_mag",1,1]]],"Adams_SF_CT_P_VLO","Zulu_StepIn_TAN_CLR_SF_M2_MC",[],["ItemMap","","TFAR_anprc152","ItemCompass","KAT_STS","Kestrel_BLK_SF_UW_C"]],     
["Adams_G3_G_KP_NP","UKSFOW","UK3CB_BAF_G_Balaclava_Win","Zulu_MFrame_BLK_CLR","Zulu_MFrame_M_CB_BLK_CLR","Grimes_Rugby_NG_KP_NP","ZXX_L119A2_CQB_BLK_MCC","ZXX_L119A2_CQB_CAMO_MCC","P_UKSF_Acc_FA556SA_Silencer_BLK","P_UKSF_Acc_FA556SA_Silencer_FDE","MCC_EXPS3_FDE","MCC_EXPS3_FDE_Down","MCC_MicroT2","MCC_MicroT2_Down","rhsusf_acc_ACOG_RMR","rhsusf_acc_ACOG_d","rhsusf_acc_su230_mrds","MCC_EXPS3_BLK","MCC_EXPS3_BLK_Down","MCC_AR_PEQ15_M300C_Tail_BLK_IRL","ZXX_L119A1_CQB_BLK_MCC","rhsusf_acc_grip2"],    
"true",    
{}    
] spawn Wbk_AddKit;  
 
[    
this,    
"Section Medic",    
[["ZXX_L119A2_CQB_BLK_MCC","P_UKSF_Acc_FA556SA_Silencer_BLK","MCC_AR_PEQ15_M300C_Tail_BLK_IRL","MCC_EXPS3_FDE",["MCC_PMAG_556_556_30_MK262",30],[],""],[],["P_UKSF_Glock17_G4","","P_UKSF_Acc_SFX300U_Blk","MPP_RMR_BLK",["P_UKSF_Mag_17rnd_9MM_FMJ_G17",17],[],""],["Adams_G3_G_KP_P",[["kat_IV_16",8],["ACE_adenosine",8],["kat_amiodarone",4],["ACE_elasticBandage",15],["ACE_packingBandage",15],["kat_BVM",1],["kat_chestSeal",10],["kat_EACA",8],["ACE_epinephrine",10],["kat_IO_FAST",4],["kat_fentanyl",2],["kat_ketamine",2],["kat_larynx",4],["ACE_morphine",8],["kat_naloxone",6],["kat_Pulseoximeter",2],["kat_TXA",10],["kat_Carbonate",1,10],["ACE_painkillers",2,10]]],["Galahad_AVS_L_D",[["tsp_sling",1],["ACE_CableTie",4],["ItemAndroidMisc",1],["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_Clacker",1],["UK3CB_BAF_SmokeShell",4,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_HiRed",4,1],["rhs_mag_mk84",2,1],["P_UKSF_Mag_17rnd_9MM_FMJ_G17",2,17],["MCC_PMAG_556_556_30_MK262",5,30],["rhs_mag_m67",1,1],["acex_intelitems_notepad",1,1],["UK3CB_BAF_SmokeShellBlue",2,1],["ACE_Chemlight_HiBlue",2,1]]],["Jones_MRASAP",[["ACE_surgicalKit",1],["kat_stethoscope",1],["kat_accuvac",1],["kat_aatKit",13],["ACE_plasmaIV",4],["ACE_plasmaIV_500",4],["ACE_splint",8],["ACE_tourniquet",8],["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["GX_UAVBattery",1],["kat_AED",1],["GX_DEPLOYABLE_MAGAZINE_BLACKHORNET_UAV",1,100],["rhsusf_m112_mag",1,1]]],"Adams_SF_CT_P_VLO","Zulu_MFrame_BLK_CLR",[],["ItemMap","","TFAR_anprc152","ItemCompass","KAT_STS","Kestrel_BLK_SF_UW_C"]],     
["Adams_G3_G_KP_NP","UKSFOW","UK3CB_BAF_G_Balaclava_Win","Zulu_MFrame_BLK_CLR","Zulu_MFrame_M_CB_BLK_CLR","Grimes_Rugby_NG_KP_NP","ZXX_L119A2_CQB_BLK_MCC","ZXX_L119A2_CQB_CAMO_MCC","P_UKSF_Acc_FA556SA_Silencer_BLK","P_UKSF_Acc_FA556SA_Silencer_FDE","MCC_EXPS3_FDE","MCC_EXPS3_FDE_Down","MCC_MicroT2","MCC_MicroT2_Down","rhsusf_acc_ACOG_RMR","rhsusf_acc_ACOG_d","rhsusf_acc_su230_mrds","MCC_EXPS3_BLK","MCC_EXPS3_BLK_Down","MCC_AR_PEQ15_M300C_Tail_BLK_IRL","ZXX_L119A1_CQB_BLK_MCC","rhsusf_acc_grip2"],    
"true",    
{}    
] spawn Wbk_AddKit;  
 
[    
this,    
"Section 2iC",    
[["ZXX_L119A2_CQB_BLK_MCC","P_UKSF_Acc_FA556SA_Silencer_BLK","MCC_AR_PEQ15_M300C_Tail_BLK_IRL","MCC_EXPS3_FDE",["MCC_PMAG_556_556_30_MK262",30],[],""],[],["P_UKSF_Glock17_G4","","P_UKSF_Acc_SFX300U_Blk","MPP_RMR_BLK",["P_UKSF_Mag_17rnd_9MM_FMJ_G17",17],[],""],["Adams_G3_G_KP_NP",[["kat_IV_16",6],["ACE_adenosine",2],["kat_amiodarone",1],["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_chestSeal",8],["kat_EACA",2],["ACE_epinephrine",6],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",8],["kat_TXA",2],["ACE_plasmaIV_500",4],["ACE_surgicalKit",1],["kat_Carbonate",1,10],["kat_Painkiller",2,4],["ACE_painkillers",2,10]]],["Rickardsson_AVS",[["tsp_sling",1],["ACE_CableTie",4],["ItemAndroidMisc",1],["ToolKit",1],["GX_UAVBattery",1],["UK3CB_BAF_SmokeShell",2,1],["UK3CB_BAF_SmokeShellPurple",1,1],["UK3CB_BAF_SmokeShellGreen",1,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_HiRed",4,1],["rhs_mag_mk84",2,1],["P_UKSF_Mag_17rnd_9MM_FMJ_G17",2,17],["rhs_mag_m67",2,1],["UK3CB_BAF_SmokeShellOrange",2,1],["ACE_Chemlight_HiBlue",2,1],["UK3CB_BAF_SmokeShellYellow",2,1],["MCC_PMAG_556_556_30_MK262",6,30],["GX_DEPLOYABLE_MAGAZINE_BLACKHORNET_UAV",1,100]]],["ZXX_117G_AVS_TFAR",[["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_IR_Strobe_Item",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ItemcTabMisc",1],["acex_intelitems_notepad",1,1],["UK3CB_BAF_762_100Rnd",3,100]]],"Adams_SF_CT_P_VLO","Zulu_MFrame_BLK_CLR",["ACE_Vector","","","",[],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","KAT_STS","Kestrel_BLK_SF_UW_C"]],     
["Adams_G3_G_KP_NP","UKSFOW","UK3CB_BAF_G_Balaclava_Win","Zulu_MFrame_BLK_CLR","Zulu_MFrame_M_CB_BLK_CLR","Grimes_Rugby_NG_KP_NP","ZXX_L119A2_CQB_BLK_MCC","ZXX_L119A2_CQB_CAMO_MCC","P_UKSF_Acc_FA556SA_Silencer_BLK","P_UKSF_Acc_FA556SA_Silencer_FDE","MCC_EXPS3_FDE","MCC_EXPS3_FDE_Down","MCC_MicroT2","MCC_MicroT2_Down","rhsusf_acc_ACOG_RMR","rhsusf_acc_ACOG_d","rhsusf_acc_su230_mrds"],    
"true",    
{}    
] spawn Wbk_AddKit;  
 
[    
this,    
"Section Gunner - L7A2",    
[["P_UKSF_L7A2","","","UK3CB_BAF_TA648_308",["UK3CB_BAF_762_100Rnd",100],[],""],[],["P_UKSF_Glock17_G4","","P_UKSF_Acc_SFX300U_Blk","MPP_RMR_BLK",["P_UKSF_Mag_17rnd_9MM_FMJ_G17",17],[],""],["Adams_G3_G_KP_NP",[["kat_IV_16",6],["ACE_adenosine",2],["kat_amiodarone",1],["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_chestSeal",8],["kat_EACA",2],["ACE_epinephrine",6],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",8],["kat_TXA",2],["kat_Carbonate",1,10],["kat_Painkiller",2,4],["ACE_painkillers",2,10]]],["Drake_AVS",[["tsp_sling",1],["ACE_CableTie",4],["ItemAndroidMisc",1],["UK3CB_BAF_SmokeShell",2,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_HiRed",4,1],["P_UKSF_Mag_17rnd_9MM_FMJ_G17",2,17],["rhs_mag_m67",1,1],["UK3CB_BAF_762_100Rnd",3,100]]],["ZXX_JPC_Panel7_CB_NB_NH",[["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_Tripod",1],["ACE_surgicalKit",1],["ACE_plasmaIV_500",4],["UK3CB_BAF_MaxiKite",1],["acex_intelitems_notepad",1,1],["ACE_SpareBarrel",1,1]]],"Adams_SF_CT_P_VLO","Zulu_MFrame_BLK_CLR",[],["ItemMap","","TFAR_anprc152","ItemCompass","KAT_STS","Kestrel_BLK_SF_UW_C"]],     
["Adams_G3_G_KP_NP","UKSFOW","UK3CB_BAF_G_Balaclava_Win","Zulu_MFrame_BLK_CLR","Zulu_MFrame_M_CB_BLK_CLR","Grimes_Rugby_NG_KP_NP"],    
"true",    
{}    
] spawn Wbk_AddKit;  
 
[    
this,    
"Section Gunner - L110A3",    
[["rhs_weap_m249_pip_S","MCC_RC2_556","MCC_PEQ15_BLK_IRL","MCC_EXPS3_BLK",["rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",200],[],"rhsusf_acc_saw_lw_bipod"],[],["P_UKSF_Glock17_G4","","P_UKSF_Acc_SFX300U_Blk","MPP_RMR_BLK",["P_UKSF_Mag_17rnd_9MM_FMJ_G17",17],[],""],["Adams_G3_G_KP_NP",[["kat_IV_16",6],["ACE_adenosine",2],["kat_amiodarone",1],["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_chestSeal",8],["kat_EACA",2],["ACE_epinephrine",6],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",8],["kat_TXA",2],["kat_Carbonate",1,10],["kat_Painkiller",2,4],["ACE_painkillers",2,10]]],["Drake_AVS",[["tsp_sling",1],["ACE_CableTie",4],["ItemAndroidMisc",1],["UK3CB_BAF_SmokeShell",2,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_HiRed",4,1],["P_UKSF_Mag_17rnd_9MM_FMJ_G17",2,17],["rhs_mag_m67",1,1],["rhsusf_100Rnd_556x45_M855_mixed_soft_pouch_coyote",2,100],["rhsusf_200Rnd_556x45_soft_pouch_coyote",1,200]]],["ZXX_JPC_Panel7_CB_NB_NH",[["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_surgicalKit",1],["ACE_plasmaIV_500",4],["acex_intelitems_notepad",1,1],["ACE_SpareBarrel",1,1]]],"Adams_SF_CT_P_VLO","Zulu_MFrame_BLK_CLR",[],["ItemMap","","TFAR_anprc152","ItemCompass","KAT_STS","Kestrel_BLK_SF_UW_C"]],     
["Adams_G3_G_KP_NP","UKSFOW","UK3CB_BAF_G_Balaclava_Win","Zulu_MFrame_BLK_CLR","Zulu_MFrame_M_CB_BLK_CLR","Grimes_Rugby_NG_KP_NP","MCC_EXPS3_BLK","MCC_EXPS3_BLK_Down"],    
"true",    
{}    
] spawn Wbk_AddKit;  
 
[    
this,    
"Sharpshooter",    
[["Louetta_HK417_3","MCC_SOCOM_Mini2_762","MCC_PEQ15_FDE_IRL","MCC_Mark5_10_BLK",["Louetta_20Rnd_762x51mm",20],[],"MSS_Harris_SBRMP"],[],["P_UKSF_Glock17_G4","","P_UKSF_Acc_SFX300U_Blk","MPP_RMR_BLK",["P_UKSF_Mag_17rnd_9MM_FMJ_G17",17],[],""],["Adams_G3_G_KP_NP",[["kat_IV_16",6],["ACE_adenosine",2],["kat_amiodarone",1],["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_chestSeal",8],["kat_EACA",2],["ACE_epinephrine",6],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",8],["kat_TXA",2],["kat_Carbonate",1,10],["kat_Painkiller",2,4],["ACE_painkillers",2,10]]],["Veersamy_AVS",[["tsp_sling",1],["ACE_CableTie",4],["ItemAndroidMisc",1],["UK3CB_BAF_SmokeShell",2,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_HiRed",4,1],["rhs_mag_mk84",1,1],["P_UKSF_Mag_17rnd_9MM_FMJ_G17",2,17],["rhs_mag_m67",1,1],["Louetta_20Rnd_762x51mm",6,20]]],["ZXX_AVS_Panel2",[["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_ATragMX",1],["ACE_Kestrel4500",1],["ACE_RangeCard",1],["ACE_Tripod",1],["ACE_plasmaIV_500",4],["ACE_surgicalKit",1],["acex_intelitems_notepad",1,1]]],"Adams_SF_CT_P_VLO","Zulu_MFrame_BLK_CLR",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","KAT_STS","Kestrel_BLK_SF_UW_C"]],     
["Adams_G3_G_KP_NP","UKSFOW","UK3CB_BAF_G_Balaclava_Win","Zulu_MFrame_BLK_CLR","Zulu_MFrame_M_CB_BLK_CLR","Grimes_Rugby_NG_KP_NP","MCC_Mark5_10_BLK","MSS_SB_PMII_525_BLK_GM_NO_LRF_NV"],    
"true",    
{}    
] spawn Wbk_AddKit;  
 
[    
this,    
"Rifleman (AT)",    
[["ZXX_L119A2_SFW_BLK_MCC","P_UKSF_Acc_FA556SA_Silencer_BLK","MCC_AR_PEQ15_M300C_Tail_BLK_IRL","MCC_EXPS3_FDE",["MCC_PMAG_556_556_30_MK262",30],[],""],["UK3CB_BAF_NLAW_Launcher","","","",[],[],""],["P_UKSF_Glock17_G4","","P_UKSF_Acc_SFX300U_Blk","MPP_RMR_BLK",["P_UKSF_Mag_17rnd_9MM_FMJ_G17",17],[],""],["Adams_G3_G_KP_NP",[["kat_IV_16",6],["ACE_adenosine",2],["kat_amiodarone",1],["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_chestSeal",8],["kat_EACA",2],["ACE_epinephrine",6],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",8],["kat_TXA",2],["kat_Carbonate",1,10],["kat_Painkiller",2,4],["ACE_painkillers",2,10]]],["Mullings_JPC",[["tsp_sling",1],["ACE_CableTie",4],["ItemAndroidMisc",1],["UK3CB_BAF_SmokeShell",2,1],["UK3CB_BAF_SmokeShellPurple",1,1],["UK3CB_BAF_SmokeShellGreen",1,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_HiRed",4,1],["P_UKSF_Mag_17rnd_9MM_FMJ_G17",2,17],["MCC_PMAG_556_556_30_MK262",6,30],["rhs_mag_m67",2,1],["rhs_mag_mk84",2,1]]],["ZXX_JPC_Panel7_CB_NB_NH",[["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_plasmaIV_500",4],["ACE_surgicalKit",1],["acex_intelitems_notepad",1,1],["UK3CB_BAF_762_100Rnd",1,100]]],"Adams_SF_CT_P_VLO","Zulu_MFrame_BLK_CLR",["ACE_Yardage450","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","KAT_STS","Kestrel_BLK_SF_UW_C"]],     
["Adams_G3_G_KP_NP","UKSFOW","UK3CB_BAF_G_Balaclava_Win","Zulu_MFrame_BLK_CLR","Zulu_MFrame_M_CB_BLK_CLR","Grimes_Rugby_NG_KP_NP","ZXX_L119A2_SFW_BLK_MCC","ZXX_L119A2_SFW_CAMO_MCC","P_UKSF_Acc_FA556SA_Silencer_BLK","P_UKSF_Acc_FA556SA_Silencer_FDE","MCC_EXPS3_FDE","MCC_EXPS3_FDE_Down","MCC_MicroT2","MCC_MicroT2_Down","rhsusf_acc_ACOG_RMR","rhsusf_acc_ACOG_d","rhsusf_acc_su230_mrds","MCC_EXPS3_BLK","MCC_EXPS3_BLK_Down","MCC_AR_PEQ15_M300C_Tail_BLK_IRL","ZXX_L119A1_CQB_BLK_MCC","rhsusf_acc_grip2"],    
"true",    
{}    
] spawn Wbk_AddKit;  
 
[    
this,    
"Platoon Sergeant",    
[["ZXX_L119A2_SFW_BLK_MCC","P_UKSF_Acc_FA556SA_Silencer_BLK","MCC_AR_PEQ15_M300C_Tail_BLK_IRL","MCC_EXPS3_FDE",["MCC_PMAG_556_556_30_MK262",30],[],""],[],["P_UKSF_Glock17_G4","","P_UKSF_Acc_SFX300U_Blk","MPP_RMR_BLK",["P_UKSF_Mag_17rnd_9MM_FMJ_G17",17],[],""],["Adams_G3_G_KP_NP",[["kat_IV_16",6],["ACE_adenosine",2],["kat_amiodarone",1],["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_chestSeal",8],["kat_EACA",2],["ACE_epinephrine",6],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",8],["kat_TXA",2],["kat_Carbonate",1,10],["kat_Painkiller",2,4],["ACE_painkillers",2,10]]],["marko_njpc_red2",[["tsp_sling",1],["ACE_CableTie",4],["ItemAndroidMisc",1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_HiRed",4,1],["ACE_Chemlight_IR",2,1],["P_UKSF_Mag_17rnd_9MM_FMJ_G17",2,17],["UK3CB_BAF_SmokeShellPurple",1,1],["UK3CB_BAF_SmokeShell",2,1],["UK3CB_BAF_SmokeShellGreen",1,1],["UK3CB_BAF_SmokeShellOrange",2,1],["rhs_mag_m67",2,1],["rhs_mag_mk84",2,1],["MCC_PMAG_556_556_30_MK262",5,30]]],["ZXX_Slingshot_AVS_TFAR",[["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_IR_Strobe_Item",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ItemcTabMisc",1],["ACE_ChalkRed",1],["GX_UAVBattery",1],["ACE_plasmaIV_500",4],["ACE_surgicalKit",1],["acex_intelitems_notepad",1,1],["GX_DEPLOYABLE_MAGAZINE_BLACKHORNET_UAV",1,100],["Laserbatteries",1,1]]],"Jones_SF_C_BDOWN_BP_P_VL","Zulu_MFrame_BLK_CLR",["UK3CB_BAF_Soflam_Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","KAT_STS","Kestrel_BLK_SF_UW_C"]],     
["Adams_G3_G_KP_NP","UKSFOW","UK3CB_BAF_G_Balaclava_Win","Zulu_MFrame_BLK_CLR","Zulu_MFrame_M_CB_BLK_CLR","Grimes_Rugby_NG_KP_NP","ZXX_L119A2_SFW_BLK_MCC","ZXX_L119A2_SFW_CAMO_MCC","P_UKSF_Acc_FA556SA_Silencer_BLK","P_UKSF_Acc_FA556SA_Silencer_FDE","MCC_EXPS3_FDE","MCC_EXPS3_FDE_Down","MCC_MicroT2","MCC_MicroT2_Down","rhsusf_acc_ACOG_RMR","rhsusf_acc_ACOG_d","rhsusf_acc_su230_mrds","MCC_EXPS3_BLK","MCC_EXPS3_BLK_Down","MCC_AR_PEQ15_M300C_Tail_BLK_IRL","ZXX_L119A1_CQB_BLK_MCC","rhsusf_acc_grip2"],    
"true",    
{}    
] spawn Wbk_AddKit;  
 
[    
this,    
"Sniper",    
[["MSS_MRAD_338LM_FDE_20","MSS_AML338_CYT_C","","MSS_Mark5_25_DIR_GM_NO_LRF_NO",["MSS_10rnd_338LM_Lap_250_MRAD",10],[],"MSS_Harris_SBRMP"],[],["P_UKSF_Glock17_G4","","P_UKSF_Acc_SFX300U_Blk","MPP_RMR_BLK",["P_UKSF_Mag_17rnd_9MM_FMJ_G17",17],[],""],["Adams_G3_G_KP_NP",[["kat_IV_16",6],["ACE_adenosine",2],["kat_amiodarone",1],["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_chestSeal",8],["kat_EACA",2],["ACE_epinephrine",6],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",8],["kat_TXA",2],["kat_Carbonate",1,10],["kat_Painkiller",2,4],["ACE_painkillers",2,10],["MSS_10rnd_338LM_Lap_250_MRAD",2,0]]],["PFM_NA_L",[["tsp_sling",1],["ACE_CableTie",4],["ItemAndroidMisc",1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_HiRed",4,1],["ACE_Chemlight_IR",2,1],["P_UKSF_Mag_17rnd_9MM_FMJ_G17",2,17],["UK3CB_BAF_SmokeShell",2,1],["rhs_mag_m67",1,1],["rhs_mag_mk84",1,1],["MSS_10rnd_338LM_Lap_250_MRAD",4,10],["MSS_10rnd_338LM_API526_MRAD",1,10]]],["ZXX_JPC_Panel2",[["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_ATragMX",1],["ACE_Kestrel4500",1],["ACE_RangeCard",1],["ACE_Tripod",1],["ACE_plasmaIV_500",4],["ACE_surgicalKit",1],["acex_intelitems_notepad",1,1]]],"Adams_SF_CT_P_VLO","zxx_molot_lapa_mc_v1_face",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","KAT_STS","Kestrel_BLK_SF_UW_C"]],     
["Adams_G3_G_KP_NP","UKSFOW","Grimes_Rugby_NG_KP_NP","MSS_Mark5_25_DIR_GM_NO_LRF_NO","MSS_Mark5_25_DIR_GM_NO_LRF_NV","zxx_molot_lapa_mc_v1_face","zxx_molot_lapa_mct_v1_face","zxx_molot_lapa_mcal_v1_face","zxx_molot_lapa_sapsan_v1_face"],    
"true",    
{}    
] spawn Wbk_AddKit;  
 
[    
this,    
"Spotter",    
[["Louetta_HK417_3","MCC_SOCOM_Mini2_762","MCC_PEQ15_FDE_IRL","MCC_Mark5_10_BLK",["Louetta_20Rnd_762x51mm",20],[],"MSS_Harris_SBRMP"],[],["P_UKSF_Glock17_G4","","P_UKSF_Acc_SFX300U_Blk","MPP_RMR_BLK",["P_UKSF_Mag_17rnd_9MM_FMJ_G17",17],[],""],["Adams_G3_G_KP_NP",[["kat_IV_16",6],["ACE_adenosine",2],["kat_amiodarone",1],["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_chestSeal",8],["kat_EACA",2],["ACE_epinephrine",6],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",8],["kat_TXA",2],["kat_Carbonate",1,10],["kat_Painkiller",2,4],["ACE_painkillers",2,10]]],["Veersamy_AVS",[["tsp_sling",1],["ACE_CableTie",4],["ItemAndroidMisc",1],["UK3CB_BAF_SmokeShell",2,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_HiRed",4,1],["rhs_mag_mk84",1,1],["P_UKSF_Mag_17rnd_9MM_FMJ_G17",2,17],["rhs_mag_m67",1,1],["Louetta_20Rnd_762x51mm",6,20]]],["ZXX_AVS_Panel2",[["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_ATragMX",1],["ACE_Kestrel4500",1],["ACE_RangeCard",1],["ACE_Tripod",1],["ACE_plasmaIV_500",4],["ACE_surgicalKit",1],["acex_intelitems_notepad",1,1]]],"Adams_SF_CT_P_VLO","zxx_molot_lapa_mc_v1_face",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","KAT_STS","Kestrel_BLK_SF_UW_C"]],     
["Adams_G3_G_KP_NP","UKSFOW","Grimes_Rugby_NG_KP_NP","zxx_molot_lapa_mc_v1_face","zxx_molot_lapa_mct_v1_face","zxx_molot_lapa_mcal_v1_face","zxx_molot_lapa_sapsan_v1_face","MCC_Mark5_10_BLK","MSS_SB_PMII_525_BLK_GM_NO_LRF_NO","MSS_SB_PMII_525_BLK_GM_NO_LRF_NV","MSS_SB_PMII_525_BLK_GM_NO_LRF_TI"],    
"true",    
{}    
] spawn Wbk_AddKit;  
 
[    
this,    
"Crewman",    
[[],[],["P_UKSF_Glock17_G4","","","",["P_UKSF_Mag_17rnd_9MM_FMJ_G17",19],[],""],["TRF_PCS_FS_NG_U",[["kat_IV_16",1],["ACE_adenosine",2],["ACE_elasticBandage",8],["ACE_packingBandage",8],["kat_chestSeal",2],["ACE_epinephrine",4],["ACE_morphine",2],["kat_naloxone",1],["ACE_splint",1],["kat_Painkiller",2,4]]],["TRF_STV_Crew",[["ACE_tourniquet",4],["ACE_CableTie",2],["Kestrel_BLK_SF_U_C",1],["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_plasmaIV_500",1],["ItemAndroidMisc",1],["UK3CB_BAF_SmokeShell",1,1],["UK3CB_BAF_SmokeShellRed",1,1],["acex_intelitems_notepad",1,1],["Chemlight_green",1,1],["Chemlight_red",1,1],["P_UKSF_Mag_17rnd_9MM_FMJ_G17",3,19]]],[],"TRF_BATLSKIN_REVISION","UK3CB_BAF_G_Tactical_Clear",[],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","KAT_STS",""]],     
["TRF_BATLSKIN_REVISION_IR","TRF_BATLSKIN_REVISION_NETTING_IR","TRF_BATLSKIN_REVISION_SCRIM_OAK","TRF_PCS_FS_NG_U","TRF_PCS_FS_G_U","TRF_PCS_HS_NG_U","TRF_PCS_HS_G_U","TRF_PCS_RS_NG_U","TRF_PCU_NG_U","TRF_PCU_G_U"],    
"true",    
{}    
] spawn Wbk_AddKit;  
 
[    
this,    
"Pilot",    
[[],[],["P_UKSF_Glock17_G4","","","",["P_UKSF_Mag_17rnd_9MM_FMJ_G17",17],[],""],["TRF_FLIGHTSUIT_18SQN",[["kat_IV_16",1],["ACE_adenosine",2],["ACE_elasticBandage",8],["ACE_packingBandage",8],["kat_chestSeal",2],["ACE_epinephrine",4],["ACE_morphine",2],["kat_naloxone",1],["ACE_splint",1],["kat_Painkiller",2,4]]],["TRF_STV_Pilot",[["ACE_IR_Strobe_Item",1],["ItemAndroidMisc",1],["P_UKSF_Mag_17rnd_9MM_FMJ_G17",3,17]]],["satcom_01",[]],"UK3CB_BAF_H_PilotHelmetHeli_A","UK3CB_BAF_G_Tactical_Clear",[],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","KAT_STS","Marko_BNVD_NC_UW"]],     
[],    
"true",    
{}    
] spawn Wbk_AddKit; 