// Hand-written for the 44th Detachment (The Kuiper Engagements / SciFi modpack).
// Faction: UCNMC - UCN Marine Corp. 16 kits, plain setUnitLoadout format.
//
// Gear notes:
//   Taken from the mod's own UCNMC_M_* unit configs rather than picked by eye,
//   so the detachment reads as UCN Marines: TKE_CombatUni* uniforms, UCMCArmour
//   plates, UCMC helmets, TKE_IntegratedNVGs.
//   NCOs carry the 7.62 UCNRifle, riflemen the 5.75 BPRifle - that is the mod's
//   own distinction, not an invention.
//   Two weapons inherit from vanilla base classes and take vanilla ammo:
//   TKE_UCNSniper (GM6_base_F -> 5Rnd_127x108) and TKE_ATRecoilless1
//   (launch_MRAWS_base_F -> MRAWS_HEAT_F).
//   Anyone the ORBAT puts on an LR net carries TFAR_rt1523g_black instead of a
//   pack; SR-only slots carry a pack. Line corpsmen are the exception (see the
//   swap list on their kit).

["UCNMC_BulldogCommander", "Detachment Commander", "UCNMC",
  [["TKE_UCNBPRifle_Optic","","","",["TKE_30rnd_575x45_magTR",30],[],""],[],["TKE_UCNPistol","","","",["TKE_UCNPistol_mag",15],[],""],["TKE_CombatUniNA_U_B",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["kat_TXA",2],["ACE_EarPlugs",1],["ACE_painkillers",1,10]]],["TKE_UCMCArmour4_2",[["TKE_30rnd_575x45_magTR",7,30],["TKE_UCNPistol_mag",2,15],["TKE_FRAG_mag",2,1],["TKE_SMOKE_mag",2,1],["ACE_Chemlight_IR",2,1]]],["TFAR_rt1523g_black",[["kat_IV_16",2],["ACE_splint",2],["ACE_surgicalKit",1],["ACE_MapTools",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_CableTie",4],["TKE_30rnd_575x45_magTR",4,30]]],"TKE_UCMRHelmOpen","TKE_CombatGlasses",["ACE_Vector","","","",[],[],""],["ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","ItemWatch","TKE_IntegratedNVGs"]],
  ["TKE_UCNRifle_Optic","TKE_UCMCHelm","TKE_UCMCArmour4_1","TKE_LightPackUCN","ItemMicroDAGR"]] call _reg;

["UCNMC_BulldogTwoIC", "2IC / Air and Fires", "UCNMC",
  [["TKE_UCNBPRifle_Optic","","","",["TKE_30rnd_575x45_magTR",30],[],""],[],["TKE_UCNPistol","","","",["TKE_UCNPistol_mag",15],[],""],["TKE_CombatUniNA_U_B",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["kat_TXA",2],["ACE_EarPlugs",1],["ACE_painkillers",1,10]]],["TKE_UCMCArmour4_2",[["TKE_30rnd_575x45_magTR",7,30],["TKE_UCNPistol_mag",2,15],["TKE_FRAG_mag",2,1],["TKE_SMOKE_mag",2,1],["ACE_Chemlight_IR",2,1]]],["TFAR_rt1523g_black",[["kat_IV_16",2],["ACE_splint",2],["ACE_surgicalKit",1],["ACE_MapTools",1],["ACE_RangeCard",1],["ACE_Kestrel4500",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["TKE_30rnd_575x45_magTR",4,30]]],"TKE_UCMCHelm","TKE_CombatGlasses",["ACE_Vector","","","",[],[],""],["ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","ItemWatch","TKE_IntegratedNVGs"]],
  ["TKE_UCNRifle_Optic","TKE_UCMRHelmOpen","TKE_UCMCArmour4_1","ACE_Yardage450","ItemMicroDAGR"]] call _reg;

["UCNMC_BulldogCorpsman", "Detachment Corpsman", "UCNMC",
  [["TKE_UCNBPRifle_Optic","","","",["TKE_30rnd_575x45_magTR",30],[],""],[],["TKE_UCNPistol","","","",["TKE_UCNPistol_mag",15],[],""],["TKE_CombatUniNARolled_U_B",[["ACE_elasticBandage",20],["ACE_packingBandage",20],["kat_chestSeal",10],["ACE_tourniquet",8],["ACE_morphine",6],["ACE_epinephrine",10],["kat_TXA",10],["ACE_EarPlugs",1],["kat_larynx",3]]],["TKE_UCMCArmour3_1",[["kat_IV_16",8],["ACE_plasmaIV_500",4],["kat_aatKit",4],["kat_IO_FAST",3],["ACE_splint",4],["TKE_30rnd_575x45_magTR",4,30],["TKE_SMOKE_mag",2,1],["ACE_Chemlight_IR",2,1]]],["TFAR_rt1523g_black",[["kat_accuvac",1],["kat_X_AED",1],["kat_BVM",1],["kat_stethoscope",1],["ACE_surgicalKit",1],["kat_fentanyl",3],["kat_ketamine",3],["kat_amiodarone",3],["ACE_adenosine",4],["kat_naloxone",4],["kat_EACA",5],["kat_Pulseoximeter",2],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1]]],"TKE_UCMCHelmM","",[],["ItemMap","ItemMicroDAGR","TFAR_anprc152","ItemCompass","ItemWatch","TKE_IntegratedNVGs"]],
  ["TKE_AlicePackUCNM_Med","TKE_UCMCHelm","TKE_UCMCArmour3_2","TKE_UCNRifle_Optic"]] call _reg;

["UCNMC_BulldogSignals", "Signals and Intel", "UCNMC",
  [["TKE_UCNBPRifle_Optic","","","",["TKE_30rnd_575x45_magTR",30],[],""],[],["TKE_UCNPistol","","","",["TKE_UCNPistol_mag",15],[],""],["TKE_CombatUniNA_U_B",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["kat_TXA",2],["ACE_EarPlugs",1],["ACE_painkillers",1,10]]],["TKE_UCMCArmour4_1",[["TKE_30rnd_575x45_magTR",7,30],["TKE_UCNPistol_mag",2,15],["TKE_FRAG_mag",1,1],["TKE_SMOKE_mag",2,1],["ACE_Chemlight_IR",4,1]]],["TFAR_rt1523g_black",[["kat_IV_16",2],["ACE_splint",2],["ACE_surgicalKit",1],["ACE_MapTools",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_CableTie",6],["acex_intelitems_notepad",1,1],["TKE_30rnd_575x45_magTR",4,30]]],"TKE_UCMCHelmClosedV2","",["ACE_Vector","","","",[],[],""],["ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","ItemWatch","TKE_IntegratedNVGs"]],
  ["TKE_RadioPackUCN","TKE_UCMCHelm","TKE_UCMCArmour4_2","ItemMicroDAGR","ItemAndroid"]] call _reg;

["UCNMC_LanceLead", "Lance Lead", "UCNMC",
  [["TKE_UCNRifle_Optic","","","",["TKE_25rnd_762x51_mag",25],[],""],[],["TKE_UCNPistol","","","",["TKE_UCNPistol_mag",15],[],""],["TKE_CombatUniRolledV1_U_B",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["kat_TXA",2],["ACE_EarPlugs",1],["ACE_painkillers",1,10]]],["TKE_UCMCArmour6_3",[["TKE_25rnd_762x51_mag",8,25],["TKE_UCNPistol_mag",2,15],["TKE_FRAG_mag",2,1],["TKE_SMOKE_mag",2,1],["ACE_Chemlight_IR",2,1]]],["TFAR_rt1523g_black",[["kat_IV_16",2],["ACE_splint",2],["ACE_surgicalKit",1],["ACE_MapTools",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_CableTie",4],["TKE_25rnd_762x51_mag",5,25]]],"TKE_UCMCHelm","TKE_CombatGlasses",["ACE_Vector","","","",[],[],""],["ItemMap","ItemMicroDAGR","TFAR_anprc152","ItemCompass","ItemWatch","TKE_IntegratedNVGs"]],
  ["TKE_UCNBPRifleV2_Optic","TKE_UCMRHelmOpen","TKE_UCMCArmour6_4","TKE_LightPackUCN","ItemcTab"]] call _reg;

["UCNMC_FireteamLead", "Fireteam Lead", "UCNMC",
  [["TKE_UCNRifle_Optic","","","",["TKE_25rnd_762x51_mag",25],[],""],[],["TKE_UCNPistol","","","",["TKE_UCNPistol_mag",15],[],""],["TKE_CombatUniRolledV1_U_B",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["kat_TXA",2],["ACE_EarPlugs",1],["ACE_painkillers",1,10]]],["TKE_UCMCArmour6_3",[["TKE_25rnd_762x51_mag",8,25],["TKE_UCNPistol_mag",2,15],["TKE_FRAG_mag",2,1],["TKE_SMOKE_mag",2,1],["ACE_Chemlight_IR",2,1]]],["TKE_LightPackUCN",[["kat_IV_16",2],["ACE_splint",2],["ACE_surgicalKit",1],["ACE_MapTools",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_CableTie",4],["TKE_25rnd_762x51_mag",6,25],["TKE_FRAG_mag",2,1]]],"TKE_UCMCHelm","TKE_CombatGlasses",["ACE_Vector","","","",[],[],""],["ItemMap","ItemMicroDAGR","TFAR_anprc152","ItemCompass","ItemWatch","TKE_IntegratedNVGs"]],
  ["TKE_UCNBPRifleV2_Optic","TKE_UCMRHelmOpen","TKE_UCMCArmour6_4","TFAR_rt1523g_black","ItemcTab"]] call _reg;

["UCNMC_Marksman", "Marksman", "UCNMC",
  [["TKE_UCNDMR_Optic","","","",["TKE_20rnd_969x51_magUCN",20],[],""],[],["TKE_UCNPistol","","","",["TKE_UCNPistol_mag",15],[],""],["TKE_CombatUniNARolled_U_B",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["kat_TXA",2],["ACE_EarPlugs",1],["ACE_painkillers",1,10]]],["TKE_UCMCArmour4_2",[["TKE_20rnd_969x51_magUCN",10,20],["TKE_UCNPistol_mag",2,15],["TKE_FRAG_mag",1,1],["TKE_SMOKE_mag",2,1],["ACE_Chemlight_IR",2,1]]],["TKE_RuckSack",[["kat_IV_16",2],["ACE_splint",2],["ACE_surgicalKit",1],["ACE_RangeCard",1],["ACE_ATragMX",1],["ACE_Kestrel4500",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["TKE_20rnd_969x51_magUCN",8,20],["TKE_20rnd_969x51_magUCNAP",4,20]]],"TKE_UCMCHelm","TKE_UCNFaceWear2",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ItemWatch","TKE_UCMCNvg"]],
  ["TKE_UCNDMR","TKE_20rnd_969x51_magUCNAP","TKE_UCMCHelmMaskV2","TKE_UCMCArmour4_1","ACE_Yardage450"]] call _reg;

["UCNMC_Heavy", "Heavy", "UCNMC",
  [["TKE_UCNLMG_Optic","","","",["TKE_150rnd_62x35_magUCN",150],[],""],[],["TKE_UCNPistol","","","",["TKE_UCNPistol_mag",15],[],""],["TKE_CombatUniRolledV1_U_B",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["kat_TXA",2],["ACE_EarPlugs",1],["ACE_painkillers",1,10]]],["TKE_UCMCArmour6_4",[["TKE_150rnd_62x35_magUCN",2,150],["TKE_UCNPistol_mag",2,15],["TKE_SMOKE_mag",2,1],["ACE_Chemlight_IR",2,1]]],["TKE_LightPackUCN",[["kat_IV_16",2],["ACE_splint",2],["ACE_surgicalKit",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["TKE_150rnd_62x35_magUCN",4,150],["TKE_150rnd_62x35_magUCNAP",2,150]]],"TKE_UCMCHelmClosedV2","TKE_FaceCoverGrey",[],["ItemMap","","TFAR_anprc152","ItemCompass","ItemWatch","TKE_IntegratedNVGs"]],
  ["TKE_UCNMMG_Optic","TKE_100rnd_ucnmmg_mag","TKE_150rnd_62x35_magUCNAP","TKE_UCMCHelmMaskV2"]] call _reg;

["UCNMC_HeavyAT", "Heavy / Anti-armour", "UCNMC",
  [["TKE_UCNBPRifle_Optic","","","",["TKE_30rnd_575x45_magTR",30],[],""],["TKE_ATRecoilless1","","","",["MRAWS_HEAT_F",1],[],""],["TKE_UCNPistol","","","",["TKE_UCNPistol_mag",15],[],""],["TKE_CombatUni_U_B",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["kat_TXA",2],["ACE_EarPlugs",1],["ACE_painkillers",1,10]]],["TKE_UCMCArmour3_2",[["TKE_30rnd_575x45_magTR",6,30],["TKE_UCNPistol_mag",2,15],["TKE_SMOKE_mag",2,1],["ACE_Chemlight_IR",2,1]]],["TKE_RuckSack",[["kat_IV_16",2],["ACE_splint",2],["ACE_surgicalKit",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["MRAWS_HEAT_F",2,1],["TKE_30rnd_575x45_magTR",4,30]]],"TKE_UCMCHelmClosedV2","",[],["ItemMap","","TFAR_anprc152","ItemCompass","ItemWatch","TKE_IntegratedNVGs"]],
  ["MRAWS_HE_F","TKE_UCMCHelmMaskV2","TKE_UCMCArmour6_4","TKE_LightPackUCN"]] call _reg;

["UCNMC_Corpsman", "Corpsman", "UCNMC",
  [["TKE_UCNBPRifle_Optic","","","",["TKE_30rnd_575x45_magTR",30],[],""],[],["TKE_UCNPistol","","","",["TKE_UCNPistol_mag",15],[],""],["TKE_CombatUniNARolled_U_B",[["ACE_elasticBandage",20],["ACE_packingBandage",20],["kat_chestSeal",10],["ACE_tourniquet",8],["ACE_morphine",6],["ACE_epinephrine",10],["kat_TXA",10],["ACE_EarPlugs",1],["kat_larynx",3]]],["TKE_UCMCArmour3_1",[["kat_IV_16",6],["ACE_plasmaIV_500",4],["kat_aatKit",4],["ACE_splint",4],["TKE_30rnd_575x45_magTR",5,30],["TKE_SMOKE_mag",2,1],["ACE_Chemlight_IR",2,1]]],["TKE_AlicePackUCNM_Med",[["kat_accuvac",1],["kat_X_AED",1],["kat_BVM",1],["kat_stethoscope",1],["ACE_surgicalKit",1],["kat_IO_FAST",3],["kat_fentanyl",3],["kat_ketamine",3],["kat_amiodarone",3],["ACE_adenosine",4],["kat_naloxone",4],["kat_EACA",5],["kat_Pulseoximeter",2],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1]]],"TKE_UCMCHelmM","",[],["ItemMap","","TFAR_anprc152","ItemCompass","ItemWatch","TKE_IntegratedNVGs"]],
  ["TFAR_rt1523g_black","TKE_UCMCHelm","TKE_UCMCArmour3_2","TKE_UCNRifle_Optic","TKE_RuckSack"]] call _reg;

["UCNMC_Sniper", "Sniper", "UCNMC",
  [["TKE_UCNSniper_R_Optic","","","",["5Rnd_127x108_Mag",5],[],""],[],["TKE_UCNPistol","","","",["TKE_UCNPistol_mag",15],[],""],["TKE_CombatUniNA_U_B",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["kat_TXA",2],["ACE_EarPlugs",1],["ACE_painkillers",1,10]]],["TKE_UCMCArmour1",[["5Rnd_127x108_Mag",8,5],["TKE_UCNPistol_mag",2,15],["TKE_SMOKE_mag",2,1],["ACE_Chemlight_IR",2,1]]],["TKE_Pattern83",[["kat_IV_16",2],["ACE_splint",2],["ACE_surgicalKit",1],["ACE_ATragMX",1],["ACE_Kestrel4500",1],["ACE_RangeCard",1],["ACE_MapTools",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["5Rnd_127x108_Mag",6,5],["5Rnd_127x108_APDS_Mag",4,5]]],"TKE_BoonieHatHS","TKE_MercAddonFW",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ItemWatch","TKE_ReconNVGUCN"]],
  ["5Rnd_127x108_APDS_Mag","TKE_UCNSniper","TKE_UCMCHelm","TKE_UCMCArmour4_2"]] call _reg;

["UCNMC_Spotter", "Spotter", "UCNMC",
  [["TKE_UCNDMR_Optic","","","",["TKE_20rnd_969x51_magUCN",20],[],""],[],["TKE_UCNPistol","","","",["TKE_UCNPistol_mag",15],[],""],["TKE_CombatUniNARolled_U_B",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["kat_TXA",2],["ACE_EarPlugs",1],["ACE_painkillers",1,10]]],["TKE_UCMCArmour1",[["TKE_20rnd_969x51_magUCN",8,20],["5Rnd_127x108_Mag",4,5],["TKE_UCNPistol_mag",2,15],["TKE_SMOKE_mag",2,1],["ACE_Chemlight_IR",2,1]]],["TKE_Pattern83",[["kat_IV_16",2],["ACE_splint",2],["ACE_surgicalKit",1],["ACE_ATragMX",1],["ACE_Kestrel4500",1],["ACE_RangeCard",1],["ACE_MapTools",1],["ACE_SpottingScope",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["5Rnd_127x108_Mag",8,5]]],"TKE_BoonieHatHS","TKE_UCNFaceWear2",["ACE_Vector","","","",[],[],""],["ItemMap","ItemMicroDAGR","TFAR_anprc152","ItemCompass","ItemWatch","TKE_ReconNVGUCN"]],
  ["TKE_UCNDMR","TKE_20rnd_969x51_magUCNAP","TKE_UCMCHelm","TKE_UCMCArmour4_2","ACE_Yardage450"]] call _reg;

["UCNMC_MailmanChiefPilot", "Chief Pilot", "UCNMC",
  [[],[],["TKE_UCNPistol","","","",["TKE_UCNPistol_mag",15],[],""],["TKE_VoidSuit_U_B",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["kat_TXA",2],["ACE_EarPlugs",1],["ACE_painkillers",1,10]]],["TKE_PilotVest",[["TKE_UCNPistol_mag",4,15],["TKE_SMOKE_mag",2,1],["ACE_Chemlight_IR",2,1]]],["TFAR_rt1523g_black",[["kat_IV_16",2],["ACE_splint",2],["ACE_surgicalKit",1],["ACE_MapTools",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_CableTie",2]]],"TKE_UCNPilotHelmRV","",["ACE_Vector","","","",[],[],""],["ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","ItemWatch","TKE_IntegratedNVGs"]],
  ["TKE_UCNBPRifle_Optic","TKE_EVAPack","ItemMicroDAGR"]] call _reg;

["UCNMC_MailmanPilot", "Pilot", "UCNMC",
  [[],[],["TKE_UCNPistol","","","",["TKE_UCNPistol_mag",15],[],""],["TKE_VoidSuit_U_B",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["kat_TXA",2],["ACE_EarPlugs",1],["ACE_painkillers",1,10]]],["TKE_PilotVest",[["TKE_UCNPistol_mag",4,15],["TKE_SMOKE_mag",2,1],["ACE_Chemlight_IR",2,1]]],["TKE_EVAPack",[["kat_IV_16",2],["ACE_splint",2],["ACE_surgicalKit",1],["ACE_MapTools",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1]]],"TKE_UCNPilotHelmRV","",["ACE_Vector","","","",[],[],""],["ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","ItemWatch","TKE_IntegratedNVGs"]],
  ["TKE_UCNBPRifle_Optic","TFAR_rt1523g_black","ItemMicroDAGR"]] call _reg;

["UCNMC_MailmanGunner", "Gunner", "UCNMC",
  [["TKE_UCNBPRifle_Optic","","","",["TKE_30rnd_575x45_magTR",30],[],""],[],["TKE_UCNPistol","","","",["TKE_UCNPistol_mag",15],[],""],["TKE_CombatUniNARolled_U_B",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["kat_TXA",2],["ACE_EarPlugs",1],["ACE_painkillers",1,10]]],["TKE_UCMCArmour1",[["TKE_30rnd_575x45_magTR",6,30],["TKE_UCNPistol_mag",2,15],["TKE_SMOKE_mag",2,1],["ACE_Chemlight_IR",2,1]]],["TFAR_rt1523g_black",[["kat_IV_16",4],["ACE_plasmaIV_500",2],["ACE_splint",4],["ACE_surgicalKit",1],["kat_aatKit",2],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["TKE_30rnd_575x45_magTR",4,30]]],"TKE_FCrewHelm_BASE","TKE_UCMCGogglesDown",[],["ItemMap","ItemMicroDAGR","TFAR_anprc152","ItemCompass","ItemWatch","TKE_IntegratedNVGs"]],
  ["TKE_UCNLMG_Optic","TKE_AlicePackUCNM_Med","TKE_UCMCHelmClosedV2"]] call _reg;

["UCNMC_MailmanVehicleCdr", "Vehicle Commander", "UCNMC",
  [["TKE_UCNBPRifle_Optic","","","",["TKE_30rnd_575x45_magTR",30],[],""],[],["TKE_UCNPistol","","","",["TKE_UCNPistol_mag",15],[],""],["TKE_CombatUniNARolled_U_B",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["kat_TXA",2],["ACE_EarPlugs",1],["ACE_painkillers",1,10]]],["TKE_UCMCArmour1",[["TKE_30rnd_575x45_magTR",6,30],["TKE_UCNPistol_mag",2,15],["TKE_FRAG_mag",1,1],["TKE_SMOKE_mag",2,1],["ACE_Chemlight_IR",2,1]]],["TFAR_rt1523g_black",[["kat_IV_16",2],["ACE_splint",2],["ACE_surgicalKit",1],["ACE_MapTools",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_CableTie",4],["TKE_30rnd_575x45_magTR",4,30]]],"TKE_FCrewHelm_BASE","TKE_UCMCGogglesDown",["ACE_Vector","","","",[],[],""],["ItemMap","ItemMicroDAGR","TFAR_anprc152","ItemCompass","ItemWatch","TKE_IntegratedNVGs"]],
  ["TKE_UCNRifle_Optic","TKE_LightPackUCN","TKE_UCMCHelm","ItemcTab"]] call _reg;
