// Auto-generated from fn_kitCrate_SAS.sqf. Loadout arrays copied verbatim.
// Faction: SAS — 9 kits.

["SAS_PatrolCommander", "Patrol Commander", "SAS",
  [["MCC_KS3_FDE_SLK","MCC_MCQ1_Shroud_556_TAN","MCC_AR_NGAL_M600V_Tail_BLK_IRL","MCC_MicroT2_Down",["MCC_PMAG_556_556_30_MK262",30],[],"MCC_BCM_VFG_FDE"],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300T","MPP_ACRO_BLK",["MPP_15rnd_9MM_147JHP_G19",15],[],""],["McNab_G3_G_KP_P",[["kat_IV_16",2],["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",6],["ACE_epinephrine",3],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",4],["kat_TXA",2],["ACE_quikclot",2],["ACE_EarPlugs",1],["kat_Carbonate",1,10],["ACE_painkillers",1,10],["kat_Painkiller",1,4]]],["Jones_JPC_SLICK_PMAG_BLK",[["tsp_sling",1],["ACE_CableTie",5],["ItemAndroidMisc",1],["MCC_PMAG_556_556_30_MK262",6,30],["MPP_15rnd_9MM_147JHP_G19",2,15],["UK3CB_BAF_SmokeShell",2,1],["ACE_Chemlight_IR",4,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_HiRed",2,1],["rhs_mag_mk84",4,1],["rhs_mag_m67",2,1]]],["TRF_CAMELBACK_LR",[["ACE_plasmaIV_500",1],["kat_mask_M04",1],["ACE_ChalkBlue",1],["ACE_Kestrel4500",1],["ACE_Cellphone",1],["ACE_MapTools",1],["ACE_PlottingBoard",1],["kat_gasmaskFilter",1],["ACE_Flashlight_XL50",1],["ACE_IR_Strobe_Item",1],["ACE_SpraypaintBlue",1],["ACE_surgicalKit",1],["ACE_EHP",1],["ItemMicroDAGRMisc",1],["ItemcTabMisc",1],["cigs_morley_cigpack",1,20],["cigs_lighter",1,100],["Laserbatteries",1,1],["GX_DEPLOYABLE_MAGAZINE_BLACKHORNET_UAV",1,100],["BOT_magazine_FPV_AP_TI",2,1],["BOT_magazine_FPV_AT_TI",2,1],["acex_intelitems_notepad",1,1],["rhs_mag_an_m14_th3",1,1],["UK3CB_BAF_SmokeShellGreen",1,1],["UK3CB_BAF_SmokeShellRed",1,1],["UK3CB_BAF_SmokeShellBlue",1,1]]],"Ibrahim_SF_CT_P_VLI","Zulu_NoFrame_A_B_CROC_BLK_CLR",["UK3CB_BAF_Soflam_Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","KAT_Ranger","Marko_BNVD_NC_UW"]],
  ["McNab_G3_G_KP_P","Adams_Rugby_KP_NP","Adams_Rugby_LS_KP_NP","Z_G3_MC_KP_PCU_GRY_G_H","UKSFOW","Zulu_NoFrame_A_B_CROC_BLK_CLR","Zulu_MFrame_A_B_CROC_BLK_CLR","Zulu_StepIn_TAN_SHD_SF_B_CROC","UK3CB_BAF_G_Balaclava_Win","MCC_EXPS3_FDE","MCC_EXPS3_FDE_Down","MCC_MicroT2","MCC_MicroT2_Down","rhsusf_acc_su230"]] call _reg;

["SAS_LeadAssaulterPointMan", "Lead Assaulter / Point Man", "SAS",
  [["MCC_KS3_FDE_SLK","MCC_MCQ1_Shroud_556_TAN","MCC_AR_NGAL_M600V_Tail_BLK_IRL","MCC_EXPS3_FDE",["MCC_PMAG_556_556_30_MK262",30],[],"MCC_BCM_VFG_FDE"],["rhs_weap_m72a7","","rhsusf_acc_anpeq15side","",[],[],""],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300T","MPP_ACRO_BLK",["MPP_15rnd_9MM_147JHP_G19",15],[],""],["McNab_G3_G_KP_P",[["kat_IV_16",2],["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",6],["ACE_epinephrine",3],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",4],["kat_TXA",2],["ACE_quikclot",2],["ACE_EarPlugs",1],["kat_Carbonate",1,10],["ACE_painkillers",1,10],["kat_Painkiller",1,4]]],["Friday_JPC",[["tsp_sling",1],["ACE_CableTie",5],["tsp_lockpick",1],["ACE_Clacker",1],["tsp_breach_shock",1],["ACE_DefusalKit",1],["ItemAndroidMisc",1],["rhs_mag_m67",2,1],["rhs_mag_mk84",6,1],["rhs_mag_mk3a2",2,1],["UK3CB_BAF_SmokeShell",2,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_White",2,1],["ACE_Chemlight_HiRed",2,1],["tsp_breach_block_mag",4,1]]],["ZXX_JPC_Panel4B",[["ACE_plasmaIV_500",1],["ACE_surgicalKit",1],["kat_mask_M04",1],["ACE_EHP",1],["ACE_SpraypaintRed",1],["ACE_ChalkWhite",1],["ACE_ChalkRed",1],["ACE_Flashlight_XL50",1],["ACE_wirecutter",1],["ACE_IR_Strobe_Item",1],["kat_gasmaskFilter",1],["cigs_morley_cigpack",1,20],["cigs_lighter",1,100]]],"Ibrahim_SF_CT_P_VLI","Zulu_NoFrame_A_B_CROC_BLK_CLR",[],["ItemMap","ItemMicroDAGR","TFAR_anprc152","ItemCompass","KAT_Katmin","Marko_BNVD_NC_UW"]],
  ["McNab_G3_G_KP_P","Adams_Rugby_KP_NP","Adams_Rugby_LS_KP_NP","Z_G3_MC_KP_PCU_GRY_G_H","UKSFOW","Zulu_NoFrame_A_B_CROC_BLK_CLR","Zulu_MFrame_A_B_CROC_BLK_CLR","Zulu_StepIn_TAN_SHD_SF_B_CROC","UK3CB_BAF_G_Balaclava_Win","MCC_EXPS3_FDE","MCC_EXPS3_FDE_Down","MCC_MicroT2","MCC_MicroT2_Down","rhsusf_acc_su230"]] call _reg;

["SAS_WeaponsSpecialistSupportGunner", "Weapons Specialist / Support Gunner", "SAS",
  [["ZXX_MCC_KS1_FDE_SLK_NAS3","MCC_MCQ1_Shroud_556_TAN","MCC_AR_NGAL_M600V_Tail_BLK_IRL","MCC_EXPS3_FDE",["MCC_D60_556_60_MK262",60],[],"MCC_BCM_VFG_FDE"],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300T","MPP_ACRO_BLK",["MPP_15rnd_9MM_147JHP_G19",15],[],""],["McNab_G3_G_KP_P",[["kat_IV_16",2],["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",6],["ACE_epinephrine",3],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",4],["kat_TXA",2],["ACE_quikclot",2],["ACE_EarPlugs",1],["kat_Carbonate",1,10],["ACE_painkillers",1,10],["kat_Painkiller",1,4]]],["Galahad_AVS_A_D",[["tsp_sling",1],["ACE_CableTie",5],["ItemAndroidMisc",1],["MPP_15rnd_9MM_147JHP_G19",2,15],["UK3CB_BAF_SmokeShell",3,1],["rhs_mag_mk84",2,1],["rhs_mag_m67",2,1],["rhs_mag_mk3a2",1,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiGreen",2,1],["Louetta_556x45_IRTM_PMAG_40",7,40]]],["ZXX_AVS_Panel2",[["ACE_plasmaIV_500",1],["ACE_surgicalKit",1],["kat_mask_M04",1],["ACE_EHP",1],["ACE_Flashlight_XL50",1],["ACE_IR_Strobe_Item",1],["kat_gasmaskFilter",1],["cigs_morley_cigpack",1,20],["cigs_lighter",1,100],["rhsusf_m112_mag",2,1],["tsp_breach_silhouette_mag",1,1]]],"Ibrahim_SF_CT_P_VLI","Zulu_NoFrame_A_B_CROC_BLK_CLR",["ACE_Yardage450","","","",[],[],""],["ItemMap","ItemMicroDAGR","TFAR_anprc152","ItemCompass","KAT_Katmin","Marko_BNVD_NC_UW"]],
  ["McNab_G3_G_KP_P","Adams_Rugby_KP_NP","Adams_Rugby_LS_KP_NP","Z_G3_MC_KP_PCU_GRY_G_H","UKSFOW","Zulu_NoFrame_A_B_CROC_BLK_CLR","Zulu_MFrame_A_B_CROC_BLK_CLR","Zulu_StepIn_TAN_SHD_SF_B_CROC","UK3CB_BAF_G_Balaclava_Win","MCC_EXPS3_FDE","MCC_EXPS3_FDE_Down","MCC_MicroT2","MCC_MicroT2_Down","rhsusf_acc_su230"]] call _reg;

["SAS_PatrolSharpshooterMarksman", "Patrol Sharpshooter / Marksman", "SAS",
  [["MSS_SR25_65CM_14_LMT_FDE_AFG","MCC_HuxWrx_Flow_762TI","MCC_AR_NGAL_M600V_Tail_BLK_IRL","MCC_Mark5_10_FDE",["MSS_20rnd_AR10_MP_65CM_140ELDM",20],[],"MCC_MLOK_AFG_FDE"],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300T","MPP_ACRO_BLK",["MPP_15rnd_9MM_147JHP_G19",15],[],""],["McNab_G3_G_KP_P",[["kat_IV_16",2],["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",6],["ACE_epinephrine",3],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",4],["kat_TXA",2],["ACE_quikclot",2],["ACE_EarPlugs",1],["kat_Carbonate",1,10],["ACE_painkillers",1,10],["kat_Painkiller",1,4]]],["Bell_JPC",[["tsp_sling",1],["ACE_CableTie",5],["ItemAndroidMisc",1],["MPP_15rnd_9MM_147JHP_G19",2,15],["MSS_20rnd_AR10_MP_65CM_140ELDM",5,20],["rhs_mag_m67",2,1],["rhs_mag_mk84",2,1],["UK3CB_BAF_SmokeShell",2,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_UltraHiOrange",2,1]]],["ZXX_JPC_Panel7_CB_NB_NH",[["ACE_plasmaIV_500",1],["ACE_surgicalKit",1],["kat_mask_M04",1],["ACE_EHP",1],["ACE_IR_Strobe_Item",1],["kat_gasmaskFilter",1],["ACE_ATragMX",1],["ACE_Kestrel4500",1],["ACE_RangeCard",1],["ACE_SpottingScope",1],["cigs_morley_cigpack",1,20],["cigs_lighter",1,100],["ClaymoreDirectionalMine_Remote_Mag",2,1],["SLAMDirectionalMine_Wire_Mag",1,1]]],"Ibrahim_SF_CT_P_VLI","Zulu_NoFrame_A_B_CROC_BLK_CLR",["ACE_Vector","","","",[],[],""],["ItemMap","ItemMicroDAGR","TFAR_anprc152","ItemCompass","KAT_Ranger","Marko_BNVD_NC_UW"]],
  ["McNab_G3_G_KP_P","Adams_Rugby_KP_NP","Adams_Rugby_LS_KP_NP","Z_G3_MC_KP_PCU_GRY_G_H","UKSFOW","Zulu_NoFrame_A_B_CROC_BLK_CLR","Zulu_MFrame_A_B_CROC_BLK_CLR","Zulu_StepIn_TAN_SHD_SF_B_CROC","UK3CB_BAF_G_Balaclava_Win","rhsusf_acc_su230a","MCC_Mark5_10_FDE","MCC_Vortex_Elanor_Acro_TAN","MSS_Mark5_18_FDE_GM_NO_LRF_NO","MSS_Mark5_18_FDE_GM_NO_LRF_NV","MSS_Mark5_18_FDE_GM_NO_LRF_TI","MSS_Mark5_18_FDE_GM_NO_NO_NO"]] call _reg;

["SAS_AdvancedMedic", "Advanced Medic", "SAS",
  [["MCC_KS3_FDE_SLK_VFG","MCC_MCQ1_Shroud_556_TAN","MCC_AR_NGAL_M600V_Tail_BLK_IRL","MCC_MicroT2",["MCC_PMAG_556_556_30_MK262",30],[],"MCC_BCM_VFG_FDE"],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300T","MPP_ACRO_BLK",["MPP_15rnd_9MM_147JHP_G19",15],[],""],["McNab_G3_G_KP_P",[["kat_IV_16",8],["ACE_adenosine",8],["kat_amiodarone",3],["ACE_elasticBandage",15],["ACE_packingBandage",15],["kat_chestSeal",10],["ACE_epinephrine",10],["kat_IO_FAST",3],["kat_fentanyl",2],["kat_ketamine",2],["kat_larynx",8],["ACE_morphine",8],["kat_naloxone",8],["kat_Pulseoximeter",2],["ACE_tourniquet",8],["kat_TXA",10],["ACE_quikclot",10],["ACE_EarPlugs",1],["kat_Carbonate",2,10],["ACE_painkillers",2,10]]],["Drake_AVS",[["tsp_sling",1],["ACE_CableTie",5],["ACE_Flashlight_XL50",1],["ACE_IR_Strobe_Item",1],["ACE_EHP",1],["ItemAndroidMisc",1],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellRed",1,1],["UK3CB_BAF_SmokeShellYellow",1,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiWhite",4,1],["acex_intelitems_notepad",1,1],["rhs_mag_mk84",4,1],["MPP_15rnd_9MM_147JHP_G19",2,15],["MCC_PMAG_556_556_30_MK262",5,30]]],["ZuluMed2",[["kat_aatKit",4],["kat_accuvac",2],["kat_X_AED",1],["ACE_plasmaIV_500",4],["ACE_splint",3],["kat_stethoscope",1],["ACE_surgicalKit",1],["kat_sealant",1],["ACE_salineIV",4],["ACE_elasticBandage",15],["ACE_packingBandage",15],["kat_BVM",2],["kat_gasmaskFilter",2],["cigs_morley_cigpack",3,20],["cigs_lighter",1,100]]],"Ibrahim_SF_CT_P_VLI","Zulu_NoFrame_A_B_CROC_BLK_CLR",["ACE_Yardage450","","","",[],[],""],["ItemMap","ItemMicroDAGR","TFAR_anprc152","ItemCompass","KAT_Ranger","Marko_BNVD_NC_UW"]],
  ["McNab_G3_G_KP_P","Adams_Rugby_KP_NP","Adams_Rugby_LS_KP_NP","Z_G3_MC_KP_PCU_GRY_G_H","UKSFOW","Zulu_NoFrame_A_B_CROC_BLK_CLR","Zulu_MFrame_A_B_CROC_BLK_CLR","Zulu_StepIn_TAN_SHD_SF_B_CROC","UK3CB_BAF_G_Balaclava_Win","MCC_EXPS3_FDE","MCC_EXPS3_FDE_Down","MCC_MicroT2","MCC_MicroT2_Down","rhsusf_acc_su230"]] call _reg;

["SAS_JSFAWPilot", "JSFAW Pilot", "SAS",
  [["P_UKSF_L119A1_CQB_BLK","","rhsusf_acc_anpeq15","MCC_MicroT2",["MCC_PMAG_556_556_30_MK262_NAS3",30],[],"rhsusf_acc_kac_grip"],[],["MPP_G19_BLK_9","","MPP_X300T","",["MPP_15rnd_9MM_147FMJ_G19",15],[],""],["Z_C_MC_PCU_RG_G_NH_NB",[["kat_IV_16",4],["ACE_adenosine",2],["kat_amiodarone",1],["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_chestSeal",6],["kat_EACA",2],["ACE_epinephrine",5],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_tourniquet",6],["kat_TXA",2],["ACE_plasmaIV_500",1],["kat_Carbonate",1,10],["kat_Painkiller",1,4],["ACE_painkillers",2,10]]],["TRF_STV_Pilot",[["ACE_IR_Strobe_Item",1],["ItemAndroidMisc",1],["ACE_CableTie",1],["ACE_Clacker",1],["42cdo_vs17_item",1],["MPP_15rnd_9MM_147FMJ_G19",2,15],["UK3CB_BAF_SmokeShell",1,1],["DemoCharge_Remote_Mag",1,1],["MCC_PMAG_556_556_30_MK262_NAS3",2,30]]],["satcom_01",[["ACE_EHP",1],["ACE_EarPlugs",1],["ACE_splint",3],["ACE_surgicalKit",1],["ACE_plasmaIV_500",3]]],"UK3CB_BAF_H_PilotHelmetHeli_A","",[],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","KAT_STS","Marko_BNVD_NC_UW"]],
  ["Z_C_MC_PCU_RG_G_NH_NB","UKSFOW"]] call _reg;

["SAS_Sniper", "Sniper", "SAS",
  [["MSS_AXSR_338NM_SAGE","MSS_AML338_BLK_C","","MSS_SB_PMII_525_BLK_GM_NO_LRF_NO",["MSS_10rnd_338NM_300ATIP_AXSR",10],[],"MSS_Atlas_BT72"],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300T","MPP_ACRO_BLK",["MPP_15rnd_9MM_147JHP_G19",15],[],""],["U_B_FullGhillie_lsh",[["kat_IV_16",2],["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",6],["ACE_epinephrine",3],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",4],["kat_TXA",2],["ACE_quikclot",2],["ACE_EarPlugs",1],["kat_Carbonate",1,10],["ACE_painkillers",1,10],["kat_Painkiller",1,4]]],["UKAF_C2R_CBAV_MARKSMAN",[["ACE_CableTie",2],["ItemAndroidMisc",1],["tsp_sling",1],["ACE_Kestrel4500",1],["ACE_ATragMX",1],["ACE_RangeCard",1],["MSS_10rnd_338NM_300ATIP_AXSR",5,10],["MPP_15rnd_9MM_147JHP_G19",2,15],["UK3CB_BAF_SmokeShell",2,1],["rhs_mag_m67",1,1],["rhs_mag_mk84",1,1],["ACE_Chemlight_IR",2,1]]],["ZXX_JPC_Panel2",[["ACE_plasmaIV_500",1],["ACE_surgicalKit",1],["ACE_ChalkWhite",1],["ACE_EHP",1],["ACE_Tripod",1],["ACE_MapTools",1],["tsp_lockpick",1],["MPP_bti_blk",1],["cigs_morley_cigpack",1,20],["cigs_lighter",1,100],["MSS_10rnd_338NM_M1162_AXSR",2,10],["acex_intelitems_notepad",1,1]]],"Ibrahim_SF_CT_P_VLI","Zulu_NoFrame_A_B_CROC_BLK_CLR",["ACE_Vector","","","",[],[],""],["ItemMap","ItemMicroDAGR","TFAR_anprc152","ItemCompass","KAT_Ranger","Marko_BNVD_NC_UC"]],
  ["U_B_FullGhillie_lsh","U_B_FullGhillie_sard","U_B_FullGhillie_ard","U_B_T_FullGhillie_tna_F","U_TaigaGhillie","U_SnowGhillie","U_GarbageGhillie3","U_AlpGhillie","DPM_FullGhillie","McNab_G3_G_KP_P","Z_G3_MC_KP_PCU_RG_G_NH","UKSFOW","ZXX_JPC_Panel2","molot_lapa_mc_v1","molot_lapa_mct_v1","molot_lapa_mcal_v1","molot_lapa_sapsan_v1","MSS_SB_PMII_525_BLK_GM_NO_LRF_NO","MSS_SB_PMII_525_BLK_GM_NO_LRF_NV"]] call _reg;

["SAS_Spotter", "Spotter", "SAS",
  [["MSS_SR25_65CM_16_B5_FDE","MSS_KAC_PRSQDC_FDE","","MSS_SB_PMII_525_BLK_GM_NO_LRF_NO",["MSS_20rnd_AR10_MP_65CM_M1200",20],[],"MSS_Harris_SBRMP"],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300T","MPP_ACRO_BLK",["MPP_15rnd_9MM_147JHP_G19",15],[],""],["U_B_FullGhillie_lsh",[["kat_IV_16",2],["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",6],["ACE_epinephrine",3],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",4],["kat_TXA",2],["ACE_quikclot",2],["ACE_EarPlugs",1],["kat_Carbonate",1,10],["ACE_painkillers",1,10],["kat_Painkiller",1,4]]],["UKAF_C2R_CBAV_MARKSMAN",[["ACE_CableTie",2],["ItemAndroidMisc",1],["tsp_sling",1],["ACE_Kestrel4500",1],["ACE_ATragMX",1],["ACE_RangeCard",1],["MPP_15rnd_9MM_147JHP_G19",2,15],["UK3CB_BAF_SmokeShell",2,1],["rhs_mag_m67",1,1],["rhs_mag_mk84",1,1],["ACE_Chemlight_IR",2,1],["UK3CB_BAF_SmokeShellRed",1,1],["UK3CB_BAF_SmokeShellGreen",1,1],["ACE_Chemlight_HiGreen",2,1],["MSS_20rnd_AR10_MP_65CM_M1200",5,20]]],["ZXX_JPC_Panel2",[["ACE_plasmaIV_500",1],["ACE_surgicalKit",1],["ACE_ChalkWhite",1],["ACE_EHP",1],["ACE_Tripod",1],["ACE_MapTools",1],["tsp_lockpick",1],["MPP_bti_blk",1],["ACE_SpottingScope",1],["cigs_morley_cigpack",1,20],["cigs_lighter",1,100],["acex_intelitems_notepad",1,1],["ClaymoreDirectionalMine_Remote_Mag",1,1]]],"Ibrahim_SF_CT_P_VLI","Zulu_NoFrame_A_B_CROC_BLK_CLR",["ACE_Vector","","","",[],[],""],["ItemMap","ItemMicroDAGR","TFAR_anprc152","ItemCompass","KAT_Ranger","Marko_BNVD_NC_UC"]],
  ["U_B_FullGhillie_lsh","U_B_FullGhillie_sard","U_B_FullGhillie_ard","U_B_T_FullGhillie_tna_F","U_TaigaGhillie","U_SnowGhillie","U_GarbageGhillie3","U_AlpGhillie","DPM_FullGhillie","McNab_G3_G_KP_P","Z_G3_MC_KP_PCU_RG_G_NH","UKSFOW","ZXX_JPC_Panel2","molot_lapa_mc_v1","molot_lapa_mct_v1","molot_lapa_mcal_v1","molot_lapa_sapsan_v1","MSS_SB_PMII_525_BLK_GM_NO_LRF_NO","MSS_SB_PMII_525_BLK_GM_NO_LRF_NV","MSS_SB_PMII_525_BLK_GM_NO_LRF_TI"]] call _reg;

["SAS_SUASOperator", "SUAS Operator", "SAS",
  [["MCC_KS1_FDE_CTR_AFG","MCC_MCQ1_Shroud_556_TAN","MCC_AR_NGAL_M600V_Tail_BLK_IRL","MCC_Vortex_Elanor_Acro_TAN",["MCC_PMAG_556_556_30_MK262",30],[],"MCC_MLOK_AFG_FDE"],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300T","MPP_ACRO_BLK",["MPP_15rnd_9MM_147JHP_G19",15],[],""],["McNab_G3_G_KP_P",[["kat_IV_16",2],["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",6],["ACE_epinephrine",3],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",4],["kat_TXA",2],["ACE_quikclot",2],["ACE_EarPlugs",1],["kat_Carbonate",1,10],["ACE_painkillers",1,10],["kat_Painkiller",1,4]]],["Jones_JPC_SLICK_PMAG_BLK",[["tsp_sling",1],["ACE_CableTie",5],["ItemAndroidMisc",1],["MPP_15rnd_9MM_147JHP_G19",2,15],["UK3CB_BAF_SmokeShell",2,1],["ACE_Chemlight_IR",4,1],["rhs_mag_mk84",2,1],["rhs_mag_m67",1,1],["MCC_PMAG_556_556_30_MK262",5,30],["UK3CB_BAF_SmokeShellBlue",1,1]]],["TRF_TRIZIP_LR",[["ACE_plasmaIV_500",1],["ACE_Flashlight_XL50",1],["ACE_IR_Strobe_Item",1],["ACE_SpraypaintBlue",1],["ACE_surgicalKit",1],["ACE_EHP",1],["ItemMicroDAGRMisc",1],["GX_UAVBattery",4],["cigs_morley_cigpack",1,20],["cigs_lighter",1,100],["Laserbatteries",1,1],["GX_DEPLOYABLE_MAGAZINE_BLACKHORNET_UAV",2,100],["BOT_magazine_FPV_AP_TI",3,1],["BOT_magazine_FPV_AT_TI",3,1],["acex_intelitems_notepad",1,1],["GX_DEPLOYABLE_MAGAZINE_RQ11B_UAV",1,100],["BOT_magazine_FPV_AT_HD",1,1],["BOT_magazine_FPV_AP_HD",1,1]]],"Ibrahim_SF_CT_P_VLI","Zulu_NoFrame_A_B_CROC_BLK_CLR",["UK3CB_BAF_Soflam_Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","KAT_Ranger","Marko_BNVD_NC_UW"]],
  ["McNab_G3_G_KP_P","Adams_Rugby_KP_NP","Adams_Rugby_LS_KP_NP","Z_G3_MC_KP_PCU_GRY_G_H","UKSFOW","Zulu_NoFrame_A_B_CROC_BLK_CLR","Zulu_MFrame_A_B_CROC_BLK_CLR","Zulu_StepIn_TAN_SHD_SF_B_CROC","UK3CB_BAF_G_Balaclava_Win","MCC_EXPS3_FDE","MCC_EXPS3_FDE_Down","MCC_MicroT2","MCC_MicroT2_Down","rhsusf_acc_su230","MCC_Vortex_Elanor_Acro_TAN"]] call _reg;
