// Auto-generated from fn_kitCrate_RANGER.sqf. Loadout arrays copied verbatim.
// Faction: RANGER — 12 kits.

["RANGER_SupportOperator", "Support Operator", "RANGER",
  [["ZXX_MCC_KS1_FDE_CTR_NAS3","MCC_MCQ1_Shroud_556_TAN","MCC_VarioRay_IRL","MCC_Vortex_Elanor_Acro_TAN",["MCC_PMAG_556_FDE_556_30_MK262",30],[],"MCC_MLOK_AFG_FDE"],[],["P_UKSF_Glock17_G4","","P_UKSF_Acc_SFX300U_Blk","MPP_RMR_BLK",["P_UKSF_Mag_17rnd_9MM_FMJ_G17",17],[],""],["Kemp_G4_G_KP_P",[["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_IV_16",6],["ACE_adenosine",2],["kat_amiodarone",1],["kat_chestSeal",8],["kat_EACA",2],["ACE_epinephrine",6],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",8],["kat_TXA",2],["ACE_painkillers",2,10],["kat_Painkiller",2,4],["kat_Carbonate",1,10],["cigs_lighter",1,100],["cigs_craven_cigpack",1,20]]],["Mullings_JPC",[["ACE_CableTie",4],["tsp_sling",1],["ItemAndroidMisc",1],["rhs_mag_m67",2,1],["UK3CB_BAF_SmokeShellPurple",1,1],["UK3CB_BAF_SmokeShellGreen",1,1],["UK3CB_BAF_SmokeShell",2,1],["ACE_Chemlight_HiRed",4,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1],["P_UKSF_Mag_17rnd_9MM_FMJ_G17",2,17],["rhs_mag_mk84",2,1],["MCC_PMAG_556_556_30_MK262",7,30]]],["ZXX_JPC_Panel7_CB_NB_NH",[["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_IR_Strobe_Item",1],["ACE_surgicalKit",1],["ACE_plasmaIV_500",4],["acex_intelitems_notepad",1,1]]],"Mullings_Maritime_CT_P_VLI","Zulu_NoFrame_A_M_MC_BLK_PPL",["ACE_Yardage450","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","KAT_Katmin","Kestrel_BLK_SF_UW_NC"]],
  ["Kemp_G4_G_KP_P","UKSFOW","UK3CB_BAF_G_Balaclava_Win","Grimes_Rugby_NG_KP_NP","MCC_MLOK_AFG_FDE","MCC_BCM_VFG_FDE","MCC_EXPS3_FDE","MCC_EXPS3_FDE_Down","MCC_Romeo9T_FDE_Down","MCC_MicroT2","MCC_MicroT2_Down","MCC_Vortex_Elanor_Acro_TAN","Zulu_NoFrame_A_M_MC_BLK_PPL"]] call _reg;

["RANGER_LeadScout", "Lead Scout", "RANGER",
  [["ZXX_MCC_KS1_FDE_CTR_NAS3","MCC_MCQ1_Shroud_556_TAN","MCC_VarioRay_IRL","MCC_Vortex_Elanor_Acro_TAN",["MCC_PMAG_556_556_30_MK262",30],[],"MCC_MLOK_AFG_FDE"],[],["rhs_weap_M320","","","",["UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",1],[],""],["Kemp_G4_G_KP_P",[["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_IV_16",6],["ACE_adenosine",2],["kat_amiodarone",1],["kat_chestSeal",8],["kat_EACA",2],["ACE_epinephrine",6],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",8],["kat_TXA",2],["ACE_painkillers",2,10],["kat_Painkiller",2,4],["kat_Carbonate",1,10],["cigs_craven_cigpack",1,20],["cigs_lighter",1,100],["MCC_PMAG_556_556_30_MK262",1,30]]],["Mullings_JPC",[["ACE_CableTie",4],["tsp_sling",1],["ItemAndroidMisc",1],["rhs_mag_m67",2,1],["UK3CB_BAF_SmokeShellPurple",2,1],["UK3CB_BAF_SmokeShellGreen",1,1],["ACE_Chemlight_HiRed",4,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",4,1],["UK3CB_BAF_SmokeShellOrange",1,1],["rhs_mag_mk84",2,1],["MCC_PMAG_556_556_30_MK262",5,30]]],["ZXX_Backpack_1_MC_JPC",[["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_IR_Strobe_Item",2],["ACE_Kestrel4500",1],["ACE_EntrenchingTool",1],["ACE_PlottingBoard",1],["ACE_wirecutter",1],["ACE_RangeCard",1],["ACE_ATragMX",1],["tsp_lockpick",1],["GX_UAVBattery",2],["ACE_plasmaIV_500",4],["ACE_surgicalKit",1],["acex_intelitems_notepad",1,1],["Laserbatteries",2,1],["GX_DEPLOYABLE_MAGAZINE_BLACKHORNET_UAV",2,100],["UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",5,1],["UK3CB_BAF_1Rnd_Smoke_Grenade_shell",2,1],["UK3CB_BAF_1Rnd_SmokeRed_Grenade_shell",1,1],["UK3CB_BAF_UGL_FlareCIR_F",2,1],["UK3CB_BAF_UGL_FlareWhite_F",1,1]]],"Mullings_Maritime_CT_P_VLI","Zulu_NoFrame_A_M_MC_BLK_PPL",["UK3CB_BAF_Soflam_Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","KAT_Katmin","Kestrel_BLK_SF_UW_NC"]],
  ["Kemp_G4_G_KP_P","UKSFOW","UK3CB_BAF_G_Balaclava_Win","Grimes_Rugby_NG_KP_NP","MCC_MLOK_AFG_FDE","MCC_BCM_VFG_FDE","MCC_EXPS3_FDE","MCC_EXPS3_FDE_Down","MCC_Romeo9T_FDE_Down","MCC_MicroT2","MCC_MicroT2_Down","MCC_Vortex_Elanor_Acro_TAN","Zulu_NoFrame_A_M_MC_BLK_PPL"]] call _reg;

["RANGER_LeadBreacher", "Lead Breacher", "RANGER",
  [["ZXX_MCC_KS1_FDE_CTR_AFG_NAS3","MCC_MCQ1_Shroud_556_TAN","MCC_VarioRay_IRL","MCC_Vortex_Elanor_Acro_TAN",["MCC_PMAG_556_FDE_556_30_MK262",30],[],"MCC_MLOK_AFG_FDE"],["tsp_meleeWeapon_halligan","","","",[],[],""],["P_UKSF_Glock17_G4","","P_UKSF_Acc_SFX300U_Blk","MPP_RMR_BLK",["P_UKSF_Mag_17rnd_9MM_FMJ_G17",17],[],""],["Kemp_G4_G_KP_P",[["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_IV_16",6],["ACE_adenosine",2],["kat_amiodarone",1],["kat_chestSeal",8],["kat_EACA",2],["ACE_epinephrine",6],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",8],["kat_TXA",2],["ACE_plasmaIV_500",4],["ACE_painkillers",2,10],["kat_Painkiller",2,4],["kat_Carbonate",1,10]]],["Francis_AVS_A",[["ACE_CableTie",4],["tsp_sling",1],["ItemAndroidMisc",1],["ACE_DefusalKit",1],["ACE_M26_Clacker",1],["tsp_lockpick",1],["tsp_breach_shock",1],["ACE_surgicalKit",1],["rhs_mag_m67",2,1],["UK3CB_BAF_SmokeShell",2,1],["ACE_Chemlight_HiRed",6,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1],["P_UKSF_Mag_17rnd_9MM_FMJ_G17",2,17],["rhs_mag_mk84",6,1],["ACE_CTS9",4,1],["MCC_PMAG_556_FDE_556_30_MK262_NAS3",6,30],["cigs_lighter",1,100],["cigs_craven_cigpack",1,20]]],["ZXX_AVS_Panel4B",[["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_IR_Strobe_Item",1],["ACE_wirecutter",1],["iedd_item_notebook",1],["acex_intelitems_notepad",1,1],["tsp_breach_popper_mag",4,1],["tsp_breach_stick_mag",2,1],["tsp_breach_linear_mag",2,1],["tsp_breach_silhouette_mag",1,1],["DemoCharge_Remote_Mag",2,1]]],"Mullings_Maritime_CT_P_VLI","Zulu_NoFrame_A_M_MC_BLK_PPL",[],["ItemMap","","TFAR_anprc152","ItemCompass","KAT_Katmin","Kestrel_BLK_SF_UW_NC"]],
  ["Kemp_G4_G_KP_P","UKSFOW","UK3CB_BAF_G_Balaclava_Win","Grimes_Rugby_NG_KP_NP","MCC_MLOK_AFG_FDE","MCC_BCM_VFG_FDE","MCC_EXPS3_FDE","MCC_EXPS3_FDE_Down","MCC_Romeo9T_FDE_Down","MCC_MicroT2","MCC_MicroT2_Down","MCC_Vortex_Elanor_Acro_TAN","Zulu_NoFrame_A_M_MC_BLK_PPL"]] call _reg;

["RANGER_JointFiresObserver", "Joint Fires Observer", "RANGER",
  [["ZXX_MCC_KS1_FDE_CTR_NAS3","MCC_MCQ1_Shroud_556_TAN","MCC_VarioRay_IRL","MCC_Vortex_Elanor_Acro_TAN",["MCC_PMAG_556_FDE_556_30_MK262",30],[],"MCC_MLOK_AFG_FDE"],[],["P_UKSF_Glock17_G4","","P_UKSF_Acc_SFX300U_Blk","MPP_RMR_BLK",["P_UKSF_Mag_17rnd_9MM_FMJ_G17",17],[],""],["Kemp_G4_G_KP_P",[["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_IV_16",6],["ACE_adenosine",2],["kat_amiodarone",1],["kat_chestSeal",8],["kat_EACA",2],["ACE_epinephrine",6],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",8],["kat_TXA",2],["ACE_painkillers",2,10],["kat_Painkiller",2,4],["kat_Carbonate",1,10],["cigs_craven_cigpack",1,20],["cigs_lighter",1,100]]],["marko_njpc_red2",[["ACE_CableTie",4],["tsp_sling",1],["ItemAndroidMisc",1],["MCC_PMAG_556_556_30_MK262",5,30],["rhs_mag_m67",2,1],["UK3CB_BAF_SmokeShellPurple",1,1],["UK3CB_BAF_SmokeShell",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",6,1],["P_UKSF_Mag_17rnd_9MM_FMJ_G17",2,17],["rhs_mag_mk84",2,1],["UK3CB_BAF_SmokeShellBlue",2,1],["UK3CB_BAF_SmokeShellOrange",2,1]]],["TRF_VIRTUS_ASSAULT_PACK_FAC",[["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_IR_Strobe_Item",1],["ItemcTabMisc",1],["ACE_ATragMX",1],["ACE_Kestrel4500",1],["ace_flags_orange",1],["ACE_PlottingBoard",1],["GX_UAVBattery",1],["ACE_plasmaIV_500",4],["ACE_surgicalKit",1],["acex_intelitems_notepad",1,1],["Laserbatteries",2,1],["GX_DEPLOYABLE_MAGAZINE_BLACKHORNET_UAV",1,100]]],"Jones_SF_C_HB_BOFF_BP_P_VL","Zulu_NoFrame_A_M_MC_BLK_PPL",["UK3CB_BAF_Soflam_Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","KAT_Katmin","Kestrel_BLK_SF_UW_NC"]],
  ["Kemp_G4_G_KP_P","UKSFOW","UK3CB_BAF_G_Balaclava_Win","Grimes_Rugby_NG_KP_NP","MCC_MLOK_AFG_FDE","MCC_BCM_VFG_FDE","MCC_EXPS3_FDE","MCC_EXPS3_FDE_Down","MCC_Romeo9T_FDE_Down","MCC_MicroT2","MCC_MicroT2_Down","MCC_Vortex_Elanor_Acro_TAN","Zulu_NoFrame_A_M_MC_BLK_PPL"]] call _reg;

["RANGER_TeamMedic", "Team Medic", "RANGER",
  [["ZXX_MCC_KS1_FDE_CTR_NAS3","MCC_MCQ1_Shroud_556_TAN","MCC_VarioRay_IRL","MCC_Vortex_Elanor_Acro_TAN",["MCC_PMAG_556_FDE_556_30_MK262",30],[],"MCC_MLOK_AFG_FDE"],[],["P_UKSF_Glock17_G4","","P_UKSF_Acc_SFX300U_Blk","MPP_RMR_BLK",["P_UKSF_Mag_17rnd_9MM_FMJ_G17",17],[],""],["Kemp_G4_G_KP_P",[["kat_IV_16",8],["ACE_adenosine",8],["kat_amiodarone",4],["ACE_elasticBandage",15],["ACE_packingBandage",15],["kat_BVM",1],["kat_chestSeal",10],["kat_EACA",8],["ACE_epinephrine",10],["kat_IO_FAST",4],["kat_fentanyl",2],["kat_ketamine",2],["kat_larynx",4],["ACE_morphine",8],["kat_naloxone",6],["kat_Pulseoximeter",2],["kat_TXA",10],["kat_Carbonate",1,10],["ACE_painkillers",2,10],["cigs_lighter",1,100],["cigs_craven_cigpack",2,20]]],["Galahad_AVS_L_D",[["ACE_CableTie",4],["tsp_sling",1],["ItemAndroidMisc",1],["ACE_IR_Strobe_Item",1],["MCC_PMAG_556_556_30_MK262",5,30],["rhs_mag_m67",1,1],["UK3CB_BAF_SmokeShellGreen",2,1],["UK3CB_BAF_SmokeShell",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_IR",2,1],["P_UKSF_Mag_17rnd_9MM_FMJ_G17",2,17],["rhs_mag_mk84",2,1],["acex_intelitems_notepad",1,1],["ACE_Chemlight_HiBlue",4,1]]],["Jones_MRASAP",[["ACE_surgicalKit",1],["kat_stethoscope",1],["kat_accuvac",1],["kat_aatKit",13],["ACE_plasmaIV",4],["ACE_plasmaIV_500",4],["ACE_splint",8],["ACE_tourniquet",8],["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["GX_UAVBattery",1],["kat_X_AED",1],["ACE_elasticBandage",5],["ACE_packingBandage",5],["GX_DEPLOYABLE_MAGAZINE_BLACKHORNET_UAV",1,100]]],"Mullings_Maritime_CT_P_VLI","Zulu_NoFrame_A_M_MC_BLK_PPL",[],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","KAT_Katmin","Kestrel_BLK_SF_UW_NC"]],
  ["Kemp_G4_G_KP_P","UKSFOW","UK3CB_BAF_G_Balaclava_Win","Grimes_Rugby_NG_KP_NP","MCC_MLOK_AFG_FDE","MCC_BCM_VFG_FDE","MCC_EXPS3_FDE","MCC_EXPS3_FDE_Down","MCC_Romeo9T_FDE_Down","MCC_MicroT2","MCC_MicroT2_Down","MCC_Vortex_Elanor_Acro_TAN","Zulu_NoFrame_A_M_MC_BLK_PPL"]] call _reg;

["RANGER_UASOperator", "UAS Operator", "RANGER",
  [["ZXX_MCC_KS1_FDE_CTR_NAS3","MCC_MCQ1_Shroud_556_TAN","MCC_VarioRay_IRL","MCC_Vortex_Elanor_Acro_TAN",["MCC_PMAG_556_FDE_556_30_MK262",30],[],"MCC_MLOK_AFG_FDE"],[],["P_UKSF_Glock17_G4","","P_UKSF_Acc_SFX300U_Blk","MPP_RMR_BLK",["P_UKSF_Mag_17rnd_9MM_FMJ_G17",17],[],""],["Kemp_G4_G_KP_P",[["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_IV_16",6],["ACE_adenosine",2],["kat_amiodarone",1],["kat_chestSeal",8],["kat_EACA",2],["ACE_epinephrine",6],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",8],["kat_TXA",2],["ACE_plasmaIV_500",4],["ACE_painkillers",2,10],["kat_Painkiller",2,4],["kat_Carbonate",1,10],["cigs_lighter",1,100],["cigs_craven_cigpack",1,20]]],["Friday_JPC",[["ACE_CableTie",4],["tsp_sling",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_surgicalKit",1],["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_IR_Strobe_Item",2],["ItemAndroidMisc",1],["MCC_PMAG_556_556_30_MK262",5,30],["rhs_mag_m67",2,1],["UK3CB_BAF_SmokeShellPurple",1,1],["UK3CB_BAF_SmokeShellGreen",1,1],["UK3CB_BAF_SmokeShell",2,1],["ACE_Chemlight_HiRed",1,1],["ACE_Chemlight_HiGreen",1,1],["ACE_Chemlight_IR",4,1],["P_UKSF_Mag_17rnd_9MM_FMJ_G17",2,17],["rhs_mag_mk84",2,1],["ACE_Chemlight_UltraHiOrange",2,1],["GX_DEPLOYABLE_MAGAZINE_BLACKHORNET_UAV",2,100],["acex_intelitems_notepad",1,1]]],["ZXX_CL",[["ItemcTabMisc",1],["GX_UAVBattery",3],["GX_DEPLOYABLE_MAGAZINE_RQ11B_UAV",1,100],["BOT_magazine_FPV_AP_HD",2,1],["BOT_magazine_FPV_AP_TI",1,1],["BOT_magazine_FPV_AT_HD",1,1],["BOT_magazine_FPV_AT_TI",1,1]]],"Mullings_Maritime_CT_NP_VLI","Zulu_NoFrame_A_M_MC_BLK_PPL",["ACE_Vector","","","",[],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","KAT_Katmin","Kestrel_BLK_SF_UW_NC"]],
  ["Kemp_G4_G_KP_P","UKSFOW","UK3CB_BAF_G_Balaclava_Win","Grimes_Rugby_NG_KP_NP","MCC_MLOK_AFG_FDE","MCC_BCM_VFG_FDE","MCC_EXPS3_FDE","MCC_EXPS3_FDE_Down","MCC_Romeo9T_FDE_Down","MCC_MicroT2","MCC_MicroT2_Down","MCC_Vortex_Elanor_Acro_TAN","Zulu_NoFrame_A_M_MC_BLK_PPL"]] call _reg;

["RANGER_EWOperator", "EW Operator", "RANGER",
  [["ZXX_MCC_KS1_FDE_CTR_NAS3","MCC_MCQ1_Shroud_556_TAN","MCC_VarioRay_IRL","MCC_Vortex_Elanor_Acro_TAN",["MCC_PMAG_556_FDE_556_30_MK262",30],[],"MCC_MLOK_AFG_FDE"],[],["P_UKSF_Glock17_G4","","P_UKSF_Acc_SFX300U_Blk","MPP_RMR_BLK",["P_UKSF_Mag_17rnd_9MM_FMJ_G17",17],[],""],["Kemp_G4_G_KP_P",[["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_IV_16",6],["ACE_adenosine",2],["kat_amiodarone",1],["kat_chestSeal",8],["kat_EACA",2],["ACE_epinephrine",6],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",8],["kat_TXA",2],["ACE_painkillers",2,10],["kat_Painkiller",2,4],["kat_Carbonate",1,10],["cigs_craven_cigpack",1,20],["cigs_lighter",1,100]]],["Mullings_JPC",[["ACE_CableTie",4],["tsp_sling",1],["ItemAndroidMisc",1],["MCC_PMAG_556_556_30_MK262",5,30],["rhs_mag_m67",2,1],["UK3CB_BAF_SmokeShellPurple",1,1],["UK3CB_BAF_SmokeShellGreen",1,1],["UK3CB_BAF_SmokeShell",2,1],["ACE_Chemlight_HiRed",4,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",4,1],["P_UKSF_Mag_17rnd_9MM_FMJ_G17",2,17],["rhs_mag_mk84",2,1],["ACE_Chemlight_HiBlue",2,1]]],["ZXX_Jammer",[["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_IR_Strobe_Item",2],["ItemcTabMisc",1],["MineDetector",1],["ToolKit",1],["ChemicalDetector_01_tan_F",1],["GX_UAVBattery",1],["ACE_plasmaIV_500",4],["ACE_surgicalKit",1],["acex_intelitems_notepad",1,1],["GX_DEPLOYABLE_MAGAZINE_BLACKHORNET_UAV",1,100]]],"Mullings_Maritime_CT_P_VLI","Zulu_NoFrame_A_M_MC_BLK_PPL",["ACE_Vector","","","",[],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","KAT_Katmin","Kestrel_BLK_SF_UW_NC"]],
  ["Kemp_G4_G_KP_P","UKSFOW","UK3CB_BAF_G_Balaclava_Win","Grimes_Rugby_NG_KP_NP","MCC_MLOK_AFG_FDE","MCC_BCM_VFG_FDE","MCC_EXPS3_FDE","MCC_EXPS3_FDE_Down","MCC_Romeo9T_FDE_Down","MCC_MicroT2","MCC_MicroT2_Down","MCC_Vortex_Elanor_Acro_TAN","Zulu_NoFrame_A_M_MC_BLK_PPL"]] call _reg;

["RANGER_PartnerLiason", "Partner Liason", "RANGER",
  [["ZXX_MCC_KS1_FDE_CTR_NAS3","MCC_MCQ1_Shroud_556_TAN","MCC_VarioRay_IRL","MCC_Vortex_Elanor_Acro_TAN",["MCC_PMAG_556_FDE_556_30_MK262",30],[],"MCC_MLOK_AFG_FDE"],[],["P_UKSF_Glock17_G4","","P_UKSF_Acc_SFX300U_Blk","MPP_RMR_BLK",["P_UKSF_Mag_17rnd_9MM_FMJ_G17",17],[],""],["Kemp_G4_G_KP_P",[["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_IV_16",6],["ACE_adenosine",2],["kat_amiodarone",1],["kat_chestSeal",8],["kat_EACA",2],["ACE_epinephrine",6],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",8],["kat_TXA",2],["ACE_painkillers",2,10],["kat_Painkiller",2,4],["kat_Carbonate",1,10],["cigs_lighter",1,100],["cigs_craven_cigpack",1,20]]],["Drake_AVS_Slick",[["ACE_CableTie",4],["tsp_sling",1],["ItemAndroidMisc",1],["MCC_PMAG_556_556_30_MK262",6,30],["rhs_mag_m67",2,1],["UK3CB_BAF_SmokeShellPurple",4,1],["UK3CB_BAF_SmokeShell",1,1],["ACE_Chemlight_IR",2,1],["P_UKSF_Mag_17rnd_9MM_FMJ_G17",2,17],["rhs_mag_mk84",2,1],["ACE_Chemlight_HiGreen",4,1],["ACE_Chemlight_HiWhite",4,1],["ACE_M14",1,1]]],["TRF_CAMELBACK_LR",[["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_IR_Strobe_Item",2],["ItemcTabMisc",1],["ACE_CableTie",10],["GX_UAVBattery",1],["ACE_plasmaIV_500",4],["ACE_surgicalKit",1],["GX_DEPLOYABLE_MAGAZINE_BLACKHORNET_UAV",1,100],["cigs_craven_cigpack",2,20],["cigs_lucky_strike_cigpack",2,20],["cigs_cigars_cigarbox_5",1,5]]],"Mullings_Maritime_CT_P_VLI","Zulu_NoFrame_A_M_MC_BLK_PPL",["ACE_Vector","","","",[],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","KAT_Katmin","Kestrel_BLK_SF_UW_NC"]],
  ["UKSFOW","UK3CB_BAF_G_Balaclava_Win","Kemp_G4_G_KP_P","Grimes_Rugby_NG_KP_NP","MCC_MLOK_AFG_FDE","MCC_BCM_VFG_FDE","MCC_EXPS3_FDE","MCC_EXPS3_FDE_Down","MCC_Romeo9T_FDE_Down","MCC_MicroT2","MCC_MicroT2_Down","MCC_Vortex_Elanor_Acro_TAN","Zulu_NoFrame_A_M_MC_BLK_PPL"]] call _reg;

["RANGER_TeamCommander", "Team Commander", "RANGER",
  [["ZXX_MCC_KS1_FDE_CTR_NAS3","MCC_MCQ1_Shroud_556_TAN","MCC_VarioRay_IRL","MCC_Vortex_Elanor_Acro_TAN",["MCC_PMAG_556_FDE_556_30_MK262",30],[],"MCC_MLOK_AFG_FDE"],[],["P_UKSF_Glock17_G4","","P_UKSF_Acc_SFX300U_Blk","MPP_RMR_BLK",["P_UKSF_Mag_17rnd_9MM_FMJ_G17",17],[],""],["Kemp_G4_G_KP_P",[["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_IV_16",6],["ACE_adenosine",2],["kat_amiodarone",1],["kat_chestSeal",8],["kat_EACA",2],["ACE_epinephrine",6],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",8],["kat_TXA",2],["ACE_painkillers",2,10],["kat_Painkiller",2,4],["kat_Carbonate",1,10],["cigs_lighter",1,100],["cigs_craven_cigpack",1,20]]],["Walsh_JPC_L",[["ACE_CableTie",4],["tsp_sling",1],["ItemAndroidMisc",1],["MCC_PMAG_556_556_30_MK262",5,30],["rhs_mag_m67",2,1],["UK3CB_BAF_SmokeShellGreen",1,1],["UK3CB_BAF_SmokeShell",2,1],["ACE_Chemlight_HiRed",4,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1],["P_UKSF_Mag_17rnd_9MM_FMJ_G17",2,17],["rhs_mag_mk84",2,1],["UK3CB_BAF_SmokeShellPurple",2,1]]],["ZXX_Slingshot_JPC_TFAR",[["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_IR_Strobe_Item",2],["ItemcTabMisc",1],["ACE_ChalkRed",1],["ACE_ChalkGreen",1],["GX_UAVBattery",1],["ACE_plasmaIV_500",4],["ACE_surgicalKit",1],["acex_intelitems_notepad",1,1],["Laserbatteries",2,1],["GX_DEPLOYABLE_MAGAZINE_BLACKHORNET_UAV",1,100]]],"Friday_SF_CT_P_VLI","Zulu_NoFrame_A_M_MC_BLK_PPL",["UK3CB_BAF_Soflam_Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","KAT_Katmin","Kestrel_BLK_SF_UW_NC"]],
  ["UKSFOW","UK3CB_BAF_G_Balaclava_Win","Kemp_G4_G_KP_P","Grimes_Rugby_NG_KP_NP","MCC_MLOK_AFG_FDE","MCC_BCM_VFG_FDE","MCC_EXPS3_FDE","MCC_EXPS3_FDE_Down","MCC_Romeo9T_FDE_Down","MCC_MicroT2","MCC_MicroT2_Down","MCC_Vortex_Elanor_Acro_TAN","Zulu_NoFrame_A_M_MC_BLK_PPL"]] call _reg;

["RANGER_TeamSergeant", "Team Sergeant", "RANGER",
  [["ZXX_MCC_KS1_FDE_CTR_NAS3","MCC_MCQ1_Shroud_556_TAN","MCC_VarioRay_IRL","MCC_Vortex_Elanor_Acro_TAN",["MCC_PMAG_556_FDE_556_30_MK262",30],[],"MCC_MLOK_AFG_FDE"],[],["P_UKSF_Glock17_G4","","P_UKSF_Acc_SFX300U_Blk","MPP_RMR_BLK",["P_UKSF_Mag_17rnd_9MM_FMJ_G17",17],[],""],["Kemp_G4_G_KP_P",[["ACE_elasticBandage",12],["ACE_packingBandage",12],["kat_IV_16",6],["ACE_adenosine",2],["kat_amiodarone",1],["kat_chestSeal",8],["kat_EACA",2],["ACE_epinephrine",6],["kat_IO_FAST",2],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",8],["kat_TXA",2],["ACE_plasmaIV_500",4],["ACE_painkillers",2,10],["kat_Painkiller",2,4],["kat_Carbonate",1,10],["cigs_lighter",1,100],["cigs_craven_cigpack",2,20]]],["Francis_AVS_A",[["ACE_CableTie",4],["tsp_sling",1],["ItemAndroidMisc",1],["GX_UAVBattery",1],["ACE_surgicalKit",1],["rhs_mag_m67",2,1],["UK3CB_BAF_SmokeShellGreen",1,1],["UK3CB_BAF_SmokeShell",2,1],["ACE_Chemlight_HiRed",4,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1],["P_UKSF_Mag_17rnd_9MM_FMJ_G17",2,17],["UK3CB_BAF_SmokeShellPurple",2,1],["MCC_PMAG_556_FDE_556_30_MK262",5,30],["rhs_mag_mk84",1,1],["Laserbatteries",1,1],["GX_DEPLOYABLE_MAGAZINE_BLACKHORNET_UAV",1,100]]],["TRF_CAMELBACK_LR",[["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_IR_Strobe_Item",2],["ItemcTabMisc",1],["ACE_ChalkRed",1],["ACE_ChalkGreen",1],["ACE_CableTie",6],["acex_intelitems_notepad",1,1],["Laserbatteries",1,1],["UK3CB_BAF_SmokeShellPurple",2,1],["UK3CB_BAF_SmokeShell",2,1],["UK3CB_BAF_SmokeShellGreen",1,1],["UK3CB_BAF_SmokeShellOrange",1,1],["UK3CB_BAF_SmokeShellBlue",1,1],["ACE_Chemlight_HiBlue",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiWhite",2,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_UltraHiOrange",2,1],["rhs_mag_m67",2,1],["rhs_mag_mk84",2,1]]],"Friday_SF_CT_P_VLI","Zulu_NoFrame_A_M_MC_BLK_PPL",["UK3CB_BAF_Soflam_Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","KAT_Katmin","Kestrel_BLK_SF_UW_NC"]],
  ["UKSFOW","UK3CB_BAF_G_Balaclava_Win","Kemp_G4_G_KP_P","Grimes_Rugby_NG_KP_NP","MCC_MLOK_AFG_FDE","MCC_BCM_VFG_FDE","MCC_EXPS3_FDE","MCC_EXPS3_FDE_Down","MCC_Romeo9T_FDE_Down","MCC_MicroT2","MCC_MicroT2_Down","MCC_Vortex_Elanor_Acro_TAN","Zulu_NoFrame_A_M_MC_BLK_PPL"]] call _reg;

["RANGER_Crewman", "Crewman", "RANGER",
  [[],[],["P_UKSF_Glock17_G4","","","",["P_UKSF_Mag_17rnd_9MM_FMJ_G17",17],[],""],["TRF_PCS_FS_NG_U",[["kat_IV_16",1],["ACE_adenosine",2],["ACE_elasticBandage",8],["ACE_packingBandage",8],["kat_chestSeal",2],["ACE_epinephrine",4],["ACE_morphine",2],["kat_naloxone",1],["ACE_splint",1],["kat_Painkiller",2,4],["cigs_matches",1,10],["cigs_lucky_strike_cigpack",1,20]]],["TRF_STV_Crew",[["ACE_tourniquet",4],["ACE_CableTie",2],["Kestrel_BLK_SF_U_C",1],["ACE_EarPlugs",1],["ACE_EHP",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_plasmaIV_500",1],["ItemAndroidMisc",1],["UK3CB_BAF_SmokeShell",1,1],["UK3CB_BAF_SmokeShellRed",1,1],["acex_intelitems_notepad",1,1],["Chemlight_green",1,1],["Chemlight_red",1,1],["P_UKSF_Mag_17rnd_9MM_FMJ_G17",3,17]]],[],"TRF_BATLSKIN_REVISION","UK3CB_BAF_G_Tactical_Clear",[],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","KAT_STS",""]],
  ["TRF_BATLSKIN_REVISION_IR","TRF_BATLSKIN_REVISION_NETTING_IR","TRF_BATLSKIN_REVISION_SCRIM_OAK","TRF_PCS_FS_NG_U","TRF_PCS_FS_G_U","TRF_PCS_HS_NG_U","TRF_PCS_HS_G_U","TRF_PCS_RS_NG_U","TRF_PCU_NG_U","TRF_PCU_G_U"]] call _reg;

["RANGER_Pilot", "Pilot", "RANGER",
  [[],[],["P_UKSF_Glock17_G4","","","",["P_UKSF_Mag_17rnd_9MM_FMJ_G17",17],[],""],["TRF_FLIGHTSUIT_18SQN",[["kat_IV_16",1],["ACE_adenosine",2],["ACE_elasticBandage",8],["ACE_packingBandage",8],["kat_chestSeal",2],["ACE_epinephrine",4],["ACE_morphine",2],["kat_naloxone",1],["ACE_splint",1],["kat_Painkiller",2,4],["cigs_lucky_strike_cigpack",1,20],["cigs_pops_poppack",1,1]]],["TRF_STV_Pilot",[["ACE_IR_Strobe_Item",1],["ItemAndroidMisc",1],["P_UKSF_Mag_17rnd_9MM_FMJ_G17",3,17]]],["satcom_01",[]],"UK3CB_BAF_H_PilotHelmetHeli_A","UK3CB_BAF_G_Tactical_Clear",[],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","KAT_STS","Marko_BNVD_NC_UW"]],
  []] call _reg;
