// Auto-generated from fn_kitCrate_SRR.sqf. Loadout arrays copied verbatim.
// Faction: SRR — 6 kits.

["SRR_PatrolCommander", "Patrol Commander", "SRR",
  [["MCC_M4A1_556_Troy_145_FDE_SLK_AFG","MCC_RC2_556","MCC_AR_NGAL_M600V_Tail_FDE_IRL","MCC_Mark5_10_BLK",["MCC_PMAG_556_556_30_MK262",30],[],"MCC_MLOK_AFG_FDE"],[],["MPP_G17_BLK_BLK_9","MPP_G17_TC","MPP_X300U","MPP_RMR_BLK",["MPP_17rnd_9MM_147JHP_G17",17],[],""],["Kemp_G3_G_KP_NP",[["kat_IV_16",2],["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",8],["ACE_epinephrine",3],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",4],["kat_TXA",2],["ACE_EarPlugs",1],["kat_Carbonate",1,10],["ACE_painkillers",1,10],["kat_Painkiller",1,4]]],["Friday_JPC",[["ACE_CableTie",5],["tsp_sling",1],["ItemAndroidMisc",1],["MCC_PMAG_556_556_30_MK262",5,30],["MPP_17rnd_9MM_147JHP_G17",2,17],["UK3CB_BAF_SmokeShell",2,1],["UK3CB_BAF_SmokeShellRed",1,1],["UK3CB_BAF_SmokeShellGreen",1,1],["rhs_mag_m67",1,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1]]],["Jones_MRASAP",[["BNVD_Galahad_U",1],["ACE_surgicalKit",1],["ACE_plasmaIV_500",1],["MPP_Lunar9S",1],["kat_mask_M04",1],["ACE_MapTools",1],["ACE_PlottingBoard",1],["ACE_RangeCard",1],["ACE_ATragMX",1],["ACE_Kestrel4500",1],["ACE_Flashlight_XL50",1],["ACE_IR_Strobe_Item",1],["kat_sealant",1],["kat_gasmaskFilter",1],["ACE_Clacker",1],["Walsh_SF_CT_NP_VLI",1],["ACE_EHP",1],["Laserbatteries",1,1],["rhs_mag_an_m14_th3",1,1],["MCC_USGI_556_556_30_MK262",2,30],["acex_intelitems_notepad",1,1],["ClaymoreDirectionalMine_Remote_Mag",2,1],["cigs_lighter",1,100],["cigs_morley_cigpack",1,20]]],"UKSF_Cap_T7_FW_MCH_ON_NF","Zulu_MFrame_A_M_RG_TAN_SHD",["UK3CB_BAF_Soflam_Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemMicroDAGR","TFAR_anprc152","ItemCompass","ACE_Altimeter","Marko_BNVD_NC_UW"]],
  ["MCC_Mark5_10_BLK","rhsusf_acc_su230_3d","Kemp_G3_G_KP_NP","UKSFOW","Zulu_MFrame_A_M_RG_TAN_SHD","Zulu_MFrame_M_RG_TAN_SHD"]] call _reg;

["SRR_ReconScout", "Recon Scout", "SRR",
  [["MCC_M4A1_556_Troy_115_FDE_Bravo_VFG","MCC_RC2_556","MCC_AR_PEQ15_M300C_Tail_BLK_IRL","MCC_EXPS3_UnityX_BLK_Down",["MCC_PMAG_556_556_30_MK262",30],[],"MCC_BCM_VFG_FDE"],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300U","MPP_RMR_BLK",["MPP_15rnd_9MM_147JHP_G19",15],[],""],["Kemp_G3_G_KP_NP",[["kat_IV_16",2],["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",8],["ACE_epinephrine",3],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",4],["kat_TXA",2],["ACE_EarPlugs",1],["kat_Carbonate",1,10],["ACE_painkillers",1,10],["kat_Painkiller",1,4],["cigs_morley_cigpack",1,20],["cigs_lighter",1,100]]],["Friday_JPC",[["ACE_CableTie",3],["tsp_lockpick",1],["tsp_sling",1],["ItemAndroidMisc",1],["MCC_PMAG_556_556_30_MK262",5,30],["MPP_15rnd_9MM_147JHP_G19",2,15],["UK3CB_BAF_SmokeShell",2,1],["rhs_mag_m67",2,1],["rhs_mag_mk3a2",1,1],["ACE_Chemlight_IR",4,1],["ACE_Chemlight_HiRed",1,1]]],["TRF_CAMELBACK",[["BNVD_Galahad_U",1],["ACE_plasmaIV_500",1],["ACE_surgicalKit",1],["MPP_Lunar9S",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_wirecutter",1],["ACE_ChalkWhite",1],["kat_mask_M04",1],["kat_gasmaskFilter",1],["kat_sealant",1],["ItemMicroDAGRMisc",1],["Walsh_SF_CT_NP_VLI",1],["ACE_EHP",1],["MCC_USGI_556_556_30_MK262",3,30],["tsp_breach_popper_auto_mag",2,1],["BOT_magazine_FPV_AP_TI",1,1]]],"UKSF_Cap_T7_FW_MCH_ON_NF","Zulu_MFrame_A_M_RG_TAN_SHD",["ACE_Vector","","","",[],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","KAT_Ranger","Marko_BNVD_NC_UW"]],
  ["MCC_MicroT2","MCC_MicroT2_Down","MCC_EXPS3_UnityX_BLK","MCC_EXPS3_UnityX_BLK_Down","rhsusf_acc_su230_3d","Kemp_G3_G_KP_NP","UKSFOW","Zulu_MFrame_A_M_RG_TAN_SHD","Zulu_MFrame_M_RG_TAN_SHD"]] call _reg;

["SRR_SIGINTCommsSpecialist", "SIGINT & Comms Specialist", "SRR",
  [["MCC_M4A1_556_Troy_115_FDE_Bravo","MCC_RC2_556","MCC_AR_PEQ15_M300C_Tail_BLK_IRL","MCC_MicroT2_Down",["MCC_PMAG_556_556_30_MK262",30],[],"MCC_BCM_VFG_FDE"],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300U","MPP_RMR_BLK",["MPP_15rnd_9MM_147JHP_G19",15],[],""],["Kemp_G3_G_KP_NP",[["kat_IV_16",2],["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",8],["ACE_epinephrine",3],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",4],["kat_TXA",2],["ACE_EarPlugs",1],["kat_Carbonate",1,10],["ACE_painkillers",1,10],["kat_Painkiller",1,4]]],["Mullings_JPC_NP",[["ACE_CableTie",4],["tsp_sling",1],["ItemAndroidMisc",1],["MCC_PMAG_556_556_30_MK262",4,30],["MPP_17rnd_9MM_147JHP_G17",2,17],["rhs_mag_m67",1,1],["UK3CB_BAF_SmokeShell",2,1],["UK3CB_BAF_SmokeShellYellow",1,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiBlue",2,1],["rhs_mag_an_m14_th3",2,1]]],["TRF_CAMELBACK_LR",[["BNVD_Galahad_U",1],["ACE_plasmaIV_500",1],["ACE_surgicalKit",1],["MPP_Lunar9S",1],["ACE_Cellphone",1],["ACE_SpraypaintBlue",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["kat_gasmaskFilter",1],["kat_sealant",1],["kat_mask_M04",1],["tsp_lockpick",1],["ACE_DefusalKit",1],["iedd_item_notebook",1],["ACE_Clacker",1],["Walsh_SF_CT_NP_VLI",1],["ACE_EHP",1],["MCC_USGI_556_556_30_MK262",3,30],["rhsusf_m112_mag",2,1],["cigs_morley_cigpack",1,20],["cigs_lighter",1,100]]],"UKSF_Cap_T7_FW_MCH_ON_NF","Zulu_MFrame_A_M_RG_TAN_SHD",["Nikon_DSLR_HUD","","","",[],[],""],["ItemMap","ItemMicroDAGR","TFAR_anprc152","ItemCompass","KAT_Cavmin","Marko_BNVD_NC_UW"]],
  ["MCC_MicroT2","MCC_MicroT2_Down","MCC_EXPS3_UnityX_BLK","MCC_EXPS3_UnityX_BLK_Down","rhsusf_acc_su230_3d","Kemp_G3_G_KP_NP","UKSFOW","Zulu_MFrame_A_M_RG_TAN_SHD","Zulu_MFrame_M_RG_TAN_SHD"]] call _reg;

["SRR_SystemsUASSpecialist", "Systems & UAS Specialist", "SRR",
  [["MCC_M4A1_556_Troy_145_FDE_SLK_AFG","MCC_RC2_556","MCC_AR_NGAL_M600V_Tail_FDE_IRL","MCC_Mark5_10_BLK",["MCC_PMAG_556_556_30_MK262",30],[],"MCC_MLOK_AFG_FDE"],[],["MPP_G17_BLK_BLK_9","MPP_G17_TC","MPP_X300U","MPP_RMR_BLK",["MPP_17rnd_9MM_147JHP_G17",17],[],""],["Kemp_G3_G_KP_NP",[["kat_IV_16",2],["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",8],["ACE_epinephrine",3],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",4],["kat_TXA",2],["ACE_EarPlugs",1],["kat_Carbonate",1,10],["ACE_painkillers",1,10],["kat_Painkiller",1,4]]],["Friday_JPC",[["ACE_CableTie",4],["tsp_sling",1],["ItemAndroidMisc",1],["MCC_PMAG_556_556_30_MK262",5,30],["MPP_17rnd_9MM_147JHP_G17",2,17],["UK3CB_BAF_SmokeShell",2,1],["UK3CB_BAF_SmokeShellOrange",1,1],["rhs_mag_m67",1,1],["ACE_Chemlight_HiYellow",2,1],["ACE_Chemlight_IR",2,1]]],["Bergen_MC_NB_NC",[["BNVD_Galahad_U",1],["ItemMicroDAGRMisc",1],["ACE_plasmaIV_500",1],["ACE_surgicalKit",1],["MPP_Lunar9S",1],["kat_mask_M04",1],["kat_sealant",1],["kat_gasmaskFilter",1],["ACE_ATragMX",1],["ACE_Kestrel4500",1],["ACE_RangeCard",1],["ACE_SpottingScope",1],["MineDetector",1],["ACE_EntrenchingTool",1],["ACE_Clacker",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["GX_UAVBattery",3],["Walsh_SF_CT_NP_VLI",1],["ACE_EHP",1],["MCC_USGI_556_556_30_MK262",2,30],["rhs_mag_an_m14_th3",1,1],["tsp_breach_linear_mag",1,1],["SLAMDirectionalMine_Wire_Mag",2,1],["GX_DEPLOYABLE_MAGAZINE_RQ11B_UAV",1,100],["GX_DEPLOYABLE_MAGAZINE_BLACKHORNET_UAV",2,100],["BOT_magazine_FPV_AT_TI",1,1],["BOT_magazine_FPV_AP_TI",1,1],["cigs_lighter",1,100],["cigs_morley_cigpack",1,20]]],"UKSF_Cap_T7_FW_MCH_ON_NF","Zulu_MFrame_A_M_RG_TAN_SHD",["rhsusf_bino_m24_ARD","","","",[],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","KAT_Katmin","Marko_BNVD_NC_UW"]],
  ["MCC_Mark5_10_BLK","rhsusf_acc_su230_3d","Kemp_G3_G_KP_NP","UKSFOW","Zulu_MFrame_A_M_RG_TAN_SHD","Zulu_MFrame_M_RG_TAN_SHD"]] call _reg;

["SRR_PatrolMedic", "Patrol Medic", "SRR",
  [["MCC_M4A1_556_Troy_115_FDE_Bravo","MCC_RC2_556","MCC_AR_PEQ15_M300C_Tail_BLK_IRL","MCC_MicroT2",["MCC_PMAG_556_556_30_MK262",30],[],"MCC_BCM_VFG_FDE"],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300U","MPP_RMR_BLK",["MPP_15rnd_9MM_147JHP_G19",15],[],""],["Adams_G3_G_KP_P",[["kat_IV_16",8],["ACE_adenosine",4],["kat_amiodarone",3],["ACE_elasticBandage",15],["ACE_packingBandage",15],["kat_chestSeal",10],["ACE_epinephrine",10],["kat_IO_FAST",3],["kat_fentanyl",3],["kat_ketamine",3],["kat_larynx",3],["ACE_morphine",6],["kat_naloxone",6],["kat_Pulseoximeter",2],["ACE_tourniquet",8],["kat_TXA",10],["ACE_EarPlugs",1],["kat_EACA",5],["kat_Carbonate",1,10],["ACE_painkillers",2,10]]],["Friday_JPC",[["ACE_CableTie",4],["tsp_sling",1],["ACE_EHP",1],["ItemAndroidMisc",1],["MCC_PMAG_556_556_30_MK262",4,30],["MPP_15rnd_9MM_147JHP_G19",2,15],["UK3CB_BAF_SmokeShell",4,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",4,1]]],["ZuluMed2",[["BNVD_Galahad_U",1],["kat_aatKit",4],["kat_accuvac",1],["kat_X_AED",1],["kat_BVM",1],["ACE_plasmaIV_500",4],["ACE_splint",3],["kat_stethoscope",1],["ACE_surgicalKit",1],["MPP_Lunar9S",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["kat_gasmaskFilter",2],["kat_sealant",1],["Walsh_SF_CT_NP_VLI",1],["rhs_mag_m7a3_cs",1,1],["MCC_USGI_556_556_30_MK262",2,30],["cigs_morley_cigpack",3,20],["cigs_lighter",1,100]]],"UKSF_Cap_T7_FW_MCH_ON_NF","Zulu_MFrame_A_M_RG_TAN_SHD",["ACE_Yardage450","","","",[],[],""],["ItemMap","ItemMicroDAGR","TFAR_anprc152","ItemCompass","KAT_ChemicalDetector","Marko_BNVD_NC_UW"]],
  ["MCC_MicroT2","MCC_MicroT2_Down","MCC_EXPS3_UnityX_BLK","MCC_EXPS3_UnityX_BLK_Down","rhsusf_acc_su230_3d","Adams_G3_G_KP_P","UKSFOW","Zulu_MFrame_A_M_RG_TAN_SHD","Zulu_MFrame_M_RG_TAN_SHD"]] call _reg;

["SRR_ElectronicWarfareCounterUASSpecialist", "Electronic Warfare & Counter-UAS Specialist", "SRR",
  [["MCC_M4A1_556_Troy_115_FDE_Bravo","MCC_RC2_556","MCC_AR_PEQ15_M300C_Tail_BLK_IRL","MCC_MicroT2_Down",["MCC_PMAG_556_556_30_MK262",30],[],"MCC_BCM_VFG_FDE"],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300U","MPP_RMR_BLK",["MPP_15rnd_9MM_147JHP_G19",15],[],""],["Kemp_G3_G_KP_NP",[["kat_IV_16",2],["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",8],["ACE_epinephrine",3],["kat_larynx",2],["ACE_morphine",4],["kat_naloxone",2],["kat_Pulseoximeter",1],["ACE_splint",3],["ACE_tourniquet",4],["kat_TXA",2],["ACE_EarPlugs",1],["kat_Carbonate",1,10],["ACE_painkillers",1,10],["kat_Painkiller",1,4]]],["Walsh_JPC_L",[["ACE_CableTie",4],["tsp_sling",1],["MPP_Lunar9S",1],["tsp_lockpick",1],["ItemMicroDAGRMisc",1],["ACE_Clacker",1],["ACE_DefusalKit",1],["ItemAndroidMisc",1],["MCC_PMAG_556_556_30_MK262",4,30],["MPP_17rnd_9MM_147JHP_G17",2,17],["rhs_mag_m67",1,1],["UK3CB_BAF_SmokeShell",2,1],["UK3CB_BAF_SmokeShellYellow",1,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiBlue",2,1],["rhs_mag_an_m14_th3",2,1]]],["ZXX_Jammer",[["BNVD_Galahad_U",1],["ACE_plasmaIV_500",1],["ACE_surgicalKit",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["kat_gasmaskFilter",1],["kat_sealant",1],["kat_mask_M04",1],["iedd_item_notebook",1],["Walsh_SF_CT_NP_VLI",1],["crowsew_ctrack",2],["muzzle_antenna_01_f",1],["muzzle_antenna_03_f",1],["muzzle_antenna_02_f",1],["ACE_EHP",1],["MCC_USGI_556_556_30_MK262",2,30],["cigs_morley_cigpack",1,20],["cigs_lighter",1,100],[["hgun_esd_01_F","","","",[],[],""],1]]],"UKSF_Cap_T7_FW_MCH_ON_NF","Zulu_MFrame_A_M_RG_TAN_SHD",["Hate_Smartphone_HUD","","","",[],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","KAT_Cavmin","Marko_BNVD_NC_UW"]],
  ["MCC_MicroT2","MCC_MicroT2_Down","MCC_EXPS3_UnityX_BLK","MCC_EXPS3_UnityX_BLK_Down","rhsusf_acc_su230_3d","Kemp_G3_G_KP_NP","UKSFOW","Zulu_MFrame_A_M_RG_TAN_SHD","Zulu_MFrame_M_RG_TAN_SHD"]] call _reg;
