// 44th SFSG ORBAT loadout library. Loadout + allowedSwap arrays copied
// verbatim from the authored kit set (New SFSG). Faction: SFSG.
// Consumed via FTH_Kits by 44th ORBAT (spawn kitting) and 44th Kit Crates.

["SFSG_PlatoonCommander", "Platoon Commander", "SFSG",
  [["P_UKSF_L119A2_SFW_BLK","P_UKSF_Acc_FA556SA_Silencer_BLK","MCC_AR_PEQ15_M300C_Tail_BLK_IRL","rhsusf_acc_su230",["MCC_PMAG_556_556_30_MK262",30],[],""],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300U","MPP_RMR_BLK",["MPP_15rnd_9MM_124FMJ_G19",15],[],""],["Friday_G3_G_KP_P",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",3],["ACE_epinephrine",2],["ACE_morphine",3],["kat_naloxone",2],["ACE_splint",1],["ACE_tourniquet",4],["ACE_quikclot",2],["ACE_EarPlugs",1],["kat_IV_16",1],["kat_Carbonate",1,10],["ACE_painkillers",1,10],["kat_Painkiller",1,4]]],["Veersamy_AVS",[["tsp_sling",1],["ACE_CableTie",5],["ItemAndroidMisc",1],["ACE_Clacker",1],["ItemcTabMisc",1],["ACE_MapTools",1],["ACE_PlottingBoard",1],["rhs_mag_m67",2,1],["rhs_mag_mk84",2,1],["UK3CB_BAF_SmokeShell",4,1],["ACE_Chemlight_IR",4,1],["ACE_Chemlight_HiRed",2,1],["MPP_15rnd_9MM_124FMJ_G19",3,15],["MCC_PMAG_556_556_30_MK262",7,30],["UK3CB_BAF_SmokeShellPurple",2,1],["acex_intelitems_notepad",1,1]]],["ZXX_Slingshot_AVS_TFAR",[["ACE_plasmaIV_500",1],["ACE_EHP",1],["ACE_Flashlight_XL50",1],["ACE_ChalkWhite",1],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["ItemcTabMisc",1],["cigs_lighter",1,100],["cigs_craven_cigpack",1,20],["GX_DEPLOYABLE_MAGAZINE_BLACKHORNET_UAV",1,100],["acex_intelitems_notepad",1,1],["rhsusf_m112_mag",1,1],["Laserbatteries",2,1]]],"Galahad_SF_CT_P_VLI","Zulu_MFrame_A_BLK_CLR",["UK3CB_BAF_Soflam_Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","KAT_Katmin","Marko_BNVD_NC_UW"]],
  ["rhsusf_acc_su230","rhsusf_acc_ACOG_RMR","MCC_EXPS3_BLK_Down","MCC_EXPS3_FDE_Down","MCC_EXPS3_UnityX_BLK_Down","MCC_EXPS3_UnityX_FDE_Down","MCC_MicroT2_Down","Grimes_Rugby_KP_NP","Grimes_Rugby_LS_KP_NP","Friday_G3_G_KP_P","Grimes_L9G2_G_KP_P","UKSFOW","Zulu_MFrame_A_BLK_CLR","Zulu_MFrame_A_M2_RG_BLK_CLR","Zulu_StepIn_BLK_CLR_SF","UK3CB_BAF_G_Balaclava_Win"]] call _reg;

["SFSG_HQDroneOperator", "HQ Drone Operator / RTO", "SFSG",
  [["ZXX_L119A1_SFW_BLK_MCC","P_UKSF_Acc_FA556SA_Silencer_BLK","MCC_AR_PEQ15_M300C_BLK_IRL","rhsusf_acc_su230",["MCC_PMAG_556_556_30_MK262",30],[],"rhsusf_acc_grip2"],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300U","MPP_RMR_BLK",["MPP_15rnd_9MM_124FMJ_G19",15],[],""],["Grimes_Rugby_KP_NP",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",3],["ACE_epinephrine",2],["ACE_morphine",3],["kat_naloxone",2],["ACE_splint",1],["ACE_tourniquet",4],["ACE_quikclot",2],["ACE_EarPlugs",1],["kat_IV_16",1],["kat_Carbonate",1,10],["ACE_painkillers",1,10],["kat_Painkiller",1,4]]],["Veersamy_AVS",[["tsp_sling",1],["ACE_CableTie",5],["ItemAndroidMisc",1],["ACE_Clacker",1],["UK3CB_BAF_SmokeShell",2,1],["ACE_Chemlight_IR",4,1],["ACE_Chemlight_HiRed",2,1],["MPP_15rnd_9MM_124FMJ_G19",3,15],["MCC_PMAG_556_556_30_MK262",6,30]]],["TRF_TRIZIP_LR",[["ACE_plasmaIV_500",1],["ACE_EHP",1],["ACE_Flashlight_XL50",1],["ACE_ChalkWhite",1],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["ItemcTabMisc",1],["GX_UAVBattery",2],["cigs_lighter",1,100],["cigs_craven_cigpack",1,20],["acex_intelitems_notepad",1,1],["rhsusf_m112_mag",1,1],["GX_DEPLOYABLE_MAGAZINE_BLACKHORNET_UAV",1,100],["GX_DEPLOYABLE_MAGAZINE_RQ11B_UAV",1,100],["BOT_magazine_FPV_AP_HD",2,1],["BOT_magazine_FPV_AP_TI",2,1],["BOT_magazine_FPV_AT_TI",1,1],["BOT_magazine_FPV_AT_HD",2,1]]],"Galahad_SF_CT_P_VLI","Zulu_MFrame_A_M2_RG_BLK_CLR",["ACE_Vector","","","",[],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","KAT_Katmin","Marko_BNVD_NC_UW"]],
  ["rhsusf_acc_su230","rhsusf_acc_ACOG_RMR","MCC_EXPS3_BLK_Down","MCC_EXPS3_FDE_Down","MCC_EXPS3_UnityX_BLK_Down","MCC_EXPS3_UnityX_FDE_Down","MCC_MicroT2_Down","Grimes_Rugby_KP_NP","Grimes_Rugby_LS_KP_NP","Friday_G3_G_KP_P","Grimes_L9G2_G_KP_P","UKSFOW","Zulu_MFrame_A_BLK_CLR","Zulu_MFrame_A_M2_RG_BLK_CLR","Zulu_StepIn_BLK_CLR_SF","UK3CB_BAF_G_Balaclava_Win"]] call _reg;

["SFSG_SectionCommander", "Section Commander", "SFSG",
  [["ZXX_L119A1_SFW_BLK_Grip_2_MCC","P_UKSF_Acc_FA556SA_Silencer_BLK","MCC_AR_PEQ15_M300C_BLK_IRL","rhsusf_acc_su230_3d",["MCC_PMAG_556_556_30_MK262",30],[],"rhsusf_acc_grip2"],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300U","MPP_RMR_BLK",["MPP_15rnd_9MM_124FMJ_G19",15],[],""],["Grimes_Rugby_KP_NP",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",3],["ACE_epinephrine",2],["ACE_morphine",3],["kat_naloxone",2],["ACE_splint",1],["ACE_tourniquet",4],["ACE_quikclot",2],["ACE_EarPlugs",1],["kat_IV_16",1],["kat_Carbonate",1,10],["ACE_painkillers",1,10],["kat_Painkiller",1,4]]],["Veersamy_AVS",[["tsp_sling",1],["ACE_CableTie",5],["ItemAndroidMisc",1],["ACE_Clacker",1],["rhs_mag_m67",2,1],["rhs_mag_mk84",2,1],["UK3CB_BAF_SmokeShell",3,1],["UK3CB_BAF_SmokeShellRed",1,1],["ACE_Chemlight_IR",4,1],["ACE_Chemlight_HiRed",2,1],["MPP_15rnd_9MM_124FMJ_G19",3,15],["MCC_PMAG_556_556_30_MK262",6,30]]],["TRF_CAMELBACK_LR",[["ACE_plasmaIV_500",1],["ACE_EHP",1],["ACE_Flashlight_XL50",1],["ACE_ChalkWhite",1],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["ItemcTabMisc",1],["tsp_lockpick",1],["cigs_lighter",1,100],["cigs_craven_cigpack",1,20],["GX_DEPLOYABLE_MAGAZINE_BLACKHORNET_UAV",1,100],["acex_intelitems_notepad",1,1],["rhsusf_m112_mag",1,1]]],"Galahad_SF_CT_P_VLI","Zulu_MFrame_A_M2_RG_BLK_CLR",["ACE_Vector","","","",[],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","KAT_Katmin","Marko_BNVD_NC_UW"]],
  ["rhsusf_acc_su230","rhsusf_acc_ACOG_RMR","MCC_EXPS3_BLK_Down","MCC_EXPS3_FDE_Down","MCC_EXPS3_UnityX_BLK_Down","MCC_EXPS3_UnityX_FDE_Down","MCC_MicroT2_Down","Grimes_Rugby_KP_NP","Grimes_Rugby_LS_KP_NP","Friday_G3_G_KP_P","Grimes_L9G2_G_KP_P","UKSFOW","Zulu_MFrame_A_BLK_CLR","Zulu_MFrame_A_M2_RG_BLK_CLR","Zulu_StepIn_BLK_CLR_SF","UK3CB_BAF_G_Balaclava_Win"]] call _reg;

["SFSG_LeadAssaulter", "Lead Assaulter / Pointman", "SFSG",
  [["ZXX_L119A2_CQB_BLK_MCC","P_UKSF_Acc_FA556SA_Silencer_BLK","MCC_AR_PEQ15_M300C_Tail_BLK_IRL","MCC_Aimpoint_Pro_T",["MCC_PMAG_556_556_30_MK262",30],[],""],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300U","MPP_RMR_BLK",["MPP_15rnd_9MM_124FMJ_G19",15],[],""],["Grimes_Rugby_KP_NP",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",3],["ACE_epinephrine",2],["ACE_morphine",3],["kat_naloxone",2],["ACE_splint",1],["ACE_tourniquet",4],["ACE_quikclot",2],["ACE_EarPlugs",1],["kat_IV_16",1],["kat_Carbonate",1,10],["ACE_painkillers",1,10],["kat_Painkiller",1,4],["MCC_PMAG_556_556_30_MK262",1,30]]],["Galahad_AVS_A_P",[["tsp_sling",1],["ACE_CableTie",5],["ItemAndroidMisc",1],["tsp_breach_shock",1],["ACE_Clacker",1],["ACE_DefusalKit",1],["UK3CB_BAF_SmokeShell",2,1],["rhs_mag_mk84",4,1],["rhs_mag_m67",2,1],["ACE_Chemlight_IR",4,1],["ACE_Chemlight_HiGreen",2,1],["MPP_15rnd_9MM_124FMJ_G19",2,15],["MCC_PMAG_556_556_30_MK262",7,30]]],["ZXX_AVS_Panel4B",[["ACE_plasmaIV_500",1],["ACE_EHP",1],["ACE_Flashlight_XL50",1],["ACE_IR_Strobe_Item",1],["ACE_SpraypaintRed",1],["ACE_wirecutter",1],["cigs_lighter",1,100],["cigs_craven_cigpack",1,20],["acex_intelitems_notepad",1,1],["rhsusf_m112_mag",2,1],["tsp_breach_stick_mag",1,1],["tsp_breach_popper_mag",2,1],["tsp_breach_block_mag",2,1],["tsp_breach_linear_mag",2,1]]],"Galahad_SF_CT_P_VLI","Zulu_MFrame_A_M2_RG_BLK_CLR",[],["ItemMap","","TFAR_anprc152","ItemCompass","KAT_Katmin","Marko_BNVD_NC_UW"]],
  ["MCC_EXPS3_BLK","MCC_EXPS3_FDE","MCC_EXPS3_UnityX_BLK","MCC_EXPS3_UnityX_FDE","MCC_Aimpoint_Pro_T","MCC_MicroT2","Grimes_Rugby_KP_NP","Grimes_Rugby_LS_KP_NP","Friday_G3_G_KP_P","Grimes_L9G2_G_KP_P","UKSFOW","Zulu_MFrame_A_BLK_CLR","Zulu_MFrame_A_M2_RG_BLK_CLR","Zulu_StepIn_BLK_CLR_SF","UK3CB_BAF_G_Balaclava_Win"]] call _reg;

["SFSG_SectionGrenadier", "Section Grenadier", "SFSG",
  [["ZXX_L119A1_UGL_BLK_MCC","P_UKSF_Acc_FA556SA_Silencer_BLK","","rhsusf_acc_ACOG_RMR",["MCC_PMAG_556_556_30_MK262",30],["UK3CB_BAF_1Rnd_HE_Grenade_Shell",1],""],["rhs_weap_m72a7","","rhsusf_acc_anpeq15side","",[],[],""],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300U","MPP_RMR_BLK",["MPP_15rnd_9MM_124FMJ_G19",15],[],""],["Grimes_Rugby_KP_NP",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",3],["ACE_epinephrine",2],["ACE_morphine",3],["kat_naloxone",2],["ACE_splint",1],["ACE_tourniquet",4],["ACE_quikclot",2],["ACE_EarPlugs",1],["kat_IV_16",1],["kat_Carbonate",1,10],["ACE_painkillers",1,10],["kat_Painkiller",1,4]]],["Veersamy_AVS",[["tsp_sling",1],["ACE_CableTie",5],["ItemAndroidMisc",1],["MCC_PMAG_556_556_30_MK262",6,30],["UK3CB_BAF_1Rnd_HE_Grenade_Shell",6,1],["UK3CB_BAF_1Rnd_Smoke_Grenade_shell",2,1],["UK3CB_BAF_UGL_FlareRed_F",1,1],["UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",2,1],["rhs_mag_m67",1,1],["rhs_mag_mk84",2,1],["UK3CB_BAF_SmokeShell",1,1],["ACE_Chemlight_IR",4,1],["MPP_15rnd_9MM_124FMJ_G19",3,15]]],["ZXX_AVS_Panel1",[["ACE_plasmaIV_500",1],["ACE_EHP",1],["ACE_Flashlight_XL50",1],["ACE_IR_Strobe_Item",1],["cigs_lighter",1,100],["cigs_craven_cigpack",1,20]]],"Galahad_SF_CT_P_VLI","Zulu_MFrame_A_M2_RG_BLK_CLR",["ACE_Yardage450","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","KAT_Katmin","Marko_BNVD_NC_UW"]],
  ["rhsusf_acc_su230","rhsusf_acc_ACOG_RMR","MCC_EXPS3_BLK_Down","MCC_EXPS3_FDE_Down","MCC_EXPS3_UnityX_BLK_Down","MCC_EXPS3_UnityX_FDE_Down","MCC_MicroT2_Down","Grimes_Rugby_KP_NP","Grimes_Rugby_LS_KP_NP","Friday_G3_G_KP_P","Grimes_L9G2_G_KP_P","UKSFOW","Zulu_MFrame_A_BLK_CLR","Zulu_MFrame_A_M2_RG_BLK_CLR","Zulu_StepIn_BLK_CLR_SF","UK3CB_BAF_G_Balaclava_Win"]] call _reg;

["SFSG_SectionMedic", "Section Medic", "SFSG",
  [["ZXX_L119A2_CQB_BLK_MCC","P_UKSF_Acc_FA556SA_Silencer_BLK","MCC_AR_PEQ15_M300C_Tail_BLK_IRL","MCC_EXPS3_FDE",["MCC_PMAG_556_556_30_MK262",30],[],""],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300U","MPP_RMR_BLK",["MPP_15rnd_9MM_124FMJ_G19",15],[],""],["Grimes_Rugby_KP_NP",[["kat_IV_16",8],["ACE_adenosine",8],["kat_amiodarone",3],["ACE_elasticBandage",15],["ACE_packingBandage",15],["kat_chestSeal",10],["ACE_epinephrine",10],["kat_IO_FAST",3],["kat_fentanyl",2],["kat_ketamine",2],["kat_larynx",8],["ACE_morphine",8],["kat_naloxone",8],["kat_Pulseoximeter",2],["ACE_tourniquet",8],["kat_TXA",10],["ACE_quikclot",10],["ACE_EarPlugs",1],["kat_Carbonate",2,10],["ACE_painkillers",2,10]]],["Veersamy_AVS",[["tsp_sling",1],["ACE_CableTie",5],["ItemAndroidMisc",1],["ACE_Flashlight_XL50",1],["ACE_IR_Strobe_Item",1],["ACE_EHP",1],["MCC_PMAG_556_556_30_MK262",5,30],["MPP_15rnd_9MM_124FMJ_G19",3,15],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellBlue",2,1],["ACE_Chemlight_IR",4,1],["rhs_mag_mk84",2,1],["rhs_mag_m67",1,1],["cigs_lighter",1,100],["acex_intelitems_notepad",1,1]]],["ZuluMed2",[["kat_aatKit",4],["kat_accuvac",2],["kat_X_AED",1],["ACE_plasmaIV_500",4],["ACE_splint",3],["kat_stethoscope",1],["ACE_surgicalKit",1],["ACE_elasticBandage",15],["ACE_packingBandage",15],["kat_BVM",2],["ACE_plasmaIV",5],["kat_amiodarone",5],["kat_EACA",5],["cigs_craven_cigpack",3,20]]],"Galahad_SF_CT_P_VLI","Zulu_MFrame_A_M2_RG_BLK_CLR",[],["ItemMap","","TFAR_anprc152","ItemCompass","KAT_Katmin","Marko_BNVD_NC_UW"]],
  ["MCC_EXPS3_BLK","MCC_EXPS3_FDE","MCC_EXPS3_UnityX_BLK","MCC_EXPS3_UnityX_FDE","MCC_Aimpoint_Pro_T","MCC_MicroT2","MCC_EXPS3_BLK_Down","MCC_EXPS3_FDE_Down","MCC_EXPS3_UnityX_BLK_Down","MCC_EXPS3_UnityX_FDE_Down","MCC_MicroT2_Down","Grimes_Rugby_KP_NP","Grimes_Rugby_LS_KP_NP","Adams_G3_G_KP_P","Grimes_L9G2_G_KP_P","UKSFOW","Zulu_MFrame_A_BLK_CLR","Zulu_MFrame_A_M2_RG_BLK_CLR","Zulu_StepIn_BLK_CLR_SF","UK3CB_BAF_G_Balaclava_Win"]] call _reg;

["SFSG_Section2iC", "Section 2iC", "SFSG",
  [["ZXX_L119A1_SFW_BLK_Grip_2_MCC","P_UKSF_Acc_FA556SA_Silencer_BLK","MCC_AR_PEQ15_M300C_BLK_IRL","rhsusf_acc_su230_3d",["MCC_PMAG_556_556_30_MK262",30],[],"rhsusf_acc_grip2"],["rhs_weap_m72a7","","rhsusf_acc_anpeq15side","",[],[],""],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300U","MPP_RMR_BLK",["MPP_15rnd_9MM_124FMJ_G19",15],[],""],["Grimes_Rugby_KP_NP",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",3],["ACE_epinephrine",2],["ACE_morphine",3],["kat_naloxone",2],["ACE_splint",1],["ACE_tourniquet",4],["ACE_quikclot",2],["ACE_EarPlugs",1],["kat_IV_16",1],["kat_Carbonate",1,10],["ACE_painkillers",1,10],["kat_Painkiller",1,4]]],["Veersamy_AVS",[["tsp_sling",1],["ACE_CableTie",5],["ItemAndroidMisc",1],["ACE_Clacker",1],["MPP_15rnd_9MM_124FMJ_G19",3,15],["UK3CB_BAF_SmokeShell",3,1],["UK3CB_BAF_SmokeShellGreen",1,1],["rhs_mag_mk84",2,1],["rhs_mag_m67",2,1],["ACE_Chemlight_IR",4,1],["MCC_PMAG_556_556_30_MK262",6,30]]],["TRF_CAMELBACK_LR",[["ACE_plasmaIV_500",1],["ACE_EHP",1],["ACE_Flashlight_XL50",1],["ACE_IR_Strobe_Item",1],["ACE_ChalkYellow",1],["tsp_lockpick",1],["cigs_lighter",1,100],["cigs_craven_cigpack",1,20],["GX_DEPLOYABLE_MAGAZINE_BLACKHORNET_UAV",1,100],["rhsusf_m112_mag",1,1],["ClaymoreDirectionalMine_Remote_Mag",2,1]]],"Galahad_SF_CT_P_VLI","Zulu_MFrame_A_M2_RG_BLK_CLR",["ACE_Vector","","","",[],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","KAT_Katmin","Marko_BNVD_NC_UW"]],
  ["rhsusf_acc_su230","rhsusf_acc_ACOG_RMR","MCC_EXPS3_BLK_Down","MCC_EXPS3_FDE_Down","MCC_EXPS3_UnityX_BLK_Down","MCC_EXPS3_UnityX_FDE_Down","MCC_MicroT2_Down","Grimes_Rugby_KP_NP","Grimes_Rugby_LS_KP_NP","Friday_G3_G_KP_P","Grimes_L9G2_G_KP_P","UKSFOW","Zulu_MFrame_A_BLK_CLR","Zulu_MFrame_A_M2_RG_BLK_CLR","Zulu_StepIn_BLK_CLR_SF","UK3CB_BAF_G_Balaclava_Win"]] call _reg;

["SFSG_SectionGunner", "Section Gunner", "SFSG",
  [["UK3CB_BAF_L110_762","UK3CB_BAF_Silencer_L110","MCC_NGAL_IRL","rhsusf_acc_su230a",["rhsusf_100Rnd_762x51_m80a1epr",100],[],""],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300U","MPP_ACRO_BLK",["MPP_15rnd_9MM_124FMJ_G19",15],[],""],["Grimes_Rugby_KP_NP",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",3],["ACE_epinephrine",2],["ACE_morphine",3],["kat_naloxone",2],["ACE_splint",1],["ACE_tourniquet",4],["ACE_quikclot",2],["ACE_EarPlugs",1],["kat_IV_16",1],["kat_Carbonate",1,10],["ACE_painkillers",1,10],["kat_Painkiller",1,4],["rhsusf_100Rnd_762x51_m80a1epr",1,100]]],["Drake_AVS_Slick",[["tsp_sling",1],["ACE_CableTie",5],["ItemAndroidMisc",1],["rhsusf_100Rnd_762x51_m80a1epr",2,100],["UK3CB_BAF_SmokeShell",2,1],["rhs_mag_m67",1,1],["rhs_mag_mk84",1,1],["ACE_Chemlight_IR",4,1],["MPP_15rnd_9MM_124FMJ_G19",2,15]]],["ZXX_Backpack_1_MC_AVS",[["ACE_plasmaIV_500",1],["ACE_EHP",1],["ACE_Flashlight_XL50",1],["ACE_IR_Strobe_Item",1],["cigs_lighter",1,100],["cigs_craven_cigpack",1,20]]],"Galahad_SF_CT_P_VLI","Zulu_MFrame_A_M2_RG_BLK_CLR",["ACE_Yardage450","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","KAT_Katmin","Marko_BNVD_NC_UW"]],
  ["UK3CB_BAF_L110_762","UK3CB_BAF_L110A3","rhsusf_acc_su230","rhsusf_acc_ACOG_RMR","MCC_EXPS3_BLK_Down","MCC_EXPS3_FDE_Down","MCC_EXPS3_UnityX_BLK_Down","MCC_EXPS3_UnityX_FDE_Down","MCC_MicroT2_Down","Grimes_Rugby_KP_NP","Grimes_Rugby_LS_KP_NP","Friday_G3_G_KP_P","Grimes_L9G2_G_KP_P","UKSFOW","Zulu_MFrame_A_BLK_CLR","Zulu_MFrame_A_M2_RG_BLK_CLR","Zulu_StepIn_BLK_CLR_SF","UK3CB_BAF_G_Balaclava_Win"]] call _reg;

["SFSG_SectionSharpshooter", "Section Sharpshooter", "SFSG",
  [["Louetta_HK417_3","MCC_HuxWrx_Flow_762TI","MCC_NGAL_IRL","MCC_Mark5_10_FDE",["Louetta_20Rnd_762x51mm",20],[],"MSS_Harris_SBRMP"],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300U","MPP_RMR_BLK",["MPP_15rnd_9MM_124FMJ_G19",15],[],""],["Grimes_Rugby_KP_NP",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",3],["ACE_epinephrine",2],["ACE_morphine",3],["kat_naloxone",2],["ACE_splint",1],["ACE_tourniquet",4],["ACE_quikclot",2],["ACE_EarPlugs",1],["kat_IV_16",1],["kat_Carbonate",1,10],["ACE_painkillers",1,10],["kat_Painkiller",1,4]]],["Drake_AVS_Slick",[["tsp_sling",1],["ACE_CableTie",5],["ItemAndroidMisc",1],["ACE_Flashlight_XL50",1],["ACE_Kestrel4500",1],["ACE_ATragMX",1],["ACE_RangeCard",1],["Louetta_20Rnd_762x51mm_IRTM",7,20],["UK3CB_BAF_SmokeShell",2,1],["ACE_Chemlight_IR",4,1],["rhs_mag_m67",1,1],["rhs_mag_mk84",1,1],["MPP_15rnd_9MM_124FMJ_G19",3,15]]],["Marko_NJPC_AVS1000",[["ACE_plasmaIV_500",1],["ACE_EHP",1],["ACE_IR_Strobe_Item",1],["ACE_SpottingScope",1],["ACE_Tripod",1],["cigs_lighter",1,100],["cigs_craven_cigpack",1,20]]],"Galahad_SF_CT_P_VLI","Zulu_MFrame_A_M2_RG_BLK_CLR",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","KAT_Katmin","Marko_BNVD_NC_UW"]],
  ["MCC_Mark5_10_FDE","rhsusf_acc_su230","vel_ss_jeans_t_g","Grimes_Rugby_KP_NP","Grimes_Rugby_LS_KP_NP","Friday_G3_G_KP_P","Grimes_L9G2_G_KP_P","UKSFOW","Zulu_MFrame_A_BLK_CLR","Zulu_MFrame_A_M2_RG_BLK_CLR","Zulu_StepIn_BLK_CLR_SF","UK3CB_BAF_G_Balaclava_Win","zxx_molot_lapa_mc_v1_face","zxx_molot_lapa_mct_v1_face","zxx_molot_lapa_mcal_v1_face"]] call _reg;

["SFSG_AntiTankRifleman", "Anti-Tank Rifleman", "SFSG",
  [["ZXX_L119A2_CQB_BLK_MCC","P_UKSF_Acc_FA556SA_Silencer_BLK","MCC_AR_PEQ15_M300C_Tail_BLK_IRL","MCC_MicroT2",["MCC_PMAG_556_556_30_MK262",30],[],""],["UK3CB_BAF_NLAW_Launcher","","","",[],[],""],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300U","MPP_RMR_BLK",["MPP_15rnd_9MM_124FMJ_G19",15],[],""],["Grimes_Rugby_KP_NP",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",3],["ACE_epinephrine",2],["ACE_morphine",3],["kat_naloxone",2],["ACE_splint",1],["ACE_tourniquet",4],["ACE_quikclot",2],["ACE_EarPlugs",1],["kat_IV_16",1],["kat_Carbonate",1,10],["ACE_painkillers",1,10],["kat_Painkiller",1,4]]],["Drake_AVS_Slick",[["tsp_sling",1],["ACE_CableTie",5],["ItemAndroidMisc",1],["MPP_15rnd_9MM_124FMJ_G19",2,15],["UK3CB_BAF_SmokeShell",2,1],["rhs_mag_mk84",2,1],["rhs_mag_m67",2,1],["ACE_Chemlight_IR",4,1],["MCC_PMAG_556_556_30_MK262",5,30]]],["ZXX_AVS_Panel7_MC2_NB_NH",[["ACE_plasmaIV_500",1],["ACE_EHP",1],["ACE_Flashlight_XL50",1],["ACE_IR_Strobe_Item",1],["ACE_Clacker",1],["cigs_lighter",1,100],["cigs_craven_cigpack",1,20],["rhsusf_m112_mag",2,1],["rhsusf_50Rnd_762x51_m80a1epr",2,50]]],"Galahad_SF_CT_P_VLI","Zulu_MFrame_A_M2_RG_BLK_CLR",[],["ItemMap","","TFAR_anprc152","ItemCompass","KAT_Katmin","Marko_BNVD_NC_UW"]],
  ["MCC_EXPS3_BLK","MCC_EXPS3_FDE","MCC_EXPS3_UnityX_BLK","MCC_EXPS3_UnityX_FDE","MCC_Aimpoint_Pro_T","MCC_MicroT2","MCC_EXPS3_BLK_Down","MCC_EXPS3_FDE_Down","MCC_EXPS3_UnityX_BLK_Down","MCC_EXPS3_UnityX_FDE_Down","MCC_MicroT2_Down","Grimes_Rugby_KP_NP","Grimes_Rugby_LS_KP_NP","Friday_G3_G_KP_P","Grimes_L9G2_G_KP_P","UKSFOW","Zulu_MFrame_A_BLK_CLR","Zulu_MFrame_A_M2_RG_BLK_CLR","Zulu_StepIn_BLK_CLR_SF","UK3CB_BAF_G_Balaclava_Win"]] call _reg;

["SFSG_SupportCommander", "Support Section Commander", "SFSG",
  [["P_UKSF_L119A2_SFW_BLK_Grip_2","P_UKSF_Acc_FA556SA_Silencer_BLK","MCC_AR_PEQ15_M300C_BLK_IRL","rhsusf_acc_su230_3d",["MCC_PMAG_556_556_30_MK262",30],[],"rhsusf_acc_grip2"],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300U","MPP_RMR_BLK",["MPP_15rnd_9MM_124FMJ_G19",15],[],""],["Grimes_Rugby_KP_NP",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",3],["ACE_epinephrine",2],["ACE_morphine",3],["kat_naloxone",2],["ACE_splint",1],["ACE_tourniquet",4],["ACE_quikclot",2],["ACE_EarPlugs",1],["kat_IV_16",1],["kat_Carbonate",1,10],["ACE_painkillers",1,10],["kat_Painkiller",1,4]]],["Veersamy_AVS",[["tsp_sling",1],["ACE_CableTie",5],["ItemAndroidMisc",1],["ACE_Clacker",1],["MPP_15rnd_9MM_124FMJ_G19",3,15],["UK3CB_BAF_SmokeShell",3,1],["UK3CB_BAF_SmokeShellRed",1,1],["rhs_mag_mk84",2,1],["rhs_mag_m67",2,1],["ACE_Chemlight_IR",4,1],["MCC_PMAG_556_556_30_MK262",6,30]]],["TRF_CAMELBACK_LR",[["ACE_plasmaIV_500",1],["ACE_EHP",1],["ACE_Flashlight_XL50",1],["ACE_IR_Strobe_Item",1],["GX_UAVBattery",1],["tsp_lockpick",1],["cigs_lighter",1,100],["cigs_craven_cigpack",1,20],["GX_DEPLOYABLE_MAGAZINE_BLACKHORNET_UAV",1,100],["acex_intelitems_notepad",1,1],["rhsusf_m112_mag",2,1]]],"Galahad_SF_CT_P_VLI","Zulu_MFrame_A_M2_RG_BLK_CLR",["ACE_Vector","","","",[],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","KAT_Katmin","Marko_BNVD_NC_UW"]],
  ["rhsusf_acc_su230","rhsusf_acc_ACOG_RMR","MCC_EXPS3_BLK_Down","MCC_EXPS3_FDE_Down","MCC_EXPS3_UnityX_BLK_Down","MCC_EXPS3_UnityX_FDE_Down","MCC_MicroT2_Down","Grimes_Rugby_KP_NP","Grimes_Rugby_LS_KP_NP","Friday_G3_G_KP_P","Grimes_L9G2_G_KP_P","UKSFOW","Zulu_MFrame_A_BLK_CLR","Zulu_MFrame_A_M2_RG_BLK_CLR","Zulu_StepIn_BLK_CLR_SF","UK3CB_BAF_G_Balaclava_Win"]] call _reg;

["SFSG_HeavySupportGunner", "Heavy Support Gunner", "SFSG",
  [["P_UKSF_L7A2","","","UK3CB_BAF_TA648_308",["UK3CB_BAF_762_200Rnd",200],[],""],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300U","MPP_RMR_BLK",["MPP_15rnd_9MM_124FMJ_G19",15],[],""],["Grimes_Rugby_KP_NP",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",3],["ACE_epinephrine",2],["ACE_morphine",3],["kat_naloxone",2],["ACE_splint",1],["ACE_tourniquet",4],["ACE_quikclot",2],["ACE_EarPlugs",1],["kat_IV_16",1],["kat_Carbonate",1,10],["ACE_painkillers",1,10],["kat_Painkiller",1,4],["rhsusf_100Rnd_762x51_m82_blank",1,0],["rhsusf_100Rnd_762x51",1,0]]],["Drake_AVS_Slick",[["tsp_sling",1],["ACE_CableTie",5],["ItemAndroidMisc",1],["UK3CB_BAF_762_200Rnd",2,200],["UK3CB_BAF_762_100Rnd",1,100],["MPP_15rnd_9MM_124FMJ_G19",2,15],["UK3CB_BAF_SmokeShell",2,1],["ACE_Chemlight_IR",4,1]]],["ZXX_Backpack_1_MC_AVS",[["ACE_plasmaIV_500",1],["ACE_EHP",1],["ACE_Flashlight_XL50",1],["ACE_IR_Strobe_Item",1],["ACE_Tripod",1],["UK3CB_BAF_MaxiKite",1],["cigs_lighter",1,100],["cigs_craven_cigpack",1,20]]],"Galahad_SF_CT_P_VLI","Zulu_MFrame_A_M2_RG_BLK_CLR",[],["ItemMap","","TFAR_anprc152","ItemCompass","KAT_Katmin","Marko_BNVD_NC_UW"]],
  ["Grimes_Rugby_KP_NP","Grimes_Rugby_LS_KP_NP","Friday_G3_G_KP_P","Grimes_L9G2_G_KP_P","UKSFOW","Zulu_MFrame_A_BLK_CLR","Zulu_MFrame_A_M2_RG_BLK_CLR","Zulu_StepIn_BLK_CLR_SF","UK3CB_BAF_G_Balaclava_Win"]] call _reg;

["SFSG_AssistantGunner", "Assistant Gunner / Ammo Bearer", "SFSG",
  [["ZXX_L119A1_SFW_BLK_Grip_2_MCC","P_UKSF_Acc_FA556SA_Silencer_BLK","MCC_AR_PEQ15_M300C_Tail_BLK_IRL","rhsusf_acc_ACOG_RMR_3d",["MCC_PMAG_556_556_30_MK262",30],[],"rhsusf_acc_grip2"],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300U","MPP_RMR_BLK",["MPP_15rnd_9MM_124FMJ_G19",15],[],""],["Grimes_Rugby_KP_NP",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",3],["ACE_epinephrine",2],["ACE_morphine",3],["kat_naloxone",2],["ACE_splint",1],["ACE_tourniquet",4],["ACE_quikclot",2],["ACE_EarPlugs",1],["kat_IV_16",1],["kat_Carbonate",1,10],["ACE_painkillers",1,10],["kat_Painkiller",1,4]]],["Veersamy_AVS",[["tsp_sling",1],["ACE_CableTie",5],["ItemAndroidMisc",1],["MPP_15rnd_9MM_124FMJ_G19",3,15],["UK3CB_BAF_SmokeShell",3,1],["ACE_Chemlight_IR",4,1],["rhs_mag_m67",2,1],["rhs_mag_mk84",2,1],["MCC_PMAG_556_556_30_MK262",6,30]]],["ZXX_CL",[["ACE_plasmaIV_500",1],["ACE_EHP",1],["ACE_Flashlight_XL50",1],["ACE_IR_Strobe_Item",1],["cigs_lighter",1,100],["cigs_craven_cigpack",1,20],["UK3CB_BAF_762_200Rnd",3,200]]],"Galahad_SF_CT_P_VLI","Zulu_MFrame_A_M2_RG_BLK_CLR",["ACE_Yardage450","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","KAT_Katmin","Marko_BNVD_NC_UW"]],
  ["rhsusf_acc_su230","rhsusf_acc_ACOG_RMR","MCC_EXPS3_BLK_Down","MCC_EXPS3_FDE_Down","MCC_EXPS3_UnityX_BLK_Down","MCC_EXPS3_UnityX_FDE_Down","MCC_MicroT2_Down","Grimes_Rugby_KP_NP","Grimes_Rugby_LS_KP_NP","Friday_G3_G_KP_P","Grimes_L9G2_G_KP_P","UKSFOW","Zulu_MFrame_A_BLK_CLR","Zulu_MFrame_A_M2_RG_BLK_CLR","Zulu_StepIn_BLK_CLR_SF","UK3CB_BAF_G_Balaclava_Win"]] call _reg;

["SFSG_SupportSection2iC", "Section Support 2iC", "SFSG",
  [["P_UKSF_L119A2_SFW_BLK_Grip_2","P_UKSF_Acc_FA556SA_Silencer_BLK","MCC_AR_PEQ15_M300C_BLK_IRL","rhsusf_acc_su230_3d",["MCC_PMAG_556_556_30_MK262",30],[],"rhsusf_acc_grip2"],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300U","MPP_RMR_BLK",["MPP_15rnd_9MM_124FMJ_G19",15],[],""],["Grimes_Rugby_KP_NP",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",3],["ACE_epinephrine",2],["ACE_morphine",3],["kat_naloxone",2],["ACE_splint",1],["ACE_tourniquet",4],["ACE_quikclot",2],["ACE_EarPlugs",1],["kat_IV_16",1],["kat_Carbonate",1,10],["ACE_painkillers",1,10],["kat_Painkiller",1,4]]],["Veersamy_AVS",[["tsp_sling",1],["ACE_CableTie",5],["ItemAndroidMisc",1],["ACE_Clacker",1],["UK3CB_BAF_SmokeShell",3,1],["UK3CB_BAF_SmokeShellGreen",1,1],["ACE_Chemlight_IR",4,1],["rhs_mag_m67",2,1],["rhs_mag_mk84",2,1],["MCC_PMAG_556_556_30_MK262",6,30],["MPP_15rnd_9MM_124FMJ_G19",3,15]]],["TRF_CAMELBACK_LR",[["ACE_plasmaIV_500",1],["ACE_EHP",1],["ACE_Flashlight_XL50",1],["ACE_IR_Strobe_Item",1],["GX_UAVBattery",1],["tsp_lockpick",1],["cigs_lighter",1,100],["cigs_craven_cigpack",1,20],["GX_DEPLOYABLE_MAGAZINE_BLACKHORNET_UAV",1,100],["rhsusf_m112_mag",2,1],["ClaymoreDirectionalMine_Remote_Mag",2,1]]],"Galahad_SF_CT_P_VLI","Zulu_MFrame_A_M2_RG_BLK_CLR",[],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","KAT_Katmin","Marko_BNVD_NC_UW"]],
  ["rhsusf_acc_su230","rhsusf_acc_ACOG_RMR","MCC_EXPS3_BLK_Down","MCC_EXPS3_FDE_Down","MCC_EXPS3_UnityX_BLK_Down","MCC_EXPS3_UnityX_FDE_Down","MCC_MicroT2_Down","Grimes_Rugby_KP_NP","Grimes_Rugby_LS_KP_NP","Friday_G3_G_KP_P","Grimes_L9G2_G_KP_P","UKSFOW","Zulu_MFrame_A_BLK_CLR","Zulu_MFrame_A_M2_RG_BLK_CLR","Zulu_StepIn_BLK_CLR_SF","UK3CB_BAF_G_Balaclava_Win"]] call _reg;

["SFSG_ATSpecialist1", "Anti-Tank Specialist #1", "SFSG",
  [["ZXX_L119A1_CQB_BLK_Grip_2_MCC","P_UKSF_Acc_FA556SA_Silencer_BLK","MCC_AR_PEQ15_M300C_BLK_IRL","MCC_Aimpoint_Pro_T",["MCC_PMAG_556_556_30_MK262",30],[],"rhsusf_acc_grip2"],["UK3CB_BAF_Javelin_Slung_Tube","","","",[],[],""],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300U","MPP_RMR_BLK",["MPP_15rnd_9MM_124FMJ_G19",15],[],""],["Grimes_Rugby_KP_NP",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",3],["ACE_epinephrine",2],["ACE_morphine",3],["kat_naloxone",2],["ACE_splint",1],["ACE_tourniquet",4],["ACE_quikclot",2],["ACE_EarPlugs",1],["kat_IV_16",1],["kat_Carbonate",1,10],["ACE_painkillers",1,10],["kat_Painkiller",1,4]]],["Galahad_AVS_L_NP",[["tsp_sling",1],["ACE_CableTie",5],["ItemAndroidMisc",1],["MPP_15rnd_9MM_124FMJ_G19",2,15],["MCC_PMAG_556_556_30_MK262",6,30],["UK3CB_BAF_SmokeShell",2,1],["rhs_mag_mk84",2,1],["rhs_mag_m67",1,1],["ACE_Chemlight_IR",4,1]]],["ZXX_AVS_Panel7_MC2_NB_NH",[["ACE_plasmaIV_500",1],["ACE_EHP",1],["ACE_Flashlight_XL50",1],["ACE_IR_Strobe_Item",1],["cigs_lighter",1,100],["cigs_craven_cigpack",1,20]]],"Galahad_SF_CT_P_VLI","Zulu_MFrame_A_M2_RG_BLK_CLR",["UK3CB_BAF_Javelin_CLU","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","KAT_Katmin","Marko_BNVD_NC_UW"]],
  ["MCC_EXPS3_BLK","MCC_EXPS3_FDE","MCC_EXPS3_UnityX_BLK","MCC_EXPS3_UnityX_FDE","MCC_Aimpoint_Pro_T","MCC_MicroT2","MCC_EXPS3_BLK_Down","MCC_EXPS3_FDE_Down","MCC_EXPS3_UnityX_BLK_Down","MCC_EXPS3_UnityX_FDE_Down","MCC_MicroT2_Down","Grimes_Rugby_KP_NP","Grimes_Rugby_LS_KP_NP","Friday_G3_G_KP_P","Grimes_L9G2_G_KP_P","UKSFOW","Zulu_MFrame_A_BLK_CLR","Zulu_MFrame_A_M2_RG_BLK_CLR","Zulu_StepIn_BLK_CLR_SF","UK3CB_BAF_G_Balaclava_Win"]] call _reg;

["SFSG_ATSpecialist2", "Anti-Tank Specialist #2", "SFSG",
  [["ZXX_L119A1_CQB_BLK_Grip_2_MCC","P_UKSF_Acc_FA556SA_Silencer_BLK","MCC_AR_PEQ15_M300C_BLK_IRL","MCC_Aimpoint_Pro_T",["MCC_PMAG_556_556_30_MK262",30],[],""],["louetta_walker_MRAWS","","","",["rhs_mag_maaws_HEAT",1],[],""],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300U","MPP_RMR_BLK",["MPP_15rnd_9MM_124FMJ_G19",15],[],""],["Grimes_Rugby_KP_NP",[["ACE_elasticBandage",10],["ACE_packingBandage",10],["kat_chestSeal",3],["ACE_epinephrine",2],["ACE_morphine",3],["kat_naloxone",2],["ACE_splint",1],["ACE_tourniquet",4],["ACE_quikclot",2],["ACE_EarPlugs",1],["kat_IV_16",1],["kat_Carbonate",1,10],["ACE_painkillers",1,10],["kat_Painkiller",1,4],["MCC_PMAG_556_556_30_MK262",1,30]]],["Galahad_AVS_L_NP",[["tsp_sling",1],["ACE_CableTie",5],["ItemAndroidMisc",1],["MCC_PMAG_556_556_30_MK262",5,30],["MPP_15rnd_9MM_124FMJ_G19",2,15],["UK3CB_BAF_SmokeShell",2,1],["ACE_Chemlight_IR",4,1],["rhs_mag_m67",1,1],["rhs_mag_mk84",2,1]]],["ZXX_3DAP",[["ACE_plasmaIV_500",1],["ACE_EHP",1],["ACE_Flashlight_XL50",1],["ACE_IR_Strobe_Item",1],["cigs_lighter",1,100],["cigs_craven_cigpack",1,20],["rhs_mag_maaws_HEDP",2,1],["rhs_mag_maaws_HEAT",2,1]]],"Galahad_SF_CT_P_VLI","Zulu_MFrame_A_M2_RG_BLK_CLR",[],["ItemMap","","TFAR_anprc152","ItemCompass","KAT_Katmin","Marko_BNVD_NC_UW"]],
  ["MCC_EXPS3_BLK","MCC_EXPS3_FDE","MCC_EXPS3_UnityX_BLK","MCC_EXPS3_UnityX_FDE","MCC_Aimpoint_Pro_T","MCC_MicroT2","MCC_EXPS3_BLK_Down","MCC_EXPS3_FDE_Down","MCC_EXPS3_UnityX_BLK_Down","MCC_EXPS3_UnityX_FDE_Down","MCC_MicroT2_Down","Grimes_Rugby_KP_NP","Grimes_Rugby_LS_KP_NP","Friday_G3_G_KP_P","Grimes_L9G2_G_KP_P","UKSFOW","Zulu_MFrame_A_BLK_CLR","Zulu_MFrame_A_M2_RG_BLK_CLR","Zulu_StepIn_BLK_CLR_SF","UK3CB_BAF_G_Balaclava_Win"]] call _reg;

["SFSG_SupportMedic", "Support Section Medic", "SFSG",
  [["ZXX_L119A1_CQB_BLK_Grip_2_MCC","P_UKSF_Acc_FA556SA_Silencer_BLK","MCC_AR_PEQ15_M300C_BLK_IRL","MCC_EXPS3_UnityX_BLK",["MCC_PMAG_556_556_30_MK262",30],[],"rhsusf_acc_grip2"],[],["MPP_G19_BLK_9","MPP_G19_TC","MPP_X300U","MPP_RMR_BLK",["MPP_15rnd_9MM_124FMJ_G19",15],[],""],["Grimes_Rugby_NKP_NP",[["kat_IV_16",8],["ACE_adenosine",8],["kat_amiodarone",3],["ACE_elasticBandage",15],["ACE_packingBandage",15],["kat_chestSeal",10],["ACE_epinephrine",10],["kat_IO_FAST",3],["kat_fentanyl",2],["kat_ketamine",2],["kat_larynx",8],["ACE_morphine",8],["kat_naloxone",8],["kat_Pulseoximeter",2],["ACE_tourniquet",8],["kat_TXA",10],["ACE_quikclot",10],["ACE_EarPlugs",1],["kat_Carbonate",2,10],["ACE_painkillers",2,10]]],["Veersamy_AVS",[["tsp_sling",1],["ACE_CableTie",5],["ItemAndroidMisc",1],["ACE_Flashlight_XL50",1],["ACE_IR_Strobe_Item",1],["ACE_EHP",1],["MPP_15rnd_9MM_124FMJ_G19",3,15],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellBlue",2,1],["ACE_Chemlight_IR",4,1],["rhs_mag_mk84",2,1],["rhs_mag_m67",1,1],["cigs_lighter",1,100],["acex_intelitems_notepad",1,1],["MCC_PMAG_556_556_30_MK262",5,30]]],["ZuluMed2",[["kat_aatKit",4],["kat_accuvac",2],["kat_X_AED",1],["ACE_plasmaIV_500",4],["ACE_splint",3],["kat_stethoscope",1],["ACE_surgicalKit",1],["ACE_elasticBandage",15],["ACE_packingBandage",15],["kat_BVM",2],["ACE_plasmaIV",5],["kat_amiodarone",5],["kat_EACA",5],["cigs_craven_cigpack",3,20]]],"Galahad_SF_CT_P_VLI","Zulu_MFrame_A_M2_RG_BLK_CLR",[],["ItemMap","","TFAR_anprc152","ItemCompass","KAT_Katmin","Marko_BNVD_NC_UW"]],
  ["MCC_EXPS3_BLK","MCC_EXPS3_FDE","MCC_EXPS3_UnityX_BLK","MCC_EXPS3_UnityX_FDE","MCC_Aimpoint_Pro_T","MCC_MicroT2","MCC_EXPS3_BLK_Down","MCC_EXPS3_FDE_Down","MCC_EXPS3_UnityX_BLK_Down","MCC_EXPS3_UnityX_FDE_Down","MCC_MicroT2_Down","Grimes_Rugby_KP_NP","Grimes_Rugby_LS_KP_NP","Adams_G3_G_KP_P","Grimes_L9G2_G_KP_P","UKSFOW","Zulu_MFrame_A_BLK_CLR","Zulu_MFrame_A_M2_RG_BLK_CLR","Zulu_StepIn_BLK_CLR_SF","UK3CB_BAF_G_Balaclava_Win"]] call _reg;
